### ISSUE TITLE
Blank project

### ISSUE THREAD

**Issue by vynt-kenshiro** [bwsw/cloudstack-ui#1]
Hello,

I want to test your project. When you upload your code ?

**Comment by bwsw** [comment]
Hey, we plan to publish first production-ready release at the end of the month, since we are in the middle of the process right now. Keep in touch.

**Comment by bwsw** [comment]
Hello, I deployed a comprehensive README.md which shows what to expect from UI and screenshots. We are finalizing the code and fixing found bugs, so quite soon release it. Plan to do it at the end of the next week:

https://bwsw.github.io/cloudstack-ui/

**Comment by bwsw** [comment]
Hello, Initial release is deployed. We still have some open issues regarind the current release, but most of the functions must be functional.
