### ISSUE TITLE
Ability to add a Firewall rule with empty ICMP type/code

### ISSUE THREAD

**Issue by chewlite** [bwsw/cloudstack-ui#1000]
There is no validation for empty ICMP type/code and no asterisks but these fields are required.
There is ability to add a rule when _empty ICMP type_ or _ICMP code_ or _ICMP type and ICMP code simultaneously_

Steps:

**1.** Go to Firewall rules editing
**2.** Select ICMP protocol and input valid IP

**3.1** Click on empty ICMP type/code then click on neutral area
Expected result: ICMP type/code is invalid, add-button is disabled
Actual result: ICMP type/code is valid, add-button is enabled

**3.2** Fill "ICMP type/code" by some numbers, then delete _type_ or _code_ or _two of them simultaneously_ and click add
Expected result: add-button is disabled 
Actual result: add-button is enabled, the rule created with type and code
![deleted type](https://user-images.githubusercontent.com/32011943/36419066-78e80d88-1663-11e8-8d5f-826d10037b5d.png)
![deleted code](https://user-images.githubusercontent.com/32011943/36419071-7b8bb2e2-1663-11e8-9a93-88a5ec6c753d.png)
![deleted type code](https://user-images.githubusercontent.com/32011943/36419076-7dcf3290-1663-11e8-88cb-39b8c9872454.png)

**Connected Feature ID:**
_firewall_rules_edit
vm_firewall_rules_edit_

**Comment by chewlite** [comment]
Also there is ability to add the rule and no validation when Start port is greater then End port

**Comment by ershovaelena** [comment]
TBD in #1019

**Comment by tamazlykar** [comment]
PR fixes #1019, #1000, and 3.2 item at #997
Please test there only #1000

Test on:
tamazlykar/1019-firewall-rules

Regression:
firewall_rules_edit
vm_firewall_rules_edit

**Comment by chewlite** [comment]
@tamazlykar 

Fails in **_firewall_rules_edit, vm_firewall_rules_edit_**:

1) If I understand comment by @qqcky in [#920](https://github.com/bwsw/cloudstack-ui/issues/920) correctly, unassigned types and codes also could be entered in ICMP type/code fields. Then we must have an ability to enter any value [0;255] and it must be valid

2) Steps:
1 - input valid CIDR, ICMP type and code (or don't touch ICMP type and code, or input and clear ICMP type and code)
2 - clear the CIDR
_Expected:_ 
ICMP type and code are disabled
_Actual:_
ICMP type and code are enabled
