### ISSUE TITLE
unable to login if password contains "+" sign

### ISSUE THREAD

**Issue by serverchief** [bwsw/cloudstack-ui#1001]
It appears some special characters arent supported in password string.

I can confirm that when my password contains "+" - i'm not able to login.

Please address this issue when possible.

**Comment by ershovaelena** [comment]
@serverchief hello. Does this problem still persist? If yes, could you please describe concrete steps to reproduce it?

 We've tried to reproduce it, but we have no problem with logging in using a password which includes "+".

**Comment by bwsw** [comment]
@serverchief Can't reproduce. If you will find the problem still present, please share the detailed report with us.
