### ISSUE TITLE
No confirmation for Delete snapshot

### ISSUE THREAD

**Issue by Nadya913** [bwsw/cloudstack-ui#1002]
http://cs-ui-ci.z1.netpoint-dc.com:8080/bwsw/master/snapshots?date=2018-02-21

Steps:
1. Login and go to Snapshots
2. Delete the snapshot

Expected result: Dialog "Are you sure you want to delete this snapshot?" with No/Yes buttons
Actual result: Snapshot is deleted

**Comment by tamazlykar** [comment]
Test on:
tamazlykar/1002-snapshot-confirmation-dialog

**Comment by rennervo** [comment]
Tested on tamazlykar/1002-snapshot-confirmation-dialog
