### ISSUE TITLE
Added firewall rules aren't displayed when going to another section

### ISSUE THREAD

**Issue by chewlite** [bwsw/cloudstack-ui#1003]
Steps:
1) Go to editing of any custom template/security group 
2) Add some rules
3) Go to another section and back
4) Open the rules view of the same custom template/security group 

Expected result: added rules are displayed
Actual result: added rules aren't displayed, after page refresh only

Right after add:
![rule displayed](https://user-images.githubusercontent.com/32011943/36709218-4c86d314-1ba9-11e8-8619-46f25b7fd8e5.png)
After going to another section and back:
![rule isn t displayed](https://user-images.githubusercontent.com/32011943/36709224-50e3d272-1ba9-11e8-8136-fdc8de9187d1.png)

**Connected Feature ID:**
firewall_rules_view
vm_firewall_rules_view

**Comment by chewlite** [comment]
@ershovaelena 
Repeated for firewall_tag_display (after create/update/delete tags)

**Comment by ershovaelena** [comment]
This issue is blocked by #894. To fix after this issue is closed

**Comment by tamazlykar** [comment]
Main issue not reproduced after #1105 
I'll fix the issue with tags

**Comment by tamazlykar** [comment]
**Test on:**
tamazlykar/1003-firewall-tags

**Regression:**
firewall_rules_view
vm_firewall_rules_view

**Comment by chewlite** [comment]
Progress:
Chrome +
