### ISSUE TITLE
Orphan filter applies to Templates and Shared SGs

### ISSUE THREAD

**Issue by chewlite** [bwsw/cloudstack-ui#1004]
Steps:

1. Go to Firewall, Private tab, and check Orphan (without active filter and search)
2. Switch to other tabs

Expected: all templates/shared SGs are displayed in according tabs, in Private - orphan private SGs

Actual: in Private - orphan private SGs, in Shared - orphan shared SGs, when switch to Templates - last content is freezed for all tabs, error in console

![1004 change tab](https://user-images.githubusercontent.com/32011943/36777771-564e3118-1c9d-11e8-94de-5eba58cf96b4.png)
![piece of code for orphan templates](https://user-images.githubusercontent.com/32011943/36829160-5fe53a88-1d50-11e8-8237-4eb69ad9e367.png)

Connected Feature ID:
_firewall_list_private_orphan_

**Comment by tamazlykar** [comment]
**Test on:**
tamazlykar/1004-orphan

**Regression:**
firewall_list_private_orphan

**Comment by chewlite** [comment]
Tested on:
tamazlykar/1004-orphan
