### ISSUE TITLE
Position of switcher "Templates/ISO" in Images tab is reset after go to "Activity Log" tab

### ISSUE THREAD

**Issue by rennervo** [bwsw/cloudstack-ui#1005]
The error is only reproduced when switching to the "active log" tab. Position of switcher "Templates/ISO" is saved when switching to other main tabs.
Steps:
- Log in and go to Images
- Set switcher "Templates/ISO" to ISO parameter
- Go to "Activity Log"
- Go to "Images"

Actual result: Position of switcher is reset
Expected result: Position of switcher is saved
Connected feature: image_list_switch
![ISO TEmplate.png](https://images.zenhubusercontent.com/5a5c77c24b5806bc2bc2be22/8fa82687-cec5-42a7-aa55-efd8f6d232af)

**Comment by tamazlykar** [comment]
**Test on:**
tamazlykar/1005-switcher

**Regression:**
image_list_switch

**Comment by tamazlykar** [comment]
Issue was closed by mistake and branch was merged so you can test it on the master branch

**Comment by chewlite** [comment]
@tamazlykar 

Tested on master in all browsers (except IE - blocked)
