### ISSUE TITLE
Action box of Images isn't available for role "User"

### ISSUE THREAD

**Issue by rennervo** [bwsw/cloudstack-ui#1006]
Action box on image list and image sidebar isn't available for User with role "User"

Actual result: Action box of Images isn't available for role "User"
Expected result: Action box of Images is available for role "User"
Connected feature: image_actionbox

![ABTemplate.png](https://images.zenhubusercontent.com/5a5c77c24b5806bc2bc2be22/0c3b43d3-4792-4262-a066-f3c19806228c)
![ABISO.png](https://images.zenhubusercontent.com/5a5c77c24b5806bc2bc2be22/7151015b-9b5a-4bac-9b19-0144bc968c37)

**Comment by tamazlykar** [comment]
Test on: 
tamazlykar/1006-action-box-on-image-list
Regression:
image_actionbox

**Comment by rennervo** [comment]
Action box in Image sidebar isn't available for role "User" (Template and ISO)
Steps:
1. Log in as role User and go to Images
2. Press to any User's Image
3. Go to "Template" tab in Image sidebar

Actual result: Action box is missing at top of Image sidebar.
Expected result: Action box is present at top of Image sidebar.

Image Sidebar of User

**Comment by tamazlykar** [comment]
**Test on:**
tamazlykar/1006-action-box-on-image-list

**Regression:**
image_actionbox

**Comment by chewlite** [comment]
@tamazlykar 

Tested on tamazlykar/1006-action-box-on-image-list in all browsers (except IE - blocked)
