### ISSUE TITLE
Navigation errors using keyboard

### ISSUE THREAD

**Issue by rennervo** [bwsw/cloudstack-ui#1007]
1) **Items in action boxes cannot be selected by using a keyboard**
Connected features: _vm_actionbox, storage_actionbox, image_actionbox, volsnapshot_actionbox,_ _firewall_actionbox, account_actionbox, account_user_actionbox_ 

**Steps:**
- Log in and go to a tab where the action boxes are used (e.g. VM)
- Select "Action box" button of any card by using "Tab" and press Enter

**Actual result:** Only first item can be selected by using a keyboard. 
**Expected result:** Any item of action box can be selected by using a keyboard. 

2) **Action box isn't closed when switching to another element by using a keyboard** 
Connected features: _vm_actionbox, storage_actionbox, image_actionbox, volsnapshot_actionbox, firewall_actionbox, account_actionbox, account_user_actionbox_ 

**Steps:**
- Log in and go to a tab where the action boxes are used (e.g. VM)
- Select "Action box" button of any card by using "Tab" and press Enter
- Switch to next card by using "Tab" and press Enter

**Actual result:** Opened action boxes aren't closed after switching to next card;
**Expected result:** Opened action boxes are closed after switching to next card;

![TAB+ENTER.png](https://images.zenhubusercontent.com/5a5c77c24b5806bc2bc2be22/d597b5b6-c405-4db8-9369-a6046f286207)

**Comment by ershovaelena** [comment]
Low priority bag
