### ISSUE TITLE
Order of "Group by" field items is reset after refresh / back+forward / switch between main tabs

### ISSUE THREAD

**Issue by rennervo** [bwsw/cloudstack-ui#1008]
Order of "Group by" field items is reset, but filtering of cards remains correct.

Steps:
- Log in and go to a tab that has "Group by" filter (e.g. Images)
- Select two or more items in filter "Group by" and change their order
- Refresh of page / Back + Forward / Switch between main tabs

Actual result: Order of "Group by" field items is reset
Expected result: Order of "Group by" field items is saved

Connected feature: vm_list_groupby, image_list_groupby, storage_list_groupby, volsnapshot_list_groupby, account_list_groupby

Screenshots:
Before refresh / back+forward / switch between main tabs
![BeforeREF.png](https://images.zenhubusercontent.com/5a5c77c24b5806bc2bc2be22/37b2cfb2-67b2-4a23-adc7-b77b12c28b5f)
After refresh / back+forward / switch between main tabs
![AfterREF.png](https://images.zenhubusercontent.com/5a5c77c24b5806bc2bc2be22/501bcf20-b586-478d-a13b-1abe5a6333fb)

**Comment by tamazlykar** [comment]
Regression:
vm_list_groupby, image_list_groupby, storage_list_groupby, volsnapshot_list_groupby, account_list_groupby, sshkey_list_groupby

**Comment by chewlite** [comment]
After refresh / back+forward / switch between main tabs checked options in "Group by" moved to beginning of the list
![before refresh](https://user-images.githubusercontent.com/32011943/39033186-14253ffe-449b-11e8-9bdb-344e94c993ac.png)
![after refresh](https://user-images.githubusercontent.com/32011943/39033188-169751c8-449b-11e8-9e2f-58498630dd90.png)

**Comment by ershovaelena** [comment]
@chewlite @tamazlykar let's stick to current solution. A comment of @chewlite will be considered inrefactoring where we use ngrx/store in "group by" components.
