### ISSUE TITLE
Image is created when wrong Web protocol is specified

### ISSUE THREAD

**Issue by rennervo** [bwsw/cloudstack-ui#1009]
Validation of path to Template / ISO file occurs after creation of Image. This allows you to create an Image that can not be used.

Steps:
- Log in and go to Images
- Create new Images by replacing Web protocol (e.g. http --> https)

Actual result: Creating of Images is successful. Error occurs when downloading Template / ISO file;
Expected result: Validation of path to file occurs before creating an image.

**Connected feature ID:** image_template_create, image_iso_create

Screenshots:
![PathFileImages.png](https://images.zenhubusercontent.com/5a5c77c24b5806bc2bc2be22/88375946-49e2-4d00-831e-459cbf3a5afc)

**Comment by tamazlykar** [comment]
This is a bug but it does not apply to the client side of the application. This check should be performed by the server. According to PO we only need to make sure that the URL is valid.
So I improved the validation because only "http://" or "https://" strings was valid.
Check this issue.

**Comment by tamazlykar** [comment]
**Test on:**
tamazlykar/1009-url-regex

**Regression:** 
image_template_create
image_iso_create
