### ISSUE TITLE
Tag is deleted if try to change Key value to existing one

### ISSUE THREAD

**Issue by rennervo** [bwsw/cloudstack-ui#1010]
Editable Tag is deleted after changing Key to an existing Key and refreshing the page

Steps:
- Log in and go to Tab that has tags of cards (e.g. Images)
- Go to tags tab of any card and replace the key of one existing tag with the key of the other one
- Refresh page

Actual result: An error occurs with the existing key, edited tag is deleted
Expected result: An error occurs with the existing key, edited tag remains with previous values 

Connected feature: image_tag_edit, vm_tag_edit, firewall_tag_edit

**Comment by ershovaelena** [comment]
This issue includes research on effects

**Comment by tamazlykar** [comment]
@Nadya913  Issue was closed by mistake and branch was merged so you can test it on the master branch

**Comment by rennervo** [comment]
Tested on master
