### ISSUE TITLE
Buttons "Create", "Edit" and "Delete" for template tags are absent for user

### ISSUE THREAD

**Issue by rennervo** [bwsw/cloudstack-ui#1012]
Buttons "Create", "Edit" and "Delete" tags aren't available for role "User" in Images tab.

Steps:
- Log in and go to Images;
- Go to Tags tab of any Template or ISO

Actual result: Buttons for manage of tags aren't available for a role "User"
Expected result: Buttons for manage of tags are available for a role "User"

Connected feature: image_tag_create, image_tag_edit, image_tag_delete

Screenshot:
![TagsButtons.png](https://images.zenhubusercontent.com/5a5c77c24b5806bc2bc2be22/95bacea9-826f-48dd-b46e-a4945e75b801)

**Comment by tamazlykar** [comment]
Test on:
tamazlykar/1012-template-tags-action-buttons
Regression:
image_tag_create, image_tag_edit, image_tag_delete

**Comment by rennervo** [comment]
Tested on tamazlykar/1012-template-tags-action-buttons
