### ISSUE TITLE
Checkbox "Show system tags" hides nonsystem tags starting with "csui"

### ISSUE THREAD

**Issue by rennervo** [bwsw/cloudstack-ui#1013]
Checkbox "Show system tags" hide nonsystem tags together with system tags. 
Nonsystem tags will be hidden if their keys begin with "csui", next characters does not matter.
If tags, that begin not with "csui", are in tags group, then this group will not be hidden.

**Steps:**
- Log in and go to tab, that has tags on cards (e.g. Images) 
- Go to Tags tab of any card and create tags: 1) csui.xxxxx (system); 2) csuixxxxx (nonsystem)
- Press to "Show system tags"

**Actual result:** System and nonsystem tags are hidden 
**Expected result:** Only system tags are hidden

**Connected feature:** vm_tag_showsystem, image_tag_showsystem, firewall_tag_showsystem

**Screenshots:**
Before check "Show system tags"
![systemtagson](https://user-images.githubusercontent.com/26665398/37010902-592c953c-2120-11e8-9f1e-0389f85eb0a0.png)

After check "Show system tags"
![systemtagsoff](https://user-images.githubusercontent.com/26665398/37010911-5efd8ab6-2120-11e8-882c-433388613184.png)

After check "Show system tags" with additional tag, that not begin with "csui"
![systemtagsnot](https://user-images.githubusercontent.com/26665398/37010914-62bf1836-2120-11e8-9de2-84b086ddae16.png)

**Comment by tamazlykar** [comment]
Issue was closed by mistake and branch was merged so you can test it on the master branch

**Comment by Nadya913** [comment]
Please, retest it on master

**Comment by rennervo** [comment]
Tested on master
