### ISSUE TITLE
Time format isn't changed without refresh page or logout - log in (ngrx)

### ISSUE THREAD

**Issue by rennervo** [bwsw/cloudstack-ui#1014]
The format of Time values in the system does not change immediately after setting. You need to refresh the page or log out + log in to display the time values in the new correct format.

**Steps:**
- Log in and go to Settings
- Change Time Format value to opposite
- Go to any tab, that has value in time format (e.g. "Time" parameter in entries of "Activity log" tab)

**Actual result:** Time values are displayed in old Time format
**Expected result:** Time values are displayed in new Time format

**Connected feature:** settings_timeformat_change

**Screenshots:**
![changetimeformat](https://user-images.githubusercontent.com/26665398/37035881-88c044be-2180-11e8-98cb-45d9e78818bd.png)

Go to Activity Log
![beforetimeformat](https://user-images.githubusercontent.com/26665398/37035902-957045e2-2180-11e8-90c6-744a061910aa.png)

Refresh page or logout + log in
![aftertimeformat](https://user-images.githubusercontent.com/26665398/37035915-a08a1cb4-2180-11e8-8732-8a21e1930a24.png)

**Comment by ershovaelena** [comment]
@tamazlykar fixing this bug includes moving to ngrx/store (Settings module)

**Comment by tamazlykar** [comment]
Includes #1140 #1143

**Comment by tamazlykar** [comment]
Please read PR description #1150 

**Regression:**
notification_snackbar (check one notification per section of the app)

Everething in settings:
settings_password_change
settings_sessiontimeout_change
settings_password_saveall
settings_apikey_display
settings_apikey_regenerate
settings_apikey_copy
settings_url_display
settings_doclink_display
settings_language_change
settings_firstdayweek_change
settings_timeformat_change
settings_themecolor_change

account_user_apikey_copy
account_user_secretkey_copy
image_url_copy

vm_creation_agreement

vm_tag_display

**Comment by Nadya913** [comment]
2. For russian language the first day of the week appears in english.
Expected: For russian language the first day of the week appears in russian.

**Comment by rennervo** [comment]
Errors from PR [#1150](https://github.com/bwsw/cloudstack-ui/pull/1150):
**1. Tag "Password" = "undefined" is created when option "Save all password" is checked**
![2018-08-03 13-38-53](https://user-images.githubusercontent.com/26665398/43634298-edcf47f8-9735-11e8-8269-5e33c99a9c36.png)

**2. VM password does not save manually when option "Save all password" isn't checked**

**3. Scrolling of the license confirmation dialog when creating a VM is not fixed**
License confirmation dialog is scrolled to down after confirm create VM

**Comment by rennervo** [comment]
**vm_tag_display**
Error with resetting password wasn't fixed.

Steps:
1. Make sure that the option "Save all passwords" is disabled in the settings
2. Go to VM and create new VM that has a password
3. Save password after the creation is complete
4. Perform the "Reset Password" action for this VM
5. Don't save password after changing the password
6. Go to tab "Tags" in a sidebar of this VM

Actual result: "Password" tag value is Old password
Expected result: There isn't tag "Password"
![error with reset password](https://user-images.githubusercontent.com/26665398/43694764-323829ca-995f-11e8-9d7e-1009d4ada086.png)
