### ISSUE TITLE
Notification box does not react to some operation from notification box list

### ISSUE THREAD

**Issue by rennervo** [bwsw/cloudstack-ui#1015]
Notification box does not support some operations, that are indicated "Notification box operation" list.

**Next operations are not supported:**

**Volume**
- CREATION_IN_PROGRESS
- CREATION_DONE
- CREATION_FAILED
- DELETION_IN_PROGRESS
- DELETION_DONE
- DELETION_FAILED

**ISO**
- REGISTER_IN_PROGRESS
- REGISTER_DONE
- REGISTER_FAILED
- DELETION_IN_PROGRESS
- DELETION_DONE
- DELETION_FAILED

**Account**
- DELETION_IN_PROGRESS
- DELETION_DONE
- DELETION_FAILED
- DISABLE_IN_PROGRESS
- DISABLE_DONE
- DISABLE_FAILED
- ENABLE_IN_PROGRESS
- ENABLE_DONE
- ENABLE_FAILED

_Deprecated:_
_**VM:**_
_- TAG_EDIT_DONE_
_- TAG_ADD_DONE_
_- TAG_REMOVE_DONE_

**Connected feature:** 
notification_bell
notification_snackbar
notification_modal

**Comment by ershovaelena** [comment]
@ershovaelena to discuss with PO the unification of notifications, to create "strategy" and than fix this problem

**Comment by tamazlykar** [comment]
@rennervo notification for tags actions deprecated

**Comment by ershovaelena** [comment]
@rennervo @Nadya913 @chewlite please note that there is a new feature ID "snackbar" that should be checked (you can find it in Feature list)

**Comment by tamazlykar** [comment]
Please read the information from the PR #1097 
PR implement much more notifications than discussed here, so please see notifications list in the documents.

**Comment by chewlite** [comment]
**FAILS:**

**VM**

1. EXPUNGE_IN_PROGRESS
When expunging from destroying dialog - text in bell "Destroying a VM"
_Expected:_ 
"Expunging a VM" 
or 
"Destroying a VM" then "Expunging a VM"

2. EXPUNGE_DONE
When expunging from destroying dialog and from actionbox - text in snackbar "VM expunged" (disappears very fast) then "Private security group deleted"
_Expected:_ "VM expunged"

3. EXPUNGE_FAILED
When expunging from destroying dialog - text in bell "Failed to destroy a VM"
_Expected:_ "Failed to expunge a VM"

4. DEPLOY_FAILED
There is deploy window with error plus modal window with error
_Expected:_ there is deploy window with error only

5. ADD_SECONDARY_IP_FAILED
IP is added, but there is modal window with error
_Expected:_ there is no modal window with error

6. SAVE_PASSWORD_DONE 
No snackbar
_Expected:_ there is snackbar with notification

7. SAVE_PASSWORD_FAILED
No modal window
_Expected:_ there is modal window with error 

**Snapshots:**

8. REVERT_DONE
Text of notifications in bell and in snackbar "Диск возращен к снимку"
_Expected:_ "Диск возВращен к снимку"

**Template:**

9. REGISTER_IN_PROGRESS
There are no notification in bell, and the created template isn't displayed immediately after creation, after refresh only
_Expected:_ there is notification in bell, and the created template is displayed immediately after creation

10. REGISTER_DONE
No notification in bell 
_Expected:_ there is notification in bell

11. REGISTER_FAILED
No modal window, no notification in bell 
_Expected:_ there is modal window with error and notification in bell

**ISO:**

12. REGISTER_DONE
No notification in bell 
_Expected:_ there is notification in bell

13. REGISTER_FAILED
No modal window, no notification in bell 
_Expected:_ there is modal window with error and notification in bell

**Accounts:**

14. ENABLE_IN_PROGRESS, ENABLE_DONE, ENABLE_FAILED
No notification in bell 
_Expected:_ there are notifications in bell

**There is deploy window or throbber - no way to see what's in bell:**
VM - DEPLOY_IN_PROGRESS
VM - CREATION_VOLUME_FROM_SNAPSHOT_IN_PROGRESS
Template - CREATION_IN_PROGRESS
ISO - REGISTER_IN_PROGRESS

**There are throbbers:** 
Firewall - SHARED_GROUP_CREATION_DONE
Firewall - TEMPLATE_CREATION_DONE

**Operations that I couldn't perform:**

VM:
FETCH_STATISTICS_FAILED
CHANGE_DESCRIPTION_FAILED
REMOVE_INSTANCE_GROUP_FAILED

Volume: 
DETACHMENT_FAILED
DELETION_FAILED
ATTACHMENT_IN_PROGRESS (from vm)
ATTACHMENT_DONE (from vm)
ATTACHMENT_FAILED (from vm)

ISO: 
ATTACHMENT_FAILED
DETACHMENT_FAILED
DELETION_FAILED

Accounts:
DELETION_FAILED
DISABLE_IN_PROGRESS
DISABLE_DONE
ACCOUNT_USER_GENERATE_KEYS_FAILED

**Comment by chewlite** [comment]
Tested on:
tamazlykar/1015-notifications
