### ISSUE TITLE
Grouping isn't saved, Delete buttons are absent, redirect to wrong tab when shared SG rules edit through VM sidebar

### ISSUE THREAD

**Issue by chewlite** [bwsw/cloudstack-ui#1016]
Steps

1) Log in and go to sidebar of VM with shared security group
2) Open the rule view and select some parameters of grouping
3) Go to rules edit

Expected result: redirect to Shared SGs tab, there are delete buttons, grouping is saved
Actual result: redirect to Firewall Templates tab, there are no delete buttons, grouping isn't saved
(If Shared SGs tab was opened before going to VMs then redirect will be to this tab)

![rules view vm](https://user-images.githubusercontent.com/32011943/37068940-c7dda4f8-21e3-11e8-8930-9129719c2aa9.png)
![rules edit vm](https://user-images.githubusercontent.com/32011943/37069221-0599012e-21e5-11e8-9600-5503ebf1ec7b.png)

Connected Feature ID:
vm_firewall_rules_edit

**Comment by ershovaelena** [comment]
Check that there is no blocking form #1019 (form was refactored)

**Comment by tamazlykar** [comment]
Test on:
tamazlykar/1016-shared-sg-rules

Regression:
vm_firewall_rules_edit

**Comment by rennervo** [comment]
Tested on tamazlykar/1016-shared-sg-rules
