### ISSUE TITLE
The same error message for adding firewall rules that are invalid for different reasons

### ISSUE THREAD

**Issue by chewlite** [bwsw/cloudstack-ui#1018]
The same message pops up at the bottom when different mistakes allowed when rules creating:
1) invalid IP
Expected result: Invalid IP address

2) start port > end port
Expected result: Start port is greater then End port

3) duplicated rule
Expected result: The rule already exists

Actual result for all cases:
![2018-03-07 10-00-34](https://user-images.githubusercontent.com/32011943/37073166-d98cdfb6-21f7-11e8-8bf6-801715f3b798.png)
![default](https://user-images.githubusercontent.com/32011943/37073167-d9ae0560-21f7-11e8-93b6-7d7245878037.png)

**Connected feature ID:**
firewall_rules_edit
vm_firewall_rules_edit

**Comment by rennervo** [comment]
will be resolved in 997
