### ISSUE TITLE
Ability to add a Firewall rule and no validation when incorrect Start and End ports 

### ISSUE THREAD

**Issue by chewlite** [bwsw/cloudstack-ui#1019]
Steps:

1) Go to firewall rules editing
2) Fill Start port by greater value then End port, click add

Expected result: Start and End ports are invalid, add button is disabled
Actual result: Start and End ports are valid, add button is enabled

**Connected Feature ID:**
firewall_rules_edit
vm_firewall_rules_edit

**Comment by ershovaelena** [comment]
Includes #1000

**Comment by tamazlykar** [comment]
Please see 

Test on:
tamazlykar/1019-firewall-rules

Regression:
firewall_rules_view (just layout)
firewall_rules_edit

**Comment by chewlite** [comment]
@tamazlykar 

Fail in **_firewall_rules_edit, vm_firewall_rules_edit_**

Steps:
1. Input the Start port and the End port < Start port
2. Input the Start port < End port
Expected result: 
Start and End ports are valid, Add button is enabled
Actual result:
Start port is valid, End port is invalid, Add button is disabled

Also repeats for Start port

**Comment by tamazlykar** [comment]
@chewlite second item is not a bug. This was discussed with PO and its fine. 
The types and codes that are missing in the specification are not considered when executed. But in the current implementation, we can not create a rule with nonexistent codes.

**Comment by tamazlykar** [comment]
@chewlite fixed.

Test on:
tamazlykar/1019-firewall-rules

**Comment by chewlite** [comment]
@tamazlykar 

Tested on: tamazlykar/1019-firewall-rules
