### ISSUE TITLE
Domain Admin has an ability to delete his own Account

### ISSUE THREAD

**Issue by chewlite** [bwsw/cloudstack-ui#1020]
Steps:

1. Create a user in account with role Domain Admin
2. Log in under that new user and go to Accounts

Expected result: no actionbox in the card/sidebar of his own account
Actual result: actionbox in the card/sidebar of his own account where all actions are enabled

**Connected Feature ID:**
account_actionbox

**Comment by tamazlykar** [comment]
Unable to reproduce bug
@Nadya913

**Comment by tamazlykar** [comment]
@Nadya913  Issue was closed by mistake and branch was merged so you can test it on the master branch

**Comment by chewlite** [comment]
There is actionbox in the sidebar of new user Account where all actions are enabled

**Comment by tamazlykar** [comment]
@Nadya913 test it on the master branch

**Comment by rennervo** [comment]
Tested on master
