### ISSUE TITLE
Error when install dependencies with npm

### ISSUE THREAD

**Issue by tamazlykar** [bwsw/cloudstack-ui#1024]
When install dependencies using npm then error appears when you build project, but with yarn everything is ok.

Steps:
Remove node_modules
Run npm install
Run npm  test (or any other command that build project)

![screenshot from 2018-03-20 11-25-30](https://user-images.githubusercontent.com/18456914/37635951-6fa74624-2c31-11e8-962b-4e2d4ad2a662.png)

Same as #931

**Comment by Voltisky** [comment]
Try this steps:
Remove node_modules
Next run npm install
Next run yarn
Next run npm test

Dont forget to install newest version of yarn and npm.

**Comment by tamazlykar** [comment]
Yes this approach with npm works fine. But not everyone uses yarn, so this issue should be fixed for npm users
