### ISSUE TITLE
I want to create examples of various systems, but I don't know that cloudstack specifically supports those systems and the version number of the system.

### ISSUE THREAD

**Issue by LYXmoonstars** [bwsw/cloudstack-ui#1050]
I want to create examples of various systems, but I don't know that cloudstack specifically supports those systems and the version number of the system.

**Comment by bwsw** [comment]
@LYXmoonstars it's not a cloudstack repo, it's cloudstack-ui - specific product for cloudstack. Please, refer to cloudstack to ask your question.
