### ISSUE TITLE
Icons don't have tool-tisp on snapshot dialog window from vm sidebar 

### ISSUE THREAD

**Issue by tamazlykar** [bwsw/cloudstack-ui#1052]
Icons don't have tool-tips on snapshot dialog window from VM sidebar (storage > view all button)

Steps:
1. Go to Virtual machines
2. Select VM and go to Storage tab in the sidebar (you need to find VM with snapshot or create a 
new one)
3.Click on View all button.

![screenshot from 2018-04-18 09-17-58](https://user-images.githubusercontent.com/18456914/38966246-796b97f0-43ab-11e8-897c-8ef295cbc11f.png)

Feature ID:
vm_vmsnap_viewall

**Comment by ershovaelena** [comment]
@tamazlykar please add feature ID to descritpion

**Comment by tamazlykar** [comment]
@ershovaelena description was updated

**Comment by tamazlykar** [comment]
Test on:
tamazlykar/1052-tooltips

Regression:
vm_vmsnap_viewall

**Comment by chewlite** [comment]
@tamazlykar 
Tested on tamazlykar/1052-tooltips
