### ISSUE TITLE
System isn't available for IE browser because of syntax error

### ISSUE THREAD

**Issue by rennervo** [bwsw/cloudstack-ui#1059]
Access to the system there isn't for IE browser. Error: "SCRIPT1002: Syntax error" there is when going to http://cs-ui-ci.z1.netpoint-dc.com:8080/bwsw/master/

Browser IE (ver. 11.0.9600.18860)

Steps:
1) Go to http://cs-ui-ci.z1.netpoint-dc.com:8080/bwsw/master/

Actual result: Syntax error there is and endless trobber on display
Expected result: Login page is opened

Screenshot:
![IE error.png](https://images.zenhubusercontent.com/5a5c77c24b5806bc2bc2be22/d0a59b68-80fc-4977-a530-bcc9116f95db)

**Comment by pm-Egor-Genning** [comment]
https://github.com/bwsw/cloudstack-ui/pull/1073

**Comment by pm-Egor-Genning** [comment]
1059-IE-browser-support

**Comment by chewlite** [comment]
Tested on http://cs-ui-ci.z1.netpoint-dc.com:8080/bwsw/983-sidebar-values-for-parameters
