### ISSUE TITLE
Add Prettier for better formatting

### ISSUE THREAD

**Issue by tamazlykar** [bwsw/cloudstack-ui#1061]
This is a feature request to add Prettier in the project.
Currently, tslint and .editorconfig can do some code style normalize but they do not enough.

Using prettier could normalize code style more, avoid difference, it's much more useful to allow different IDE.

The plan
1. [x] Research whether style guide can be combined with Prettier
2. [x] Check out google and Airbnb style guides (optional)
3. [x] Discuss with a team which styleguide to use (if to use) and decide (optional)
4. [x] Configure tslint
5. [x] Configure codelyzer
6. [x] Configure Prettier
7. [x] Fix lint errors (if needed)
8. [ ] Create pre-commit hook or update CI.

**Comment by ershovaelena** [comment]
@tamazlykar when this issue is closed, provide @Nadya913 @rennervo @chewlite  with the information about style guide.

**Comment by tamazlykar** [comment]
During implementing this task I find a bug that in access VM dialog in the webshell tab, ssh key not appears. 
I'll fix it here.

**Comment by tamazlykar** [comment]
The second bug about changing compute offering for VM.
Cannot change compute offering for VM even if I have a lot of available resources. The bug only about CPU number.

Prerequisites:
- An account has a limitation to CPU number equal 3.
- An account doesn't have any VM.
Steps:
1. Create a VM with 1 core so 2 more will be available for you after creation.
2. Try to change a compute offering for created VM. You should see an error that the service offering cannot be selected because it doesn't fit the account resources available.

**Comment by tamazlykar** [comment]
The third bug about filtering VM by groups. This was not worked at all.

**Comment by chewlite** [comment]
@tamazlykar 

All bug fixes from comments are tested in all browsers.
Surface testing of the entire system was performed in Chrome.

Fails:
1) The badge on the notification bell with the number of unwatched operations does not disappear after opening the bell

_Steps:_ 
1. Start/stop any VM
2. Wait until the operation will complete
3. Open the notification bell
_Actual:_ the badge isn't disappeared
_Expected:_ the badge is disappeared

2) The calendar isn't displayed in Snapshots and Activity log
![2018-10-19 13-08-19](https://user-images.githubusercontent.com/32011943/47200359-1415c800-d3a0-11e8-8a96-18458b069a5d.png)

**Comment by chewlite** [comment]
@tamazlykar 

Fails from the comment above are tested

**Comment by chewlite** [comment]
@tamazlykar

lack:2

Firewall rules in shared/private SGs and SG templates cannot be deleted

**Steps:**

1. Open the Edit window for shared/private SG or SG template
2. Add the new rule
3. Click to Delete button next to rule

**Actual result:**
Infinite throbber, after page refresh - error in the console, the rule isn't deleted
![2018-10-22 14-21-20](https://user-images.githubusercontent.com/32011943/47284104-42014380-d610-11e8-9af2-0e9b331f840a.png)
![2018-10-22 14-21-58](https://user-images.githubusercontent.com/32011943/47284108-44fc3400-d610-11e8-9037-a7f186ed2964.png)

**Expected result:**
The rule is deleted, no errors

**Comment by wowshakhov** [comment]
to test: pulse plugin

**Comment by Nadya913** [comment]
Pulse plugin can't be test - request  for permitted-intervals is failed.
