### ISSUE TITLE
VM creation: no response after going to Installation source

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#1063]
Browser Chrome

Steps:
1. Go to VM list
2. Click VM creation
3. Go to Installation source
4. Click any other button

Expected result: action is available
Actual result: no response from UI, only reloading page gets back to action

**Comment by tamazlykar** [comment]
Test on: 
tamazlykar/1063-vm-creation

Regression:
vm_creation
vm_creation_installsource

**Comment by chewlite** [comment]
@tamazlykar 
Tested on: tamazlykar/1063-vm-creation
