### ISSUE TITLE
Do not search by description and do not show it for storage section

### ISSUE THREAD

**Issue by tamazlykar** [bwsw/cloudstack-ui#1069]
We should not search by description and do not show it for Storage section. This is discussed with PO.
This will cover additional task in #963 

![](https://user-images.githubusercontent.com/26665398/38795628-121b36de-4183-11e8-8461-c80e92cde45a.png)

**Comment by tamazlykar** [comment]
Test on:
tamazlykar/1069-description-on-cards

Regression:
storage_card
storage_list_search

**Comment by chewlite** [comment]
@tamazlykar 
Tested on: tamazlykar/1069-description-on-cards
