### ISSUE TITLE
Hints duplicate text of card fields in Images section

### ISSUE THREAD

**Issue by tamazlykar** [bwsw/cloudstack-ui#1070]
Hints duplicate the text of the card fields in the image section, so they are redundant.
Discussed with PO.

![screenshot from 2018-05-04 14-22-37](https://user-images.githubusercontent.com/18456914/39616895-ca85e110-4fa7-11e8-8b84-0abd21ea6379.png)

**Comment by tamazlykar** [comment]
Test on:
tamazlykar/1070-redundant-tooltips

Regression:
image_card

**Comment by chewlite** [comment]
@tamazlykar 
Tested on: tamazlykar/1070-redundant-tooltips
