### ISSUE TITLE
 Error "Entity already exists" when updating tags

### ISSUE THREAD

**Issue by tamazlykar** [bwsw/cloudstack-ui#1093]
### Description
Error appears when updating tags

### Steps to reproduce
1. Go to VM page
2. Select VM and choose the Tags tab
3. Add a tag or use created one if exist
4. Update value of existing tag

### Actual result

When you try to update a tag an error "Entity already exists:" are shown.

### Expected result

Tag successfully updated

### Environment
<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

### Connected feature ID

vm_tag_edit
image_tag_edit
firewall_tag_edit

**Comment by tamazlykar** [comment]
**Test on:**
tamazlykar/1093-updating-tags

**Regression:**
vm_tag_edit
image_tag_edit
firewall_tag_edit

**Comment by rennervo** [comment]
Tested on /tamazlykar/1093-updating-tags/
