### ISSUE TITLE
VM is not created

### ISSUE THREAD

**Issue by tamazlykar** [bwsw/cloudstack-ui#1094]
### Steps to reproduce
1. Create VM with default configuration

### Actual result

The application freezes. An error occurred in the console.

### Expected result

VM created. No console errors.

### Environment

<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

### Connected feature ID

vm_creation

### Screenshots

![screenshot from 2018-06-04 13-59-08](https://user-images.githubusercontent.com/18456914/40903000-1a075afa-6800-11e8-860c-0705cf9a2ddc.png)

**Comment by ershovaelena** [comment]
@Nadya913 please check this problem and try to find exact steps to reproduce the problem. The idea is to delete all vms

**Comment by tamazlykar** [comment]
On the current master, it reproduces when you open a dialog for the first time and you will see Firewall rules - None. And it produces the error.
![screenshot from 2018-07-01 15-26-17](https://user-images.githubusercontent.com/18456914/42132518-a081b51e-7d43-11e8-9193-a8214c8199e6.png)
When you close and open creation dialog for the second time you will get  Firewall rules -  based on... In this case, everything will be fine.
![screenshot from 2018-07-01 15-26-34](https://user-images.githubusercontent.com/18456914/42132527-cccf1198-7d43-11e8-8ed3-65b97957e37f.png)

**Comment by tamazlykar** [comment]
But I can't understand exact steps when this occurs. Sometimes it's enough to update the page, and sometimes it does not happen.

**Comment by ershovaelena** [comment]
The bug is not reproduced
