### ISSUE TITLE
New affinity group does not connect to the virtual machine

### ISSUE THREAD

**Issue by tamazlykar** [bwsw/cloudstack-ui#1095]
### Steps to reproduce
1. Open Vm sidebar
2. Select edit affinity group
3. Choose "Create a new group"
4. Enter new name and press assign

### Actual result

When you open VM sidebar and want to attach new affinity group to VM the affinity group created but not attached.

### Expected result

New affinity group created and attached to VM.

### Environment
<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

### Connected feature ID

vm_afgroup_change

**Comment by tamazlykar** [comment]
**Test on:**
tamazlykar/1095-affinity-group

**Regression:**
vm_afgroup_change

**Comment by rennervo** [comment]
Tested on tamazlykar/1095-affinity-group
