### ISSUE TITLE
Sidebar opens automatically when creating a firewall template or shared SG

### ISSUE THREAD

**Issue by tamazlykar** [bwsw/cloudstack-ui#1096]
### Steps to reproduce
1. Go to Firewall page
2. Create a Firewall template or Shared SG

### Actual result

After creation of Firewall template or Shared SG, a sidebar opens for created element

### Expected result

Once created, the sidebar should not open. This behavior is observed in other sections.

### Environment
<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

### Connected feature ID

firewall_sg_create

**Comment by chewlite** [comment]
Tested on:
tamazlykar/1096-sidebar
