### ISSUE TITLE
Can not delete a private security group without refreshing the page

### ISSUE THREAD

**Issue by tamazlykar** [bwsw/cloudstack-ui#1098]
### Steps to reproduce
1. Create VM
2. Delete this VM (don't expunge)
3. Wait until deleted VM disappears approx. 1-2 min (you need to refresh the data pressing on VM link in the menu)
4. Go to Firewall and Private SG tab
5. Try to delete the SG belonging to removed VM

### Actual result

Unable to delete Private SG that belongs to removed VM without refreshing the page. There is no such action in menu.

### Expected result

The ability to remove Private SG, which belongs to a removed VM, without updating the page. 

### Environment
<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

**Comment by tamazlykar** [comment]
The same issue exists for Shared groups.

**Comment by tamazlykar** [comment]
**Test on:**
tamazlykar/1098-delete-private-sg

**Comment by rennervo** [comment]
Tested on tamazlykar/1098-delete-private-sg
