### ISSUE TITLE
VM list "blinks" before loading actual filtering choice

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#110]
Steps:

1. Go to VM list view
2. Apply multiple filtering: Choose all zones, all groups, choose "group by colors"
3. Go to another page (e.g. Firewall templates)
4. Come back to VM list view

Expected result: 
VMs are filtered properly as it was chosen before going to another page

Actual result:
Basic VM list (with no filtering, VMs in a row) appears for few seconds, then filtering applies.

**Comment by bwsw** [comment]
The same behaviour is for other areas (like Images)
