### ISSUE TITLE
Can not attach volume from VM sidebar

### ISSUE THREAD

**Issue by tamazlykar** [bwsw/cloudstack-ui#1100]
### Steps to reproduce
1. Open VM sidebar and go to storage tab
2. Click create a new one (Attach a volume card)
3. Create new volume
4. Go to the same VM and storage tab.

### Actual result

You can not attach a volume to a virtual machine, even if there are spare ones.

### Expected result

Be able to attach a spare volume.

### Environment
<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

### Connected feature ID

vm_disk_attach

**Comment by tamazlykar** [comment]
**Test on:**
tamazlykar/1100-attach-volume

**Regression:**
vm_disk_attach

**Comment by rennervo** [comment]
Tested on tamazlykar/1100-attach-volume

If you simultaneously attach/detach multiple disks to the VM, then the operation of the first repository is displayed indefinitely. Only after reloading the page is a successful result.

Steps:
1. Log in and go to VM
2. Make sure that you have a VM and several free storages
3. Go to sidebar VM in Storage tab
4. Simultaneously attach or detach two storages to VM

Actual result: Operation of first storage is displayed indefinitely without refresh page.
Expected result: Operations of all storages age ending without refresh page.
![joint attach-detach a few storage](https://user-images.githubusercontent.com/26665398/41635033-baf4e49c-7470-11e8-9a79-70f3c9335196.png)

**Comment by rennervo** [comment]
Tested on tamazlykar/1100-attach-volume
