### ISSUE TITLE
A duplicate snapshot appears when creating new one in VM sidebar

### ISSUE THREAD

**Issue by tamazlykar** [bwsw/cloudstack-ui#1101]
### Steps to reproduce
1. Open VM's sidebar and go to a Storage tab
2. Create one snapshot if it doesn't exist
3. After the first snapshot successfully created, create another one
4. Quickly go to another section, for example, settings and go back to VM's sidebar Storage tab
5. Click View all button and wait 

### Actual result

When creating a snapshot through the sidebar of a virtual machine, one extra snapshot appears if we move to another section and go back. For example, we have 1, create a second one, quickly go to another section and back, open a snapshot list of the virtual machine in the modal window, see 2 snapshots while creating, and when it was created we see 3 and the status is not updated.

### Expected result

Extra snapshot does not appear.

### Environment
<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

### Connected feature ID

vm_vmsnap_create
vm_vmsnap_snap_create

**Comment by chewlite** [comment]
Tested on:
tamazlykar/1101-duplicate-snapshot
