### ISSUE TITLE
The badge with the number of unlooked asynchronous operations disappears when moving to another section

### ISSUE THREAD

**Issue by tamazlykar** [bwsw/cloudstack-ui#1102]
### Steps to reproduce
1. Start or Stop VM
2. See badge with notifications count on the bell icon 
3. Go to another section
4. See there is no notification count badge

### Actual result

The badge with the number of unlooked asynchronous operations disappears when moving to another section

### Expected result

Tha badge should not disappear after going to another section

### Environment
<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

### Connected feature ID

notification_bell

**Comment by tamazlykar** [comment]
**Test on:**
tamazlykar/1102-badge

**Regression:**
notification_bell

**Comment by chewlite** [comment]
The badge with the number of unlooked asynchronous operations doesnt disappears right after open bell. And if open the bell and go to another section right after that the badge doesnt disappears too

**Comment by tamazlykar** [comment]
If we will disappear the number of unlooked asynchronous operations after right after opening the bell it will fix the second issue that you describe.
But here I found another bug that if an operation is still running the number is reset after notification window close. The past behavior saved the number of current operations after the window was closed.

**Comment by tamazlykar** [comment]
Fix both issues.

**Comment by rennervo** [comment]
Tested on tamazlykar/1102-badge
