### ISSUE TITLE
Error when searching in the firewall section

### ISSUE THREAD

**Issue by tamazlykar** [bwsw/cloudstack-ui#1103]
### Steps to reproduce
1. Go to the firewall section
2. Search something

### Actual result

When you searching something in the firewall section error occurs in the console and empty cards appear

### Expected result

Results are shown without errors and empty cards

### Environment
<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

### Connected feature ID

firewall_list_search

### Screenshots

![screenshot from 2018-06-09 13-33-44](https://user-images.githubusercontent.com/18456914/41188608-591f9b60-6bea-11e8-828a-ac8a4a820e71.png)

**Comment by tamazlykar** [comment]
**Test on:**
tamazlykar/1103-firewall-search-error

**Regression:**
firewall_list_search

**Comment by chewlite** [comment]
Tested on:
tamazlykar/1103-firewall-search-error
