### ISSUE TITLE
Filters data in the firewall section are cached

### ISSUE THREAD

**Issue by tamazlykar** [bwsw/cloudstack-ui#1110]
### Steps to reproduce
1. Go to Firewall section
2. Set some filters, for example, choose private SG, select some account and use the search
3. Go to another section like Images to change URL
4. Close and reopen browser tab or refresh the page
5. Go back to Firewall section

### Actual result

Filters data in the firewall section are cached, so when you reopen or refresh application it keeps previous filters. This behavior exists only in the Firewall section.

### Expected result

Filters data are not cached.

### Environment
<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

### Connected feature ID

firewall_list_filter
firewall_list_search

**Comment by tamazlykar** [comment]
**Test on:**
tamazlykar/1110-cached-firewall-filter

**Regression:**
firewall_list_filter
firewall_list_search

**Comment by chewlite** [comment]
Tested on:
tamazlykar/1110-cached-firewall-filter
