### ISSUE TITLE
Error "You are not logged in" appears but user is not logged out

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#1112]
### Steps to reproduce
1. Login to system
2. Do not make any actions on the page for some time (e.g. go to another browser tab)
3. Come back to page

### Actual result

Error "you are not logged in" appears in VM list, user is not logged out

### Expected result

Error appears on the Login screen, user is logged out

### Environment
<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

### Connected feature ID

- login_default
- login_url
- login_domain
- logout

### Screenshots

![1](https://user-images.githubusercontent.com/26703076/41456968-62ca1ac0-70ac-11e8-8d74-82cc12c524dc.png)

**Comment by tamazlykar** [comment]
Unnable to reproduce. Please provide additional information.

**Comment by ershovaelena** [comment]
The bug is not reproduced
