### ISSUE TITLE
The Previous value of Account limit is displayed after closing the sidebar

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#1113]
### Steps to reproduce
1. Go to Accounts and open a sidebar of any account
2. Change one of the limits (E.g. CPU limits) and save changes
3. The new value of the limit is displayed
4. Close the sidebar
5. Reopen the sidebar of the same account

### Actual result

Previous value of CPU limits is displayed. New value appears after reloading the page

### Expected result

New value of CPU limits is displayed. No need to reload the page

### Environment
<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

### Connected feature ID

- account_limits_display
- account_limits_change

**Comment by tamazlykar** [comment]
Will be done in #1114

**Comment by tamazlykar** [comment]
**Test on:**
tamazlykar/1114-account-limits

**Regression:**
account_limits_display
account_limits_change

**Comment by rennervo** [comment]
Tested on /tamazlykar/1114-account-limits/

**Comment by tamazlykar** [comment]
Fixed in #1119
