### ISSUE TITLE
The current user's account card is smaller than the rest

### ISSUE THREAD

**Issue by tamazlykar** [bwsw/cloudstack-ui#1115]
### Steps to reproduce
1. Go to Accounts section

### Actual result

The current user's account card is smaller than the rest

### Expected result

All cards have the same size

### Environment
<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

### Screenshots

![screenshot from 2018-06-15 15-11-39](https://user-images.githubusercontent.com/18456914/41457868-38a3470a-70af-11e8-9c52-5746b8597bcd.png)

**Comment by rennervo** [comment]
Tested on tamazlykar/1115-account-card
