### ISSUE TITLE
Error "Cannot read property 'account' of undefined" appears when disabling account

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#1116]
### Steps to reproduce
1. Log in to the system as admin
2. Go to Accounts section
3. Click "Disable" for any account 

### Actual result

Error "Cannot read property 'account' of undefined" appears. Status is not changed to "disabled" until you reload the page. 

### Expected result

Error does not appear, status of the Account is changed to "disabled".

### Environment
<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

### Connected feature ID

- account_card
- account_actionbox
- account_disable
- account_enable

**Comment by tamazlykar** [comment]
**Test on:**
tamazlykar/1116-account-disable

**Regression:**
account_card
account_actionbox
account_disable
account_enable

**Comment by rennervo** [comment]
Tested on tamazlykar/1116-account-disable
