### ISSUE TITLE
System works incorrectly when delete the last user in account

### ISSUE THREAD

**Issue by chewlite** [bwsw/cloudstack-ui#1127]
**Steps to reproduce**
1. Delete the last user in account
2. Go to another section, back and change section again

**Actual result**
Content in all sections duplicated, overlapped by each other and unavailable for interaction

**Expected result**
Content in each section is appropriate and available for interaction

**Connected feature ID**
account_user_delete

**Screenshots**

Accounts
![accounts](https://user-images.githubusercontent.com/32011943/41755004-4ff00394-75ff-11e8-8857-32ecfa4866dd.png)

Another sections, for example:
![activitylog](https://user-images.githubusercontent.com/32011943/41755002-4fa78358-75ff-11e8-9385-399e0885731b.png)

![vms](https://user-images.githubusercontent.com/32011943/41755003-4fcac3d6-75ff-11e8-83ef-cb33153a6184.png)

**Comment by tamazlykar** [comment]
**Test on:**
tamazlykar/1127-last-user

**Regression:**
account_user_delete

**Comment by chewlite** [comment]
Tested on:
tamazlykar/1127-last-user
