### ISSUE TITLE
Private SGs tab is displayed incorrectly when change box/list view in Firewall 

### ISSUE THREAD

**Issue by chewlite** [bwsw/cloudstack-ui#1133]
**Steps to reproduce**
1. Log in and go to Firewall
2. Change box view to "list"
3. Go to Private SGs tab

**Actual result**
Shared SGs tab is displayed, empty object on top of the list. 
Other sections are displayed incorrectly: throbbers, content is duplicated
If change list view to "box" then Private SGs tab with Private SGs cards and list of Shared SGs are displayed

**Expected result**
Content in each tab is appropriate to tab's name. Other sections are displayed correctly

**Connected feature ID**
firewall_list_switch
box_list_view

**Screenshots**
![2018-06-27 09-17-59](https://user-images.githubusercontent.com/32011943/41950091-a893966c-79ee-11e8-9c80-014d6a6599e1.png)

**Comment by tamazlykar** [comment]
Test on:
tamazlykar/1133-list-firewall-view

Regression:
firewall_list_switch
box_list_view

**Comment by chewlite** [comment]
Tested on:
tamazlykar/1133-list-firewall-view
