### ISSUE TITLE
There is no "would you like to create a VM\Volume?" message

### ISSUE THREAD

**Issue by tamazlykar** [bwsw/cloudstack-ui#1136]
### Steps to reproduce
1. Create a new User account.
2. Log in with this account
3. Go to VM / Volume section

### Actual result

There is no modal window that asks you about creating your first VM / Volume.

### Expected result

There is a modal window that asks you about creating your first VM / Volume.

### Environment
<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] Opera version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

### Connected feature ID

- vm_propose_create
- storage_propose_create

**Comment by HeyRoach** [comment]
For QA:
Also find a small bug: volumes doesn't deleting (console error appears)

**Comment by HeyRoach** [comment]
@ershovaelena Changes requested after review

**Comment by tamazlykar** [comment]
Regression:
vm_propose_create
storage_propose_create

**Comment by chewlite** [comment]
@tamazlykar 

**1. Different highlights of options in the dialog: _No/No, don't ask_ and _Yes_**
(for VM and Storage)
![2018-08-20 13-32-26](https://user-images.githubusercontent.com/32011943/44332756-15597000-a497-11e8-89c5-77f55f500598.png)

**2. The dialog appear even if there are entities**
- after login (dialog about VM)
- after refresh the VM page (dialog about VM)
- after refresh the Storage page (dialog about Storage)

**3. Select "No, don't ask" - the dialog still appear**
(for VM and Storage)

Steps:
1. For VM/Storage select "No, don't ask"
2. Refresh VM/Storage section

Actual: the dialog appear
Expected: the dialog doesn't appear 

**4. "No, don't ask" saves for Storage after logout**

Steps:
1. Select "No, don't ask" for Storage
2. Logout and login
3. Go to Storage

Actual: the list is empty but the dialog doesn't appear 
Expected: the list is empty, the dialog appear

**5. Dialog doesn't appear for Storage after delete the last disk**

Steps:
1. Make sure that the lists (VM and Storage) are empty
2. Create a VM 
3. Make sure that in Storage appear one root disk
4. Delete the newly created VM
5. Go to Storage

Actual: the dialog doesn't appear 
Expected: the dialog appear

**Comment by tamazlykar** [comment]
4. Not a bug. This is the expected behavior. 
All other - fixed.
Please, retest all.

**Comment by chewlite** [comment]
@tamazlykar 

**1. After logout the dialog (about VM and Storage) appears one or few times**
I was able to repeat this only for users "develop" and "user"
After every press on some option in the dialog the background behind becomes lighter

![2018-08-22 09-42-24](https://user-images.githubusercontent.com/32011943/44441147-60899500-a5f5-11e8-8e5a-e70975b5653d.png)

**2. Select "No, don't ask" - the dialog still appear**
To reproduce this bug follow the steps slowly

Steps:
1. Create a new user and login under this user
2. Press "No, don't ask" in VM/Storage
3. Go to another section or refresh the page
4. Back to VM/Storage

Actual: the dialog appear
Expected: the dialog doesn't appear

**Comment by chewlite** [comment]
@tamazlykar 

Tested on 1192
