### ISSUE TITLE
Add support -1 (Any) value for ICMP IPv6 Type and Code 

### ISSUE THREAD

**Issue by tamazlykar** [bwsw/cloudstack-ui#1137]
CloudStack v4.11 supports now -1 value for IPv6 ICMP Type and Code.
We need to implement support for this functionality.

Connected feature ID: 
- firewall_rules_view
- firewall_rules_edit

**Comment by HeyRoach** [comment]
pull request number

firewall_rules_view
firewall_rules_edit
