### ISSUE TITLE
System tags are not displayed after a VM creation

### ISSUE THREAD

**Issue by tamazlykar** [bwsw/cloudstack-ui#1139]
### Steps to reproduce
1. Create VM (with password enabled template and run VM)
2. Make sure that you save password (because is should be saved in system tags)
3. Open Tags tab of the new VM's sidebar

### Actual result

System tags are not displayed

### Expected result

System tags are displayed

### Environment
<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] Opera version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

### Connected feature ID

vm_tag_display
vm_tag_showsystem

**Comment by tamazlykar** [comment]
The problem arises because after copying the tags the model in ngrx / store is not updated.

**Comment by tamazlykar** [comment]
**Test on:**
tamazlykar:1139-vm-tags

**Regression:**
vm_creation
vm_tag_display
vm_tag_showsystem

**Comment by rennervo** [comment]
**After creating a VM without updating the page, only the "Password" tag is displayed**

Steps: 
1) Create VM with password
2) Save password after creating VM
3) Go to sidebar this VM to "Tags" tab

Actual result: Only tag "Password" is displayed
Expected result: All system tags and all non-system tags of the template are displayed

**Comment by tamazlykar** [comment]
Regression: 
vm_tag_display
vm_tag_create
vm_tag_edit
vm_tag_delete
vm_tag_showsystem
vm_tag_search

**Comment by rennervo** [comment]
**VM tags aren't displayed when saving password after VM create**

Steps:
1. Go to VM and create new VM with password
2. Save password after VM create
3. Go to this VM sidebar to "Tags" tab

Actual result: Only tag "password" is displayed
Expected result: All tags are displayed

**Comment by chewlite** [comment]
Tested on 1173
