### ISSUE TITLE
Images area improvements

### ISSUE THREAD

**Issue by bwsw** [bwsw/cloudstack-ui#114]
1. Move State bullet to the left of ISO/template card
2. Implement a bar "Zones" in ISO/template detailed sidebar:
- This bar should be the list of template's Zones
- Put completion status near zone name ("% ready" if it's not ready yet, or "ready")
- Put "reload" button (choose an icon for it) on the right side of Name and Status. Pressing this button updates the status (completion %)
3. Implement a bar "Download URL" in ISO/template detailed sidebar:
Put there the URL link that was used to create this template. Place download URL in tags DOWNLOAD_URL 

This issue is connected with #113

**Comment by bwsw** [comment]
Connected with #113

**Comment by andrewbents** [comment]
There is a "status" field in ISO and templates, but it is rarely present in the API response. If the response has this field, it is shown only to the user owning the ISO or the template
