### ISSUE TITLE
Modal window "Do you want to save a password for all VMs?" appears even if "No" is set in Settings

### ISSUE THREAD

**Issue by tamazlykar** [bwsw/cloudstack-ui#1140]
### Steps to reproduce
1. Set "Save VM passwords by default" = false in settings
2. Create new VM (with password) and press Save password

### Actual result

A modal window appears and it appears every time when "Save VM passwords by default" - disabled

### Expected result

A modal window should appear only once until the system doesn't know user preference (For example new user). If  "Save VM passwords by default" was enabled and you disable it then modal windows "Do you want to save a password for all VMs?" should not appear anymore.
For the new user, there is no difference in the "Save VM passwords by default" checkbox between the state is not set and turned off.

### Environment
<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] Opera version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

### Connected feature ID

settings_password_saveall
vm_password_save

**Comment by ershovaelena** [comment]
TBD in #1014

**Comment by ershovaelena** [comment]
Please, test this issue on master

**Comment by rennervo** [comment]
Tested on Master

1) This error wasn't fixed. 

Actual result: A modal window appears every time when parameter "Save VM password by default" set as disabled. It does not matter whether the user is new or old.
Expected result: Modal window appears only one time when a new user creates first VM and parameter "Save VM password by default" set as disabled.

2) The parameter "Save VM password by default" not set to "Enabled" state when confirming the modal window "Save all passwords" after creating VM.

Steps:
1. Set "Save VM passwords by default" = false in settings
2. Create new VM (with password) and press Save password
3. Confirm the modal window

Actual result: Parameter "Save VM password by default" set as disabled in settings
Expected result: Parameter "Save VM password by default" set as enabled in settings

**Comment by rennervo** [comment]
Tested on Master
