### ISSUE TITLE
The password is not displayed the first time a deployed virtual machine is started

### ISSUE THREAD

**Issue by tamazlykar** [bwsw/cloudstack-ui#1141]
### Steps to reproduce
1. Create VM (with a password but do not start it)
2. Start created VM

### Actual result

Create VM with a password which not started during deployment. Deployment window will show that there is no information about the password but Save password button work. When you start this VM for the first time there is no information about password provided, but this data exists in response from a server.

### Expected result

If there is no information about a password in deployment window when deployed VM does not start, Password information not shown. After the first start of the deployed VM modal window with password appears, for example as when resetting the password.

### Environment
<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] Opera version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

### Connected feature ID

vm_deploy
vm_start

**Comment by tamazlykar** [comment]
New dialog view added see PR #1199 

Regression:
vm_deploy
vm_start
vm_password_reset

**Comment by chewlite** [comment]
Tested on 1199
