### ISSUE TITLE
VM status is not updated after resetting the password

### ISSUE THREAD

**Issue by tamazlykar** [bwsw/cloudstack-ui#1142]
### Steps to reproduce
1. Disable "Save VM passwords by default" in settings
2. Reset password of VM
3. Press Save password
4. Should appears dialog which asks about autosave passwords. Press any button.
4. Exit from dialog

### Actual result

VM has a stopped state

### Expected result

VM has a running state

### Environment
<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] Opera version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

### Connected feature ID

settings_password_saveall
vm_password_reset
vm_password_save
vm_card

**Comment by tamazlykar** [comment]
PR #1150 fixes this issue

**Comment by ershovaelena** [comment]
Please, test this issue on master

**Comment by rennervo** [comment]
Tested on Master
