### ISSUE TITLE
Modal window "Do you want to save a password for all VMs?" does not work

### ISSUE THREAD

**Issue by tamazlykar** [bwsw/cloudstack-ui#1143]
### Steps to reproduce
1. Disable "Save VM passwords by default" in settings
2. Reset password of VM
3. Save Password
4. In the Modal "Do you want to save a password for all VMs?" press Yes
5. Go to settings and see "Save VM passwords by default"

### Actual result

Checkbox disabled

### Expected result

Checkbox enabled

### Environment
<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] Opera version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

### Connected feature ID

settings_password_saveall
vm_password_saveall
vm_password_reset

**Comment by tamazlykar** [comment]
This behavior should work only if a user never saves password before so the user does not have "csui.user.save-password-for-all-vms".

**Comment by ershovaelena** [comment]
TBD in #1014

**Comment by ershovaelena** [comment]
Please, test this issue on master

**Comment by rennervo** [comment]
Tested on Master
