### ISSUE TITLE
Error appears when creating VM with default custom service offering

### ISSUE THREAD

**Issue by tamazlykar** [bwsw/cloudstack-ui#1144]
### Steps to reproduce
1. Make sure that you don't have any fixed service offering.
2. Create VM with default parameters.

### Actual result

The application allows creating a VM with default params. If there is no fixed service offering the application will select by default first custom offering. But there will be no parameters set in the custom service offering. And If you press create button without changing anything, you will get an error.

### Expected result

A virtual machine is created without error with default parameters.

### Environment
<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] Opera version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

### Connected feature ID

vm_creation_so
vm_creation_so_custom

**Comment by tamazlykar** [comment]
Need to fill in a custom service offering with default values, the same ones that fill the window for setting up a custom service offering.
And also make sure that when you open the form creation values are set in the description.
Discussed with PO.
![screenshot from 2018-07-01 13-22-33](https://user-images.githubusercontent.com/18456914/42131793-aab1c060-7d34-11e8-9e3d-9fa0260b5b79.png)

**Comment by tamazlykar** [comment]
Add a new parameter to the config that sets the default values for all custom service offering.
These values should have the lowest priority in comparison with the values in Default Service Offering (if specified) and with the tags.

**Comment by tamazlykar** [comment]
Decided not to make parameter configurable. So no validation and config-guide update needed.

**Comment by tamazlykar** [comment]
Implemented during #1230

**Comment by rennervo** [comment]
Tested on 1267
