### ISSUE TITLE
Can not click select for an already selected value

### ISSUE THREAD

**Issue by tamazlykar** [bwsw/cloudstack-ui#1145]
### Steps to reproduce
1. Open VM creation window
2. Click on the Select button for Service offering
or
1. Open Volume creation
2. Click on the Select button for Disk Offering
3. Select any Value
3. Reopen disk offering selection
or
1. Open VM creation window
2. Choose ISO for Installation Source
3. Click on the Select button for Installation Source

### Actual result

The Select button is disabled in modals for already selected value.

### Expected result

The Select button should be enabled for already selected value.

### Environment
<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] Opera version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

### Connected feature ID

vm_creation_so
vm_creation_so_custom
vm_creation_diskoffering
storage_disk_create

### Screenshots

![screenshot from 2018-07-02 09-41-17](https://user-images.githubusercontent.com/18456914/42142873-2c21ef88-7ddc-11e8-922d-5949323eb2a2.png)
![screenshot from 2018-07-02 09-41-42](https://user-images.githubusercontent.com/18456914/42142879-2f006aa4-7ddc-11e8-90d4-ca8921b74653.png)
![screenshot from 2018-07-02 09-43-36](https://user-images.githubusercontent.com/18456914/42142916-6c559ac8-7ddc-11e8-9d8d-b38c8dc194aa.png)

**Comment by tamazlykar** [comment]
**Test on:**
tamazlykar/1145-disabled-select

**Regression:**
vm_creation_so
vm_creation_so_custom
vm_creation_diskoffering
storage_disk_create

**Comment by rennervo** [comment]
**Button "Select" is available when no item is selected.**

Steps:
1. Go to Storage
2. Click on "Create" button
3. Click on "Select" disk offering button

Actual result: "Select" button is available when no item is selected
Expected result: "Select" button isn't available when no item selected
![select disk offering without items](https://user-images.githubusercontent.com/26665398/42856066-b038524c-8a6d-11e8-8cda-0673b6d111d2.png)

**Additional: Create, please, more items in a window for service offering select. Fixed and Custom.**

**Comment by ershovaelena** [comment]
To be tested on the simulator locally

**Comment by tamazlykar** [comment]
Implemented during #1176 PR

**Comment by chewlite** [comment]
Tested locally and on /1176
