### ISSUE TITLE
Error during the deployment of the template

### ISSUE THREAD

**Issue by tamazlykar** [bwsw/cloudstack-ui#1149]
### Description
Error during the deployment of the next templates:

Name                            coreos-1745.7.0-5gb
Size                              4.43 GB
Direct Download          No
extractable                  Yes
Password Enabled      No
Dynamically Scalable  No
Public                          Yes
Featured                     Yes
OS Type                      CoreOS
Cross Zones               Yes

### Steps to reproduce
Create VM with  "coreos-1745.7.0-5gb" template.

### Actual result

Error during deployment

### Expected result

No errors during deployment

### Environment
<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] Opera version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

### Connected feature ID

vm_deploy

### Screenshots

![unnamed](https://user-images.githubusercontent.com/18456914/42547304-95b9b2ee-84eb-11e8-9374-66f4b7a0a7b4.png)

**Comment by tamazlykar** [comment]
The problem occurs because the application passes the calculated rootize parameter to the virtual machine creation request.

Native UI request
![screenshot from 2018-07-15 18-11-39](https://user-images.githubusercontent.com/18456914/42733592-bbc36780-885d-11e8-9061-e9a36bbe0c26.png)

CloudStack UI request
![screenshot from 2018-07-15 18-08-46](https://user-images.githubusercontent.com/18456914/42733597-d4ffc234-885d-11e8-95ea-aeb68dcaa41a.png)

**Comment by tamazlykar** [comment]
**Test on**
tamazlykar/1149-root-disk-size

**Regression:**
vm_deploy

**Comment by rennervo** [comment]
Tested on tamazlykar/1149-root-disk-size
