### ISSUE TITLE
Disable select button for Installation source and SO in VM creation if no elements in the list

### ISSUE THREAD

**Issue by tamazlykar** [bwsw/cloudstack-ui#1155]
### Steps to reproduce
1. Make sure that you do not have any ISOs (you can use a simulator)
2. Open VM creation dialog
3. Open the Installation source selection dialog
4. Go to ISO tab
5. Press select button

### Actual result

Select button exists and after it was pressed an error appears at dialog window but Installation source shows previous selection. I think the same problem will be if there are no templates, but there will be ISO.

### Expected result

I think we should hide button (Service offering dialog hide the Select button if there is no SO in tab) or disable, this needs to discuss with PO. If we do this then an error will not be shown.

### Environment
<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] Opera version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

### Connected feature ID

vm_creation_installsource

### Screenshots

Initial form state
![screenshot from 2018-07-14 16-35-44](https://user-images.githubusercontent.com/18456914/42723479-b18bb8b0-8788-11e8-845a-490dfe977bc8.png)
Instalation source dialog with no ISOs and the enabled selection button 
![screenshot from 2018-07-14 16-35-55](https://user-images.githubusercontent.com/18456914/42723482-bbd8d0c8-8788-11e8-98d8-85db1dfdc4a8.png)
An error that occurs
![screenshot from 2018-07-14 16-36-05](https://user-images.githubusercontent.com/18456914/42723505-12e9d63c-8789-11e8-915d-822b6b3eaa22.png)
Other behavior on a similar situation in the service offering dialog
![screenshot from 2018-07-14 16-36-14](https://user-images.githubusercontent.com/18456914/42723519-45027fe8-8789-11e8-842b-0d2a18004c69.png)

**Comment by tamazlykar** [comment]
@zolotyx, please see the code. Do you see any solution to this problem without completely rewriting the components?

**Comment by ershovaelena** [comment]
@tamazlykar discussed with PO: Select button should be disabled if no elements in the list
- disable the button (Case of ISO Installation source)
- show disabled button (Case of Service offering)

**Comment by ershovaelena** [comment]
Includes #1145

**Comment by tamazlykar** [comment]
Regression:
vm_creation_installsource

**Comment by chewlite** [comment]
**An error "No templates available" still occurs**

Tested on simulator 

**Steps:**
1. Open VM creation dialog
2. Open the Installation source selection dialog
3. Go to ISO tab (tab should be empty)
4. Press Cancel button

**Actual result:** 
![42723505-12e9d63c-8789-11e8-915d-822b6b3eaa22](https://user-images.githubusercontent.com/32011943/44129670-aac17552-a073-11e8-9d19-870955f5f2d1.png)

**Expected result:**
No error

**Comment by tamazlykar** [comment]
Please check that templates displays as before and as expected and filter works right.

**Comment by chewlite** [comment]
**(!) testing is not complete**

**vm_creation_installsource_filter
vm_creation_installsource_search**

Steps:
1. Set some filters, fill the search field with a value
2. Cancel/Select
3. Open Installation source dialog

Actual: filters and search are saved
Expected: filters and search are set by default

**vm_creation_installsource_search**

Steps:
1. Fill the search field with a value
2. Select (fully or partially) value in the search field (with the cursor/the keyboard)

Actual:
Dialog closes and for installation source saves "OS template: undefined"
![2018-08-16 16-17-23](https://user-images.githubusercontent.com/32011943/44202420-1f692f00-a176-11e8-94b6-5dca3bb67723.png)
When open Installation source dialog again:
![2018-08-16 16-16-20](https://user-images.githubusercontent.com/32011943/44202449-314ad200-a176-11e8-9bf7-e4bd936182c5.png)
Expected: 
Dialog stays open, value in the search field selected successfully

**Comment by chewlite** [comment]
@tamazlykar 

Tested on 1176
