### ISSUE TITLE
Update Angular with dependencies

### ISSUE THREAD

**Issue by tamazlykar** [bwsw/cloudstack-ui#1160]

**Comment by tamazlykar** [comment]
Test the second issue by Nadya913 in #1014  ([my comment](https://github.com/bwsw/cloudstack-ui/issues/1014#issuecomment-410196402))

**Comment by tamazlykar** [comment]
To test

**Comment by chewlite** [comment]
@tamazlykar

**Comment by chewlite** [comment]
**1. vm_disk_snap_schedule, storage_snap_schedule**
The window for setting the snapshot schedule expands and shrinks when you change the tabs "Hour", "Daily", "Weekly", "Monthly"

**2. notification_bell**
"Clear completed" button is shifted below

**Comment by chewlite** [comment]
**1. 
vm_disk_snap_schedule 
storage_snap_schedule** 
`All browsers`

The window for setting the snapshot schedule expands and shrinks when you change the tabs "Hour", "Daily", "Weekly", "Monthly"

**2. notification_bell**
`All browsers`

- "Clear completed" button is shifted below 
- When hover on "Clear completed" button there is no highlighting on it

_Branch:_
![2018-09-21 15-55-44](https://user-images.githubusercontent.com/32011943/45871122-d16bca80-bdb6-11e8-8823-9f75881ec4d9.png)

_Master:_
![2018-09-21 15-50-55](https://user-images.githubusercontent.com/32011943/45870873-2f4be280-bdb6-11e8-989c-c22b8233fef6.png)

**3. 
vm_firewall_rules_view
vm_firewall_rules_edit
firewall_rules_view
firewall_rules_edit**
`All browsers`
After every rule there is a line
Expected: there are no lines after every rule, layout as on master

**4. vm_creation**
`All browsers`
Extra space in VM creation window after SO and Firewall rules fields

_Branch:_
![2018-09-21 16-01-48](https://user-images.githubusercontent.com/32011943/45871490-d67d4980-bdb7-11e8-9f65-b5dd3e0d1c5a.png)

_Master:_
![2018-09-21 16-17-44](https://user-images.githubusercontent.com/32011943/45872416-2fe67800-bdba-11e8-869d-2aba3429a057.png)


**5. 
vm_creation_so
vm_SO_change
vm_disk_snap_schedule
storage_snap_schedule**
`All browsers except IE`
Radio button is aligned too close to right side of the window

_Branch:_
![2018-09-21 16-08-58](https://user-images.githubusercontent.com/32011943/45871992-1133b180-bdb9-11e8-9e02-94088c121556.png)

_Master:_
![2018-09-21 16-12-36](https://user-images.githubusercontent.com/32011943/45872054-3aecd880-bdb9-11e8-915f-bd0c1b2534d9.png)

**6. 
vm_creation_so
vm_SO_change
vm_disk_snap_schedule
storage_snap_schedule
vm_vmsnap_viewall
activitylog_events_display**
Text is shifted up
`IE browser`
![2018-09-21 16-22-32](https://user-images.githubusercontent.com/32011943/45872611-a2575800-bdba-11e8-8778-a7a3a189cc39.png)
![2018-09-21 16-23-28](https://user-images.githubusercontent.com/32011943/45872636-b1d6a100-bdba-11e8-9ea8-363689a9b465.png)
![2018-09-21 16-23-50](https://user-images.githubusercontent.com/32011943/45872673-c9ae2500-bdba-11e8-9e4e-e9e3a3c8cb48.png)
![2018-09-21 16-24-07](https://user-images.githubusercontent.com/32011943/45872674-cc107f00-bdba-11e8-803c-9987f835bebc.png)

**Comment by tamazlykar** [comment]
3. Provide more detailed steps to reproduce. I don't see any lines.

**Comment by rennervo** [comment]
Tested on 1294
