### ISSUE TITLE
A badly readable table in Disk Offering chooser dialog

### ISSUE THREAD

**Issue by tamazlykar** [bwsw/cloudstack-ui#1165]
### Steps to reproduce
1. Configure app in the config.json with
```
"diskOfferingParameters": [
    "displaytext",
    "disksize",
    "created",
    "storagetype",
    "provisioningtype",
    "iscustomized",
    "miniops",
    "maxiops"
  ],
```
2. Open a disk offering dialog in a volume creation dialog.

### Actual result

A badly readable table

### Expected result

To discuss

### Environment
<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] Opera version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

### Connected feature ID

vm_creation_diskoffering
storage_disk_create

### Screenshots

![screenshot from 2018-07-19 15-07-23](https://user-images.githubusercontent.com/18456914/42929967-d854ccda-8b65-11e8-9154-4f6d5575a2c6.png)

**Comment by ershovaelena** [comment]
Connected to #942

**Comment by tamazlykar** [comment]
We decided to replace the table with a set of expansion panels. In the header of which the name, description with the tooltip, and the size of the disk. If the disk offering is custom, then the size of the disk is indicated by "custom".
The choice of disk offering is made by pressing the radio button, but the panel does not open.

![screenshot from 2018-09-25 17-53-37](https://user-images.githubusercontent.com/18456914/46010189-ff6d4980-c0eb-11e8-8659-b58d96f900c0.png)
![screenshot from 2018-09-25 17-53-46](https://user-images.githubusercontent.com/18456914/46010211-0c8a3880-c0ec-11e8-81fd-ac0c685aa02f.png)
Approved by PO

**Comment by tamazlykar** [comment]
We desided to remove Disk Offering Parameters from config.
"Disk Offering" card in the disk sidebar was related on this property. Now we will show all properties.
There was a **bug**, that "Storage type" field don't have a translation for a "local" value. 

![screenshot from 2018-09-25 17-55-17](https://user-images.githubusercontent.com/18456914/46010303-5ecb5980-c0ec-11e8-8c09-1c563ff0e75e.png)

**Comment by tamazlykar** [comment]
To test:
vm_creation_diskoffering
storage_disk_resize
storage_disk_create
storage_diskoffering_display

**Comment by rennervo** [comment]
**Bad readable parameters of the disk offering when opening the panel**
**Description:**
The location of the headers to the values of the parameters is not obvious. (For example, it's not quite obvious that "Read" and "Write" refer specifically to "IOPS"). You need to change the alignment of headers.

**Steps:**
1) Go to Storage
2) Click to 'Create" button
3) Click to "Select" in Disk offering string
4) Open parameters panel of any disk offering

**Actual result:** Headers aligned to the left
**Expected result:** Headers aligned to the right

**Feature ID:** storage_diskoffering_display, vm_creation_diskoffering
**Screenshot:**
![layout disk offering parameters](https://user-images.githubusercontent.com/26665398/46057890-3f7f0b80-c182-11e8-900b-dbd29414d0d9.png)

**Comment by tamazlykar** [comment]
This is not a bug. The PO wanted just such a layout.

**Comment by rennervo** [comment]
Ok. Tested on 1300
