### ISSUE TITLE
ConfigureSidebar feature does not work as expected

### ISSUE THREAD

**Issue by tamazlykar** [bwsw/cloudstack-ui#1166]
### Expected behavior

The configureSidebar settings should configure a sidebar order.  If we remove an element from the array, then this menu section must be disabled in the application menu setup mode.

### Actual behavior

Menu items don't follow the order in the configureSidebar setting.
If we remove an item from the configureSidebar Array them this section disappears completely even from menu setup mode, but you can go there by URL.

### Environment
<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] Opera version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

### Connected feature ID

sidebar_reorder
config_configure_sidebar

**Comment by tamazlykar** [comment]
Addition restriction:
If a user turns off the visibility of VM section and makes logout => login then he will be redirected to VM section by default. So we decided don't allow turn off the visibility of the VM section.

**Comment by rennervo** [comment]
Tested on a simulator of branch "1166-configure-sidenav"
