### ISSUE TITLE
Update Config Guide

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#1167]
Update [Config guide](https://github.com/bwsw/cloudstack-ui/blob/master/config-guide.md)
1. Change the structure of the document (use the same order as in config file)
2. Rename configurations in user and default config (names must be validated with PM and PO) **+ in code**
3. Update configurations descriptions. Descriptions must be understandable, up-to-date
4. Add small examples to configurations
5. Put a link to "Config example" document
6. Change Feature List documentation

**Comment by ershovaelena** [comment]
@tamazlykar do not forget to change Feature List ("configurations" tab) according to the changes in this issue

**Comment by ershovaelena** [comment]
@tamazlykar Documentation changes include [these changes](https://github.com/bwsw/cloudstack-ui/issues/1231#issuecomment-420853153)

**Comment by tamazlykar** [comment]
Renamed:
templateGroups => imageGroups
allowReorderingSidebar => allowReorderingSidenav
serviceOfferingClasses => computeOfferingClasses
offeringAvailability => serviceOfferingAvailability
defaultThemeName => defaultTheme

To test all renamed properties.
