### ISSUE TITLE
When local data volume is created, VM ID should be provided

### ISSUE THREAD

**Issue by bwsw** [bwsw/cloudstack-ui#1169]
There are 2 storage types (local, shared). The type of data disk is local or shared as well (depending on the disk offering that user chooses during volume creation). When local data volume is created, it should be attached to VM. 

**Acceptance criteria:**
1. Volume creation
 - Add a "select VM" drop-down in volume creation
 - If a chosen disk offering is local - choosing VM has to be required, a mandatory field
 - If a chosen disk offering is shared - choosing VM is not necessary, an optional field

2. Storage section
- Remove "State:[Ready]/[Allocated]" from volume card
- Add to Storage sidebar (section "General information")
  - "State:[Ready]/[Allocated]"
  - "VM name:[VM name]/[Not attached]"
- Add "VM name:[VM name]/[Not attached]" to volume card

**Connected feature ID:** storage_disk_create, storage_card, storage_geninfo_display

**Comment by ershovaelena** [comment]
@bwsw For now, we do not show VMs, to which volumes are attached, in Storage section. 
Should we add a separate section to Storage details sidebar (volume tab) "VM name" where VM will be displayed? If the volume is not attached to any VM we can hide this section.

**Comment by bwsw** [comment]
@ershovaelena @HeyRoach @tamazlykar 
Ticket declined.
