### ISSUE TITLE
When creating, deleting, updating an image tag, a spinner appears in the main application area

### ISSUE THREAD

**Issue by tamazlykar** [bwsw/cloudstack-ui#1172]
### Steps to reproduce
1. Go to the Images page
2. Add/update/delete tag of any template or iso

### Actual result

When creating, deleting, updating an image tag, a spinner appears in the main application area. See screenshot.

### Expected result

The spinner should not be arrears during this operation

### Environment
<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] Opera version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

### Connected feature ID

image_tag_create
image_tag_edit
image_tag_delete

### Screenshots

![screenshot from 2018-07-26 09-50-51](https://user-images.githubusercontent.com/18456914/43238900-58c0be7a-90ba-11e8-8cfd-4f9a0bccf374.jpg)

**Comment by HeyRoach** [comment]
Test on:
HeyRoach/1172-images-bug

Test to:
image_tag_create
image_tag_edit
image_tag_delete

**Comment by rennervo** [comment]
**An error dialog appears when editing a newly created tag**
Steps:
1. Go to Images on any tabs (Templates or ISO)
2. Select any image from the list and go its sidebar to the "Tags" tab
3. Create new tag
4. Go to editing new tag
5. Change parameters and click to "Edit"

Actual result: An error dialog appears when editing a newly created tag (See to screenshot)
Expected result: Tag successfully updated, the error there isn't.
![error when editing image tags](https://user-images.githubusercontent.com/26665398/43705193-13d71d92-998c-11e8-9efe-a4ee4c297a65.png)

**Comment by rennervo** [comment]
A deleted tag is displayed after refresh page (only ISO)

Steps:
1. Go to Images to "ISO" tab
2. Go to a sidebar of any your ISO to "Tags" tab
3. Create any new tag
4. Delete this tag
5. Refresh page

Actual result: Tag wasn't deleted and it is displayed in tag-list
Expected result: Deleted tag there isn't in tag-list

**Comment by HeyRoach** [comment]
maybe this bug appears because BaseTemplateModel extends BaseModel
@tamazlykar, what do you think?

**Comment by tamazlykar** [comment]
I don't think so. This your command failed. Try to find why when you delete it right after creation you have wrong request params.
![screenshot from 2018-08-17 08-44-12](https://user-images.githubusercontent.com/18456914/44243577-f4c0ba00-a1f9-11e8-8565-783889eb1b95.png)
While good one looks like:
![screenshot from 2018-08-17 08-43-25](https://user-images.githubusercontent.com/18456914/44243583-0609c680-a1fa-11e8-8a7a-f68103218dd0.png)

**Comment by chewlite** [comment]
@HeyRoach 

**Firefox**
Doesn't repeat on the master

Steps:
1. Log in
2. Open section
VM/Storage/Images/Snapshots/Firewall/SSHkeys/Accounts
3. Open details sidebar 
4. Refresh the page

**Actual:**
Bottom of the page becomes white, for example
![2018-08-17 14-09-07](https://user-images.githubusercontent.com/32011943/44252701-429fe700-a227-11e8-9377-8d7ff1706438.png)
![2018-08-17 14-08-08](https://user-images.githubusercontent.com/32011943/44252702-429fe700-a227-11e8-85d6-8fa88268ba0a.png)

**Expected:**
Bottom of the page not becomes white

**Comment by chewlite** [comment]
@HeyRoach 

Tested on 1174
