### ISSUE TITLE
VM creation dialog enhancements

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#1177]
### Description
Change VM creation dialog (see the acceptance criteria)

### Acceptance criteria
1. Add 2 tabs "Main options" and "Additional options"
2. Show characteristics in two columns  
2.1. Main options:
  - Name
  - Zone
  - Service offering
  - Installations source
  - Disk offering

2.2. Additional options
  - Group
  - Affinity group
  - Firewall rules
  - SSH keys
  - Start VM

_Keyboard layout is to be moved to settings in #861_ 

3. Add the ability to resize root volume in VM creation (includes #1178) : 
 - "Disk size" + slider should be placed under "Installation source" when template is chosen (to do)
 - "Disk size" + slider should appear under "Disk offering" when ISO is chosen (it is already done for now)

_4. Change Affinity group selection (TBD in #1243)_

5. Firewall rules: 
- group  "default group" should be chosen by default
- default group name should be configurable in config. Add "default group name" parameter to config and let user change its name.

6. Think about reworking "SELECT" buttons placement (Service offering, Installation source, affinity group). The idea is to change a selection process (it might be a clicking on the entity instead of clicking "SELECT" button. To validate proposed changes with PM and PO. To create a separate enhancement task if there is a concrete suggestion.

7. Change styles for Disk offering (GB is too big, disk offering is too small). Make it coherent with other font sizes

**8. Please, approve mockups with PM before implementation**

### Connected feature ID

vm_creation_name, vm_creation_zone, vm_creation_so, vm_creation_so_custom, m_creation_installsource, vm_creation_installsource_filter, vm_creation_installsource_search, vm_creation_diskoffering, vm_creation_diskoffering_disksize, vm_creation_vmgroup, vm_creation_affinitygroup, vm_creation_firewall_template, vm_creation_firewall_shared, vm_creation_firewall_private_name, vm_creation_keyboard, vm_creation_sshkeypair, vm_creation_vmstart

### Mockup

![img_0597](https://user-images.githubusercontent.com/26703076/44321219-eb8d5280-a470-11e8-86b7-7e7e7cf84f12.JPG)

![1177 2](https://user-images.githubusercontent.com/26703076/44637245-580cd200-a9da-11e8-9ea7-8a33d024dd17.jpg)

**Comment by HeyRoach** [comment]
- [ ] 1

- [ ] 2

- [ ] 3

- [ ] 4

- [ ] 5

**Comment by HeyRoach** [comment]
Test:
config_defaultgroupname
vm_creation_name,
 vm_creation_zone, 
vm_creation_so,
 vm_creation_so_custom, 
m_creation_installsource, 
vm_creation_installsource_filter,
 vm_creation_installsource_search, 
vm_creation_diskoffering, 
vm_creation_diskoffering_disksize,
 vm_creation_vmgroup,
 vm_creation_affinitygroup, 
vm_creation_firewall_template, 
vm_creation_firewall_shared, 
vm_creation_firewall_private_name,
 vm_creation_keyboard, v
m_creation_sshkeypair, 
vm_creation_vmstart

**Comment by rennervo** [comment]
**1) Default group of other account is selected by default when VM creating**
Steps:
1. Log in with username = "develop'" and password = "qwerty123"
2. Go to VM
3. Click to Create button
4. Click  to "CREATE"

Actual result: There was an error in the VM deployment window about choosing the security group of another account (screenshot)
Expected result: Default security group of the current account is selected by default when VM creating
![2018-09-28 09-11-20](https://user-images.githubusercontent.com/26665398/46184235-d40e7880-c2fe-11e8-9255-3187baedc933.png)

**2) The field for selecting the disk size is present if a fixed disk offering is selected**
Steps:
1. Go to creating VM 
2. Go to selecting Installation source
3. Go to ISO tab, select any ISO and click "SELECT"
4. Go to selecting Disk offering
5. Select any fixed disk offering and click 'SELECT"

Actual result: Field for selecting the disk size is present in VM creating window (screenshot)
Expected result: Field is not present in VM creating window same as on the master. The slider is present if selected custom disk offering.
![select disk size](https://user-images.githubusercontent.com/26665398/46184753-39636900-c301-11e8-8dc1-d4a944062441.png)

**3) Incorrect selecting disk size by default**
Steps:
1. Use all free resource for your account
2. Go to VM
3. Click to "Create" button

Actual result: Disk size is always selected as 10 GB by default, even if there is not enough free space.

Expected result: Choose a default disk size of 10 GB if space is sufficient. If the free space is less than 10 GB, select the maximum possible free space (from 1 to 9). If there are 0 resources left, print a notification that there are no free resources, and the disk size selection field does not need to be displayed.

**Comment by HeyRoach** [comment]
(3) - It will be resolved in #1242

**Comment by rennervo** [comment]
Lack:2

**Selecting shared SG does not work when creating a VM**

**Description:**
The default shared SG can not be canceled. It is not selected in the group list, so you can not undo the selection. Other shared SG that will also be selected when creating the VM - will not be assigned to the created VM.

**Steps:**
1) Go to creating VM
2) Go to Advanced tab
3) Click to "Edit" in "Firewall rules" string 
4) Select any shared group except "Default" (Screenshot 1)
5) Click to "Save" button
6) Click to 'Create" button

**Actual result:**
- Default SG is not checked and can not be canceled in "Firewall rules" window
- Additional selected shared SGs are not assigned to the created VM (Screenshots 2, 3)

**Expected result:**
- Default SG is checked and can be canceled in "Firewall rules"
- Additional selected shared SGs are assigned to the created VM

**Feature ID:** vm_creation_firewall_shared

**Screenshots:**
Screenshot 1:
![default sg 1](https://user-images.githubusercontent.com/26665398/46269414-31a6fd00-c56b-11e8-9593-f298876608cc.png)
Screenshot 2:
![default sg 2](https://user-images.githubusercontent.com/26665398/46269420-3a97ce80-c56b-11e8-9c30-a2ac51577cd8.png)
Screenshot 3:
![default sg 3](https://user-images.githubusercontent.com/26665398/46269425-41264600-c56b-11e8-90a9-934672c77113.png)

**Comment by rennervo** [comment]
Tested on 1292
