### ISSUE TITLE
Add the ability to resize root volume in VM creation

### ISSUE THREAD

**Issue by tamazlykar** [bwsw/cloudstack-ui#1178]
Add the ability to resize the root volume during the creation of the virtual machine

Acceptance criteria:
1. when a user opens a VM creation, he should be able to change the size of a root disk
2. When a template is chosen (installation source), disk slider should be placed under "installation source"
3. If an ISO is chosen, this slider should disappear (disk offering resize slider appears vm_creation_diskoffering_resize)
4. A default value for a disk size in VM creation should be a size of a chosen template
5. Boundary values for a slider:
- min - 10GB
- max - as set in config (see the next point)
6. The same behavior should be in VM details sidebar (root disk resize feature)

**Connected feature ID:** vm_creation_rootdisk_resize, storage_disk_resize, config_maxrootdisksize

**Comment by ershovaelena** [comment]
TBD in #1177

**Comment by HeyRoach** [comment]
It was resolved in 1177 (test it there)
Test:
vm_creation_rootdisk_resize, 
storage_disk_resize,
 config_maxrootdisksize

**Comment by rennervo** [comment]
@bwsw 
There is an inconsistency between 4 and 5 criteria. The system may have patterns that are less than 10 GB in size. For example, now the system has templates with the names "# 1" (8 Gb) and "coreos-1745.7.0-5gb" (5 Gb) (for user "develop").
What is the minimum value for the root disk size slider in such cases?

I can offer such options:

1) The minimum size of the root disk can not be less than 10 GB. If the template size is less than 10 GB, then the minimum size of the root disk is 10 GB. If the template size is more than 10 GB, then the minimum size of the root disk is the size of the template.

2) The minimum size of the root disk is equal to the size of the template, even if the template is less than 10 GB in size.

**Comment by ershovaelena** [comment]
discussed with PO: remove 6th point of requirements (do not add config parameter). Description changed.

**Comment by rennervo** [comment]
Tested on 1292
