### ISSUE TITLE
Template/ISO Agreement appears with the scroll at the end of the page

### ISSUE THREAD

**Issue by HeyRoach** [bwsw/cloudstack-ui#1185]
**Steps to reproduce:**

1. Open VM creation
2. Click on Installation source
3. Select Template or ISO with tag: "csui.template.agreement"
4. Click on "Create" VM

**Actual result**
Agreement dialog appears with the scroll at the end of the page

**Expected result**
Agreement dialog appears with the scroll at the start of the page

**Environment**
```
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] Opera version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:
```
**Connected feature ID**
vm_creation_agreement

**Screenshots**
Initial form state
![image](https://user-images.githubusercontent.com/11550134/43623765-22323330-970d-11e8-8d80-c4e1a43b7e24.png)

**Comment by HeyRoach** [comment]
Proposal:
 ![image](https://user-images.githubusercontent.com/11550134/43624165-d8bf23fe-970f-11e8-9031-171f902f38db.png)

**Comment by tamazlykar** [comment]
PO approved these changes

**Comment by HeyRoach** [comment]
**Test on:**  1186

**Test:**
vm_creation_agreement

**Comment by rennervo** [comment]
Tested on 1186
