### ISSUE TITLE
Settings window for VM creating isn't opening for User role. An infinite throbber is displayed.

### ISSUE THREAD

**Issue by rennervo** [bwsw/cloudstack-ui#1190]
Steps to reproduce

1) Login with the User role
2) Go to VM and create new VM
3) Do not refresh a page and click "Create"

Actual result
An infinite throbber is displayed. Settings window for VM creating isn't opening. Browser console has no errors.

Expected result
Settings window for VM creating is opening

Environment

```
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] Opera version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:
```

Connected feature ID

Screenshots

**Comment by tamazlykar** [comment]
unable to reproduce
