### ISSUE TITLE
Display errors of Accounts section

### ISSUE THREAD

**Issue by rennervo** [bwsw/cloudstack-ui#1195]
#### 1. The filter name "Select Role Type" does not appear fully in Russian.
Actual result: The filter name is not completely displayed
Expected result: The filter name is completely displayed

#### 2. The number of IP addresses in accounts is not count. The error occurs in the "Details" and "Statistics" areas in the account's sidebar.
Steps to reproduce
1) Go to Accounts
2) Click on any account that has at least one VM

Actual result: The number of IP addresses is not count
Expected result: The number of IP addresses is count

#### 3. Field names are truncated in Russian. The error occurs in the "Limits" and "Statistics" areas in the account's sidebar.
Actual result: Field names are not displayed completely
Expected result: Field names are displayed completely

#### 4. "Copy" icons are missing in user's details on "Users" tab of account's sidebar. (Only IE browser)
Steps to reproduce
1) Go to Accounts
2) Click on account "develop"
3) Go to tab "Users"
4) Click to user "develop"

Actual result: "Copy" icons are missing
Expected result: "Copy" icons there are

### Environment
<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] Opera version XX
- [ ] IE version XX
- [ ] Edge version XX
Others:

</code></pre>
### Connected feature ID
account_list_filter
account_details_display
account_limits_display
account_statistics_display
account_user_apikey_copy
account_user_secretkey_copy
### Screenshots
![copy icons are missing](https://user-images.githubusercontent.com/26665398/43937462-fb5b8ff6-9c87-11e8-8e4c-f61c2cd04447.png)
![field names clipped limits](https://user-images.githubusercontent.com/26665398/43937463-fb8e22b8-9c87-11e8-886a-7ae46130f492.png)
![field names clipped statistics](https://user-images.githubusercontent.com/26665398/43937464-fbb10314-9c87-11e8-80b1-2de551fd994e.png)
![filter name is not complete](https://user-images.githubusercontent.com/26665398/43937465-fbd21b6c-9c87-11e8-8977-5a35ff19a9d4.png)

**Comment by tamazlykar** [comment]
1. This is to discuss with @bwsw.
2. This is not a bug, see the original interface.
3. This is to discuss with PO.
4. Agree

**Comment by ershovaelena** [comment]
The 4th problem wll be done in #1214

**Comment by ershovaelena** [comment]
After discussion with PO:
1. The filter name "Select Role Type" does not appear fully in Russian - don't fix it, we leave it as it is.
2. Not a bug
3. Field names are truncated in Russian. The error occurs in the "Limits" and "Statistics" areas in the account's sidebar - move long titles to 2nd line

**Comment by HeyRoach** [comment]
Test:
account_limits_display
account_statistics_display

Regressions:
account_user_apikey_copy
account_user_secretkey_copy
vm_NIC_display
account_details_display
account_limits_display
account_user_display
storage_diskoffering_display
volsnapshot_details_display
firewall_details_display

**Comment by chewlite** [comment]
@HeyRoach 

Tested on 1219
