### ISSUE TITLE
Custom service offering is not saved to user tags

### ISSUE THREAD

**Issue by rennervo** [bwsw/cloudstack-ui#1196]
### Description
Custom SO not save after change when creating VM.

### Steps to reproduce
1) Go to VM
2) Click on "Create"
3) Click Select SO
4) Change SO values to new
5) Create VM
6) Click on "Create" again
7) Click Select SO

### Actual result
SO values are old, which was before the change.

### Expected result
SO values are new for all users of this account, but SO values not change for other accounts.

### Environment
<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] Opera version XX
- [ ] IE version XX
- [ ] Edge version XX
Others:
</code></pre>

### Connected feature ID
vm_creation_so_custom

**Comment by tamazlykar** [comment]
You must store the values in custom tags, not in account tags. The tag is saved when the machine is created, not when changing values in the dialog box.

The values are used in the Service Offering dialog box and in the dialog with value selection.

These values have the highest priority in comparison with all the others.

**Comment by ershovaelena** [comment]
@HeyRoach please describe details of this configuration in config guide

**Comment by HeyRoach** [comment]
After discussion with PO:
The tag is saved when changing values in the dialog box

**Comment by HeyRoach** [comment]
Test:
vm_creation_so_custom

**Comment by chewlite** [comment]
@HeyRoach 

lack:1

**Values of the Custom SO doesn't save after logout and login under the same user if this custom SO isn't default**

Initial condition: Fixed SO is selected by default

Steps:
1) Open the VM creation 
2) Press SELECT in Service offering and go to Custom tab
3) Set new values for some custom SO and confirm changes
4) Logout and login under the same user
5) Repeat steps 1-2

Actual:
- CPU cores and CPU (MHz) that you set aren't save
- CPU cores and CPU (MHz) has a default values
- Memory (MB) has a value you set

Expected:
If you change custom SO values, confirm changes, then logout and login under the same user - CPU cores, CPU (MHz) and Memory (MB) of this custom SO should be saved

**Comment by chewlite** [comment]
The task got the "Testing Failed" by mistake
