### ISSUE TITLE
A tag consisting of spaces can not be deleted or changed

### ISSUE THREAD

**Issue by rennervo** [bwsw/cloudstack-ui#1197]
### Steps to reproduce
1. Go to VM / Images / Firewall
2. Click on any entity
3. Go to tab "Tags"
4. Create new tag with key = " " and value = " " (space)
### Actual result
The created tag can not be deleted or changed
### Expected result
The created tag can be deleted or changed
### Environment
<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] Opera version XX
- [ ] IE version XX
- [ ] Edge version XX
Others:

</code></pre>
### Connected feature ID
vm_tag_display
vm_tag_edit
vm_tag_delete
### Screenshots
![2018-08-10 12-40-16](https://user-images.githubusercontent.com/26665398/43940552-4f4ccc9e-9c9a-11e8-856c-7fad3d5169d7.png)

**Comment by tamazlykar** [comment]
@ershovaelena should we allow this tags?
I think this tags should be invalid. What do you think?

**Comment by HeyRoach** [comment]
Test:
vm_tag_create
vm_tag_edit
vm_tag_display
image_tag_display
image_tag_create
image_tag_edit
firewall_tag_display
firewall_tag_create
firewall_tag_edit

**Comment by ershovaelena** [comment]
Need to clarify requirements

**Comment by ershovaelena** [comment]
Discussed with PO:

The only restriction is n**o spaces as the first symbol** in keys and values. 
So user can enter numbers, spaces inside of keys and values, special symbols.

**Comment by rennervo** [comment]
**Error entering a space character in the "Value" field is not localized**

Steps:
1. Go to VM/Image/Firewall tags of any entity
2. Go to create or edit tag
3. Enter space character in "value" field

Actual result: Error appears with a text "TAGS.TAG_INVALID" 
Expected result: Error appears with a text "Field value must start with 'non-space' character"
![2018-08-28 14-53-40](https://user-images.githubusercontent.com/26665398/44709867-e2396100-aad4-11e8-85e1-5cddc2739488.png)

**Comment by rennervo** [comment]
Tested on 1215
