### ISSUE TITLE
Storages can not be deleted and attached to VM

### ISSUE THREAD

**Issue by rennervo** [bwsw/cloudstack-ui#1198]
#### 1. Storages can not be deleted
Steps to reproduce
1) Go to Storage
2) Click on action box of any additional storage
3) Select Delete

Actual result: Storage is not deleted, console error "Failed to attach local data volume <name storage> to VM null as migration of local data volume is not allowed" (screenshot 2)
Expected result: Storage is deleted, console error there is not.

#### 2. Storage in state "Ready" can not be attached to VM
Steps to reproduce
1) Go to Storage
2) Click on action box of any additional storage in state "Ready"
3) Select Attach
4) Select VM and press "ATTACH"

Actual result: Storage is not attached, error dialog appears with text "Cannot read property 'length' of undefined" (screenshot 1)
Expected result: Storage is attached to VM

### Environment
<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] Opera version XX
- [ ] IE version XX
- [ ] Edge version XX
Others:
</code></pre>
### Connected feature ID
storage_disk_attach
storage_disk_delete
### Screenshots
![2018-08-10 12-48-36](https://user-images.githubusercontent.com/26665398/43940783-76f5f97c-9c9b-11e8-9faa-67929ad8fd4f.png)
![2018-08-10 12-47-55](https://user-images.githubusercontent.com/26665398/43940769-64592302-9c9b-11e8-87ed-dbc9e03dc513.png)

**Comment by bwsw** [comment]
@rennervo 
Not a bug. See #1169

**Comment by bwsw** [comment]
Why delete doesn't work is a question.
