### ISSUE TITLE
Improve config validations 

### ISSUE THREAD

**Issue by tamazlykar** [bwsw/cloudstack-ui#1201]
Make validation based on JSON schemes. This will simplify the writing of validation for complex config configurations.

**Comment by tamazlykar** [comment]
We can use:
[ajv](https://github.com/epoberezkin/ajvl) as JSON Scheme validator
[ajv-keywords](https://github.com/epoberezkin/ajv-keywords) for additional features that not in the standard (like uniqueItemProperties)
[ajv-errors](https://github.com/epoberezkin/ajv-errors) for defining custom errors

**Comment by tamazlykar** [comment]
Regression:
config
vm_colorpicker

**Comment by chewlite** [comment]
@tamazlykar 

Tested on 1201
