### ISSUE TITLE
"Copy" icons are missing in user's details on "Users" tab of account's sidebar in IE

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#1214]
From fails of #1195

### Steps to reproduce
1. Go to Accounts
2. Click on account "develop"
3. Go to tab "Users"
4. Click to user "develop"

### Actual result:
 "Copy" icons are missing
### Expected result: 
"Copy" icons there are

Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] Opera version XX
- [x] IE version XX
- [ ] Edge version XX

### Connected feature ID
- account_user_apikey_copy
- account_user_secretkey_copy

**Comment by HeyRoach** [comment]
pull request number

Test:
account_user_apikey_copy
account_user_secretkey_copy
