### ISSUE TITLE
Access VM enhancements

### ISSUE THREAD

**Issue by bwsw** [bwsw/cloudstack-ui#1224]
There are three access modes currently supported: VNC, SSH, HTTP.

**1. VNC console access mode** 
For VNC console a user must see:

```
Login: {csui.vm.login|root}
Password: {csui.vm.password|Not Set}
Open VNC console (clickable link)
```

**2. SSH access mode** 
This mode is the default option for Unix. This access mode is defined by template tags:

- csui.vm.auth-mode = SSH
- csui.vm.ssh.login = login
- csui.vm.ssh.password = password
- csui.vm.ssh.port = port

If no `csui.vm.auth-mode=SSH` then no helper is shown for SSH, otherwise there are two options:
1. Webshell plugin is not deployed - no webshell launch link (see (2) pic. attached).
2. Webshell plugin deployed - (1) and webshell launch link displayed.

Show Connection string (IPv6) and IPv6 if supported (see (2) pic. attached). If IPv6 not supported don't show IPv6 strings.
If no SSH key installed, do not show SSH key string
_If webshell is deployed, it must open in a new window, not VNC window._

For SSH mode a user must see:
```
Connection String (IPv4): ssh -p{csui.vm.ssh.port|22} -u{csui.vm.ssh.login|csui.vm.login|root} <vmipv4> (copy)
Connection String (IPv6): ssh -p{csui.vm.ssh.port|22} -u{csui.vm.ssh.login|csui.vm.login|root} <vmipv6> (copy)
IPv4: <vmipv4>
IPv6: <vmipv4>
Port: {csui.vm.ssh.port|22}
Login: {csui.vm.ssh.login|csui.vm.login|root}
Password: {csui.vm.ssh.password|csui.vm.password|Not Set} 
SSH Key: name
Open WebShell (clickable link)
```

**3. HTTP access mode.** 
This mode is useful for templates with ready to use web systems deployed, like Wordpress, etc. It's regulated by next variables:

- csui.vm.auth-mode = HTTP
- csui.vm.http.protocol = HTTP|HTTPS
- csui.vm.http.port = 
- csui.vm.http.path =
- csui.vm.http.login = 
- csui.vm.http.password = 

For HTTP mode a user must see::

```
Login: {csui.vm.http.login|csui.vm.login|root}
Password: {csui.vm.http.password|csui.vm.password|Not Set}
Open URL: lowercase({csui.vm.http.protocol|http})://<vmip>:{csui.vm.http.port}{csui.vm.http.path|/}
```

if no `csui.vm.http.port`, then if `csui.vm.http.protocol = HTTPS`: 443, if `HTTP`: 80.
If no `csui.vm.http.protocol` then HTTP.

**4. In certain cases all three access modes can coexist. E.g. for template tags:**
```
csui.vm.auth-mode=HTTP,SSH
csui.vm.http.protocol=HTTP
csui.vm.http.login=Admin
csui.vm.http.password=zabbix
csui.vm.ssh.port=22
csui.vm.ssh.login=appliance
csui.vm.ssh.password=zabbix
```
- All three helpers must coexist (see mockups)
- If there is one or two modes not available, disable the tab

5. `csui.vm.auth-mode=HTTP,SSH` - support space between HTTP and SSH values -> `csui.vm.auth-mode=HTTP, SSH`

**6. Please, approve mockups with PM before implementation**

**Connected feature ID:** vm_postcreation_ISO, vm_postcreation_SSH, vm_postcreation_HTTP, vm_accessvm

**Mockup**

![1224](https://user-images.githubusercontent.com/26703076/46453063-9364a280-c7c9-11e8-8377-4b6a4a6f9185.JPG)

**Comment by ershovaelena** [comment]
Connected to #1226

**Comment by HeyRoach** [comment]
To test:
vm_postcreation_ISO, vm_postcreation_SSH, vm_postcreation_HTTP, vm_accessvm

**Comment by rennervo** [comment]
Lack:1

**1) The SSH key name is displayed separated by a comma if there is a space in the name**

If the name of the SSH key consists of several words and there is a space between the words, in the "Access VM" window on the "WebShell" tab a key with a comma between the words will be displayed. It seems that the VM has several keys.

**Steps:**
1. Create SSH key with several words in the name (add space between words in the name)
2. Create new VM with created SSH key
3. Add tag "csui.vm.auth-mode: SSH" in created VM
4. Go to "Access VM" window of created VM on "WebShell" tab

**Actual result:** Field "SSH-key" contains a value with a comma between words (Screenshot)
**Expected result:** Field "SSH-key" contains a value without a comma between words

**Screenshot:**
![ssh key comma](https://user-images.githubusercontent.com/26665398/46843659-1b682f00-cdfe-11e8-824d-96f4cefb2abc.png)

**2) The requirement of lowercase to the link "Open URL" in "URL" tab is not met if the values entered in the tags are uppercase**

**Steps:**
1. Create new VM
2. Add following tags to VM:
- csui.vm.auth-mode: HTTP
- csui.vm.http.protocol: HTTP
- csui.vm.http.path: PATH
3. Go to "Access VM" of created VM on "URL" tab

**Actual result:** Values from tags are uppercase in "Open URL" link (screenshot)
**Expected result:** All symbols in "Open URL" link are lowercase

**Screenshot:**
![uppercase in url tab](https://user-images.githubusercontent.com/26665398/46844470-620b5880-ce01-11e8-9adc-d82938f8ee00.png)

**3) The default value is incorrect for HTTP port when HTTP protocol is "HTTP"**
The default port for the "HTTP" protocol is 80, for the "HTTPS" protocol is 443

**Steps:**
1. Create new VM
2. Add following tags to VM:
- csui.vm.auth-mode: HTTP
- csui.vm.http.protocol: HTTP
3. Go to 'Access VM" of created VM on "URL" tab

**Actual result:** Default port for the 'HTTP" protocol is 443 (screenshot)
**Expected result:** Default port for the 'HTTP" protocol is 80

**Screenshot:**
![default port for http protocol](https://user-images.githubusercontent.com/26665398/46845027-c4655880-ce03-11e8-93ea-b3e26742a2e5.png)

**4) The system is blocked and an error appears in the console if you click on an incorrect "Open URL" link**
By blocking the system means that requests to the API are not sent. For example, you cannot stop a VM or grouping VMs in a list.

**Steps:**
1. Create new VM
2. Add following tags to VM:
- csui.vm.auth-mode: HTTP
- csui.vm.http.port: asdasdasd (invalid value)
3. Go to 'Access VM" of created VM on "URL" tab
4. Click to "Open URL" link (screenshot)

**Actual result:** System is blocked, an error is in the console
**Expected result:** System is not blocked, an error is in the console

**Screenshot:**
![click to invalid open url link](https://user-images.githubusercontent.com/26665398/46845642-7b62d380-ce06-11e8-8f63-71fad548211c.png)

**Comment by HeyRoach** [comment]
@ershovaelena 
When URL (in URL tab) is invalid an error appears and URL non-clickable
