### ISSUE TITLE
Access helpers don't work as expected

### ISSUE THREAD

**Issue by bwsw** [bwsw/cloudstack-ui#1226]
#### (1) Steps to reproduce 
1. Go to VM section
2. Choose VM created from a template with `auth-mode=SSH` tag
3. Open Access VM
4. Open VNC console
5. VNC console window opens
6. Open WebShell

#### (1) Actual result
WebShell, URL are opened in VNC console window
#### (1) Expected result
All 2 windows are opened separately

#### (2) Actual result
Template tags are missing
#### (2) Expected result
1. SSH access mode is defined by template tags:
- csui.vm.auth-mode = SSH
- csui.vm.ssh.login = login
- csui.vm.ssh.password = password
- csui.vm.ssh.port = port
2. These tages are copied to VM during VM creation
3. These tags are described in the wiki

**Connected feature ID:** vm_postcreation_ISO, vm_postcreation_SSH, vm_postcreation_HTTP, vm_accessvm

**Comment by bwsw** [comment]
When a VM is created from a template or ISO, all tags must be copied to VM. Certain tags are interpreted in a special way when a user wants to get an access to a VM.

There are three access modes currently supported:
1. VNC console access mode. This mode doesn't allow passing certain arguments inside and provided natively by CloudStack. VNC mode assumes that a user uses local OS authentication method, e.g. console login for Unix, UI-based login for Windows. Anyway, a user needs to know certain credentials - login and password. The templates may be password enabled, so when created they generate a password and return it back (maybe generated upon VM start if VM is launched stopped, to test it). Basically, our system supports storing this password into "csui.vm.password". Another thing to know is login which may differ from template to template, e.g. in Windows - Administrator or even Администратор, for UNIX-based - root, administrator, ubuntu, centos, etc. It can be any name, actually. Users, when creating VMs, don't know that name beforehand.

**Comment by tamazlykar** [comment]
The password generated upon VM start if VM is launched stopped. #1141

**Comment by ershovaelena** [comment]
Connected to #2

**Comment by ershovaelena** [comment]
Description changed after the discussion with PO. Enhancements are moved to #1224

**Comment by HeyRoach** [comment]
- [ ] Add description to wiki

- [ ] fix first bug

- [ ] fix second bug

- [ ] fix bug with spaces between auth-mode values

**Comment by HeyRoach** [comment]
Test:
vm_postcreation_ISO, 
vm_postcreation_SSH,
 vm_postcreation_HTTP, 
vm_accessvm

**Comment by rennervo** [comment]
Tested on 1266
