### ISSUE TITLE
customOfferingRestrictions feature does not work

### ISSUE THREAD

**Issue by tamazlykar** [bwsw/cloudstack-ui#1230]
customOfferingRestrictions should describe the compute offerings, their limitations on the number of cores, the processor frequency and the amount of memory. See [config guide](https://github.com/bwsw/cloudstack-ui/blob/master/config-guide.md#custom-offering-restrictions)
Add Validation.

Also, there is the ability to set 0 values in the custom SO params, which doesn't make sense. Restrict this.

**Connected feature ID:** config_so_custom_restrictions

**Comment by tamazlykar** [comment]
Found an additional bug. 
The app doesn't show compute offering if they need more resources than available. But if available resources equal to a minimum allowed parameters for custom compute offering then this offering also will be suppressed.

**Comment by ershovaelena** [comment]
@tamazlykar please describe details of this configuration in config guide

**Comment by tamazlykar** [comment]
To test:
All places where config is used. Check just presence, not logic.
For example, if you set serviceGroupTemplates and you see it where it should be that's should be enough. I changed the way we get this values, not logic.

See additional bug above.

Regression:
config_so_custom_restrictions
vm_creation_so_custom
config_offering_availability

**Comment by ershovaelena** [comment]
Includes #1144

**Comment by chewlite** [comment]
@tamazlykar 

lack:1

**1. Incorrect validation**
Actual: you can set max<min for any of parameters in customOfferingRestrictions ("cpunumber", "cpuspeed", "memory")
Expected: if max<min then default values are applied in customOfferingRestrictions

**2. Please, fix the description of customOfferingRestrictions in the Config Guide:**
- there is shouldn't be 
"Any of these parameters may be left unspecified, in which case 0 will be used for min and infinity will be used for max." 
- but should be
"All parameters are required. If any of them invalid or missed then default values are applied for all in customOfferingRestrictions"

**Comment by rennervo** [comment]
1) Configure "Default Service Offering" is failed. It will be fixed in #1231 
2) Configuration "Session Refresh Interval" does not work same as expected. 
Actual result: Requests in "Network" browser tab are **not sent** when the session update time is reached.
Expected result: Requests in "Network" browser tab are **sent** when the session update time is reached.

**Comment by Nadya913** [comment]
Tested for policy - ok

**Comment by tamazlykar** [comment]
@chewlite 
1. JSON schemes don't allow to check this case. We can't do this in an easy way. It's up to user to set proper values for now.
2. This is a bug from #940. I fix it and added tests. There were two cases for this bug: **First**, when you set minimum restriction to the input field greater than 0 and type to the input field a 0 value. **Second** case, when you set maximum restriction to the input field lower than 0 (e.g -5) and type to the input field a 0 value.

**Comment by rennervo** [comment]
Error with "Session Refresh Interval" is transferred to task #1273

**Comment by ershovaelena** [comment]
@rennervo 3. Incorrect description of customOfferingRestrictions in the Config Guide - removed from  config guide

**Comment by rennervo** [comment]
Tested on 1267 in a simulator
