### ISSUE TITLE
Errors of configuration "serviceOfferingClasses"

### ISSUE THREAD

**Issue by rennervo** [bwsw/cloudstack-ui#1233]
**1) Displaying multiple classes named "Common" when the class name is empty**

Steps:
1 Create in config.json serviceOfferingClass with a unique id, description, service offerings (At least one)
2 Leave class name empty
3 Go to the VM creation window (in CS UI)
5 Go to SO selection window
6 Click to the drop-down list of select SO Class

Actual result: SO list has two classes with the name "Common" (screenshot)
Expected result: SO list has only one class with the name "Common". Class with an empty name not displayed and all its SO attached to class "Common".
![empty name of service offering class](https://user-images.githubusercontent.com/26665398/44702173-4d2a6e00-aabc-11e8-87be-12c46b7ba6e0.png)

**2) Filtering by SO class does not have a result when so the class has empty id**

Steps:
1 Create in config.json serviceOfferingClass with a name, description, service offerings (At least one)
2 Leave class ID empty
3 Go to the VM creation window (in CS UI)
5 Go to SO selection window
6 Click to the drop-down list of select SO Class
7 Select created class without ID

Actual result: Filtering does not have a result (screenshot)
Expected result: Class with an empty id not displayed and all its SO attached to class "Common".
![empty id of service offering class](https://user-images.githubusercontent.com/26665398/44702182-59163000-aabc-11e8-879b-fbebc1e04caa.png)

**3) If a SO belongs to several classes, then when choosing a SO, the last class is always marked**

Steps:
1 Create in config.json two serviceOfferingClasses with a different id, name, description
2 Add one SO to both classes
3 Go to the VM creation window (in CS UI)
5 Go to SO selection window
6 Select repeating SO in first class

Actual result: Repeating SO is selected in second class, an error appears in the console (screenshot)
Expected result:  Repeating SO is selected in first class, an error there is not in the console
![one so for multiple classes](https://user-images.githubusercontent.com/26665398/44702190-67644c00-aabc-11e8-8dae-42c459ac7162.png)

**Comment by ershovaelena** [comment]
@rennervo 
1. Not a bug. The system should not move classes with no name to "common". An empty name is also a name. 
- We might enhance the displaying of such classes by showing "_No name_" in a drop-down.
- Leave it as it is (empty).
@bwsw what do you think?
2. 
3. @bwsw Is it okay that SO is displayed 2 times in the list (in 2 classes) ? should we restrict adding SO to several classes ? If no need to restrict, then we'll try to fix this problem (the solution is not obvious. Research is needed)

**Comment by bwsw** [comment]
@ershovaelena @rennervo 
3. OK, no problem. I don't see "what is not obvious" there. If the SO defined in several classes, show it in each.
2. I don't see the problem with id = "". It's stupid but it's up to user.

> Not a bug. The system should not move classes with no name to "common". An empty name is also a name.

I don't catch what "name" is, as I see, the name is "ID" if ID is defined somehow, even `""` it's ok to classify it. 

> 2) Filtering by SO class does not have a result when so the class has empty id
It's a bug for sure.

3) If a SO belongs to several classes, then when choosing a SO, the last class is always marked
It's a bug for sure. It should be displayed in every class to which it belongs.

**Comment by ershovaelena** [comment]
Discussed with PO:
1. Not a bug. The system should not move classes with no name to "common". An empty name is also a name.
2. A bug, to fix
3. A bug: SO presented in several classes (so repeated in the list) should be chosen exactly where a user clicks on a radio button

**Comment by HeyRoach** [comment]
For information:
id should contain at least 1 character

**Comment by rennervo** [comment]
Tested on 1247 in a simulator
