### ISSUE TITLE
Rework the left-side menu

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#1235]
This issue covers the following requirements:
[REQ_GEN_006] A user should be able to see the left-side menu and navigate through sections.

**Acceptance criteria:**

**1. Change the structure of the left-side menu.** 
1) There should be two 1-level sections (Virtual Machines, Accounts).
2) When a user clicks on 1-level section, a detailed menu opens (2-level sections).
3) User can come back to 1-level section by clicking on sandwich button
3) The structure of the menu:

Virtual Machines
- Virtual machines
- Storage
- Images
- Snapshots
- Firewall
- SSH keys
- Logout

Accounts
- Accounts
- Activity Log
- Settings
- Logout
4) Use as an example (see the gif attached). The only difference is that we do not have a fixed up-side panel, so sandwich button that opens and hides 1-level menu should be presented in both modes (see a gif).
5) VM (2 level) should be opened by default
6) Login information should be displayed in 2 level
7) Logout should be displayed in both levels (1st and 2nd) 

**2. Remove features (as this structure changes the way the menu works) from the code + from config + from documentation**
1) Hide/collapse sidebar (sidenav_show)
2) Reorder sidebar (sidebar_reorder)

**3. Please, approve mockups with PM before implementation**

**Connected feature ID:** sidenav, sidenav_show, sidebar_reorder

**Example**

![menu](https://user-images.githubusercontent.com/26703076/45133634-8e0f3a80-b1c0-11e8-8637-2847bd688384.gif)

**Comment by chewlite** [comment]
@tamazlykar 
Tested on 1333
