### ISSUE TITLE
Template Group with empty ID is available for filtering and for adding templates in group

### ISSUE THREAD

**Issue by rennervo** [bwsw/cloudstack-ui#1236]
Steps:
1. In config.json create a template group with translate and with an empty ID
2. In CS UI go to Images
3.1. Click to a drop-down list of filtering by groups
3.2. Go to a sidebar of any image and click to an icon of group editing

Actual result: Template group with empty ID is available for select
Expected result: Template group with empty ID s not in the list
![Template Group empty ID.png](https://images.zenhubusercontent.com/5a5c77c24b5806bc2bc2be22/69beed83-7b23-4a6a-b6c3-cf7e86c3b45a)

**Comment by ershovaelena** [comment]
To investigate whether it is possible to validate it in json scheme

**Comment by HeyRoach** [comment]
For information:
add validation: id should contain at list 1 character,
translations might be '' , because  it's up to the user

Test:
config_image_group
