### ISSUE TITLE
You can not select installation sources when creating a VM

### ISSUE THREAD

**Issue by rennervo** [bwsw/cloudstack-ui#1238]
Steps:
1. Go to VM
2. Click to Create button
3. Click to "Select" button in "Installation source" area

Actual result: Window for selecting installation source opens with console error (screenshot), a selection is not possible.
Expected result: Window opens without errors, a selection is possible.
![Снимок экрана от 2018-08-29 10-18-47.png](https://images.zenhubusercontent.com/5a5c77c24b5806bc2bc2be22/adc578a8-1b78-4ea8-91ab-27904b1314a1)

**Comment by ershovaelena** [comment]
@HeyRoach  Probably changes #893 caused this problem

**Comment by HeyRoach** [comment]
Test:
vm_creation_installsource
vm_creation_installsource_filter

**Comment by rennervo** [comment]
Tested on 1240
