### ISSUE TITLE
"Delete" in system SG template action box when "preselected":false in config

### ISSUE THREAD

**Issue by chewlite** [bwsw/cloudstack-ui#1241]
### Steps to reproduce
1. Set "preselected":false for the one of system templates in the "securityGroupTemplates" [] in the config
2. Go to Firewall
3. Open the action box of the system template from Step 1

### Actual result
There is disabled "Delete" action

### Expected result
There is no "Delete" action

### Environment
<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Chromium version XX
</code></pre>

### Connected feature ID
firewall_actionbox

### Screenshots
Template with "preselected":true
![2018-08-29 17-09-13](https://user-images.githubusercontent.com/32011943/44781895-be971900-abaf-11e8-8386-6a30d43b437f.png)
Template with "preselected":false
![2018-08-29 17-08-53](https://user-images.githubusercontent.com/32011943/44781919-ca82db00-abaf-11e8-9fb8-b54922b95255.png)

**Comment by rennervo** [comment]
Tested on 1248 in a simulator
