### ISSUE TITLE
Rework "affinity group" section in VM creation and VM details sidebar

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#1243]
This issue covers the following requirements:
1. [REQ_VM_CREATE_014] A user should be able to set the VM affinity group in VM creation
2. [REQ_VM_DTLS_006] A user should be able to manage VM affinity groups

We should support displaying the type of affinity groups: affinity/ anti-affinity and adding several affinity groups.

**Acceptance criteria:**

**VM creation**

1. Change Affinity group selection: 
1.1. Add "SELECT" button
1.2. When clicking "SELECT" button, a dialog opens
1.3. The dialog is alike with "firewall rules" edit dialog: user can choose an existing group from the list or create a new one above the list
1.4. New group creation: fields 
   - "name" (input 63 symbols max), 
   - "select type" ("anti-affinity", "affinity" in drop-down), 
   - description (input 63 symbols max)

Mandatory fields: name, type

1.5. The list of existing groups: two columns "name, "type". Name has a tooltip with description (if there is one). Radio buttons to choose one group
N.B: a user can create a new group but choose another one in the list.
1.6. Buttons "CANCEL" and "SELECT"

**VM details sidebar**

1. Name and a type of groups should be displayed in "**Affinity groups**" section of the sidebar
- Name should be positioned left-aligned, type - right-aligned (the same line)
- Name should have a tooltip with a description (optional, if there is a description for the group)
2. Adding new Affinity group 
- When a user clicks "add", a modal dialog opens (the same as in VM creation #1177)
- Actual groups are displayed at the beginning of the list, but no actions available for already selected groups
- A user can choose one group in the list or create a new one (2.1)
- Each time a user can add only one group, but in general he can add as many groups as he wants by clicking "add" each time

2.1. New group creation
- The dialog is alike with "firewall rules" edit dialog (as in VM creation #1177): a user can choose an existing group from the list or create a new one above the list
- New group creation: fields
"name" (input 63 symbols max), "select type" ("anti-affinity", "affinity" in drop-down), description (input 63 symbols max). Mandatory fields: name, type

3. Affinity group deletion
- "delete" button is placed near each group and displayed on hover (like in tags tab)
- when a user clicks "delete" a modal dialog opens
- user approves a dialog by clicking "yes"
- affinity group deletes is not displayed in the list of groups

**4. Please, approve mockups with PM before implementation**

**Connected feature ID:** vm_afgroup_display, vm_afgroup_change, vm_afgroup_delete

**Mockup**
![affinity](https://user-images.githubusercontent.com/26703076/45140139-1a7b2680-b1dc-11e8-8860-833691cf0aa6.png)

**Comment by ershovaelena** [comment]
This issue covers the following requirements:
1. [REQ_VM_CREATE_014] A user should be able to set the VM affinity group in VM creation
2. [REQ_VM_DTLS_006] A user should be able to manage VM affinity groups

**Comment by Nadya913** [comment]
Lack1:
1. First name column for list is too long in case of long group name. 
Expected: long name is cutted ( by ...) or moved on next row, no horizontal schroll
Actual: horizontal schroll appears, long name is present 
![list](https://user-images.githubusercontent.com/33111683/47282370-28103280-d609-11e8-8c58-3775699ba094.png)

2. According 1.5 should be no description as column but a tooltip.
> 1.5. The list of existing groups: two columns "name, "type". Name has a tooltip with description (if there is one). Radio buttons to choose one group
![description](https://user-images.githubusercontent.com/33111683/47283094-fc427c00-d60b-11e8-8219-9cbc8df5a8ad.png)

3. Alphabetical order is creashed after some value is selected once.
![order](https://user-images.githubusercontent.com/33111683/47283578-26953900-d60e-11e8-9bbb-0a17812e083c.png)
Steps:
 1. Press create VM 
 2. Go to advanced, press select for some affinity group and chose some value
 3. press select for some affinity group one more time
 expected: values in Alphabetical order
 actual: selected value appears in first row



4.

**Comment by HeyRoach** [comment]
@Nadya913 
about 3 fail:
but in ticket description ( vm details sidebar (2.2) ) we have:

Actual groups are displayed at the beginning of the list, but no actions available for already selected groups

**Comment by ershovaelena** [comment]
@HeyRoach add "No group" / RU as the 1st element in the list in VM creation

**Comment by chewlite** [comment]
lack:2

**1. VM creation - Not the alphabetical order of existing groups in the modal window**
Expected result: alphabetical order of existing groups before and after the new group adding (par. 3 from Nadya's comment with fails)

**2. VM creation - Radiobutton isn't selected by default for "No affinity group" in the modal window**
Expected result: in lists with radio buttons, one of them should always be selected (in this case "No affinity group")

**3. VM creation - In the window with the progress of VM creation _(vm_creation_progress_logger feature)_ line about affinity group creation is always active, even after deploy completed**
![2018-10-25 12-36-49](https://user-images.githubusercontent.com/32011943/47480956-576aad80-d85c-11e8-8078-f66965acb675.png)
![2018-10-25 11-48-15](https://user-images.githubusercontent.com/32011943/47480957-576aad80-d85c-11e8-9c0c-bb16588461bf.png)

Steps:
1. In the VM creation window, open the affinity group selection modal window
2. Add the new group to the list and select it
3. Click Create
Actual result: line about affinity group creation is always active, even after deploy completed

**Comment by HeyRoach** [comment]
About 3
In a new interface we create affinity group in affinity group dialog (not in the deployment process)
because of this we dont see anything about affinity group in deployment dialog

**Comment by chewlite** [comment]
@HeyRoach 
Tested on 1343
