### ISSUE TITLE
'VM will be rebooted' message doesn't appear

### ISSUE THREAD

**Issue by HeyRoach** [bwsw/cloudstack-ui#1265]
### Steps to reproduce
Initial state:
VM with status 'Start'. Service offering should be 'Custom'

1. Open a sidebar of a VM
2. Click on 'Change' button in 'ServiceOffering' paragraph
3. Change parameters for selected offering

### Actual result
Params are changed. No message appears.

### Expected result
 Params are changed. Warning message 'Virtual machine will be rebooted' appears. (see screenshot)
<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] Opera version XX
- [ ] IE version XX
- [ ] Edge version XX
</code></pre>

### Connected feature ID
vm_SO_change

### Screenshots
![image](https://user-images.githubusercontent.com/11550134/45077156-a32f8f00-b116-11e8-8501-5721043552df.png)

**Comment by bwsw** [comment]
Use word "restarted".

**Comment by ershovaelena** [comment]
For QA:
1. Notice that the message should be "VM will be **restarted**"
2. If the current SO is chosen (radio button), then SELECT button should be disabled (no reason to change).

**Comment by tamazlykar** [comment]
Regression:
vm_SO_change
vm_creation_so
vm_creation_so_custom

**Comment by chewlite** [comment]
@tamazlykar 

Tested on tamazlykar:1265-reboot-message (on the simulator)
