### ISSUE TITLE
The color of any selected value in the drop-down list does not match the color scheme

### ISSUE THREAD

**Issue by mdbardina** [bwsw/cloudstack-ui#127]
Select a value from any drop-down list (for example, VM filtering). The selected value is always blue.
I think it should match the color scheme.
![2017-05-10 11-24-36](https://cloud.githubusercontent.com/assets/25217218/25931338/ef82846e-3635-11e7-8f87-952567d6e32f.png)

**Comment by ershovaelena** [comment]
Not needed
