### ISSUE TITLE
Configuration "Session Refresh Interval" does not work as expected

### ISSUE THREAD

**Issue by rennervo** [bwsw/cloudstack-ui#1273]
**Description:**
The "Session Refresh Interval" configuration should update the session according to the specified time interval, but update requests are not answered on the "Network" tab in the browser.

**Steps:**
1) Set parameter "sessionRefreshInterval" to 15 in config.json
2) Go to system and log in as a new user

**Actual result:** Requests in "Network" browser tab are not sent when the session update time is reached.
**Expected result:** Requests in "Network" browser tab are sent when the session update time is reached - every 15 seconds.

**FeatureID:** config_sessionrefresh

**Comment by tamazlykar** [comment]
Regression:
config_sessionrefresh

**Comment by chewlite** [comment]
Tested on tamazlykar:1273-session-refresh-interval on the simulator
