### ISSUE TITLE
Grouping by colors for VM list is not working

### ISSUE THREAD

**Issue by rennervo** [bwsw/cloudstack-ui#1280]
**Description:**
If you select several groupings for the VM, among which there will be grouping by colors, and group by color in the first place in the grouping priorities, then only grouping by colors will work, the remaining groupings will be ignored.

**Steps:**
1) Go to VM (Make sure you have at least 2 VMs)
2) Set any color for one of VMs and leave rest VMs without colors
3) Select several groupings, among which there will be grouping by colors
4) Put grouping by colors in the first place

**Actual result:** Only grouping by colors works, the rest of the groupings are not displayed (see screenshot)
**Expected result:** All selected groups work on the principle of nesting: first, the VMs are grouped by colors, then grouped according to the queue of the other groupings. All groupings are displayed in the VM list.

**Screenshots:**
"Colors" in the last place
![Colors in last place.png](https://images.zenhubusercontent.com/5a5c77c24b5806bc2bc2be22/a03555dd-6e8a-46cf-a007-e6a5d27c437d)
"Colors" in the second place
![Colors in second place.png](https://images.zenhubusercontent.com/5a5c77c24b5806bc2bc2be22/9e753977-f604-44a0-8c1b-edc09c171fd0)
"Colors" in the first place
![Colors in first place.png](https://images.zenhubusercontent.com/5a5c77c24b5806bc2bc2be22/9bd83817-2d87-4b55-bd23-a86027de483e)

**Feature ID:**
vm_list_groupby
vm_colorpicker

**Comment by HeyRoach** [comment]
Test:
vm_list_groupby
vm_colorpicker

**Comment by chewlite** [comment]
@HeyRoach 
Tested on 1289
