### ISSUE TITLE
IE, Edge - selection of year in datepickers work incorrectly in Snapshots and Activity log

### ISSUE THREAD

**Issue by chewlite** [bwsw/cloudstack-ui#1297]
### Description
In **IE** and **Edge** browsers _**if you set the russian language**_ in settings and go to selection of a year in datepicker in Snapshots or in Activity log you will get the wrong display and behavior of datepicker

### Steps to reproduce
1. Log in and set the russian language in the Settings
2. Go to Activity log/Snapshots
3. Open the datepicker
4. Click to year
5. Click to any year in the list

### Actual result

_1. When you open the years list in datepicker:_
- the symbols "г." are displayed next to every year like "1994 г."
- the list is displayed from the beginning
- the current year isn't highlighted: font size and color are the same as for all years

_2. When you click to any year the selected year isn't saved and the empty calendar is displayed_

### Expected result

(!) Expected result shouldn't depend on environment or language in the system

_1. When you open the years list in datepicker:_
- the year is displayed without any letters, just numbers of the year like "1994"
- the part of the list in which the current year is located is displayed: current year in the middle of displayed list, a few years before and a few years after the current year
- the current year is highlighted: font size is larger than the others, color is blue

_2. When you click to any year the selected year is saved and the calendar is displayed with highlighted selected current date_

### Environment

<pre><code>
Browser:
- [ ] IE version XX
- [ ] Edge version XX
</code></pre>

### Connected feature ID
volsnapshot_list_datepicker
activitylog_datepicker_display
activitylog_datepicker_change
settings_language_change

### Screenshots

**Actual result:**
![1111](https://user-images.githubusercontent.com/32011943/45943722-b1841300-c011-11e8-9c69-fcca3d938322.png) ![2222](https://user-images.githubusercontent.com/32011943/45943724-b3e66d00-c011-11e8-9b31-b6760213b152.png)
**Expected result:**
![3333](https://user-images.githubusercontent.com/32011943/45943729-b8ab2100-c011-11e8-94b1-194bc3afffe4.png) ![4444](https://user-images.githubusercontent.com/32011943/45943738-be086b80-c011-11e8-806e-8f9965d93e81.png)

**Comment by wowshakhov** [comment]
To test:
volsnapshot_list_datepicker
activitylog_datepicker_display
activitylog_datepicker_change
settings_language_change

**Comment by rennervo** [comment]
Tested on 1311
