### ISSUE TITLE
Button "Clear completed" in pending window is not changed when you hover the cursor

### ISSUE THREAD

**Issue by rennervo** [bwsw/cloudstack-ui#1298]
### Description
Button "Clear completed" must change color to "gray" when you hover the cursor.

### Steps:
1) Go to VM
2) Click to "Pending bell" icon
3) Hover the cursor on 'Clear complete" button

### Environment
<pre><code>
Browser:
- Chrome version 69.0.3497.100 64-bit
- Opera version 55.0.2994.61
- Chromium version 69.0.3497.92 64-bit

OS:
- Ubuntu version 17.10
</code></pre>

### Connected feature ID
notification_snackbar

**Comment by wowshakhov** [comment]
Can't reproduce on most systems. This is probably a problem with the the specific combination of Browser + OS. Probably not worth fixing right now.
