### ISSUE TITLE
Implement VM groups through proper groups

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#1307]
VM group should be implemented through proper groups, not through VM tags.

This issue covers the following requirements:
1. [REQ_VM_CREATE_013] A user should be able to set VM group (VM creation)
2. [REQ_VM_DTLS_004] A user should be able to manage VM groups (VM details sidebar)
3. [REQ_VM_LIST_004] A user should be able to filter the VM list by VM groups

**Comment by ershovaelena** [comment]
This issue includes:
1. Removing the old code (tags)
2. Unit tests

**Comment by wowshakhov** [comment]
To test:
REQ_VM_CREATE_013
REQ_VM_DTLS_004
REQ_VM_LIST_004
