### ISSUE TITLE
Implement Log View plugin

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#1314]
This epic is dedicated to the implementation of UI for [Log View plugin](https://github.com/bwsw/cloud-plugin-vm-logs)

**Comment by wowshakhov** [comment]
To test: 
VM logs

extension config:

- Should be able to enable/disable webshell
- Should be able to enable/disable vm logs

If VM logs plugin is disabled:

- No link in sidenav
- Should redirect from /logs to /instances
- No action in VM actions

If VM logs plugin is enabled:

- Link in sidenav
- Should open /logs
- 'Logs' action in VM actions

Timepicker in all places
Datepicker in all places

**Comment by Nadya913** [comment]
1. DateTimepicker is broken in Firefox, Opera, Chromium, Safari
ERROR TypeError: "t.component.currentRoute is undefined"

**Comment by Nadya913** [comment]
Tested on log branch
