### ISSUE TITLE
An error appears while vm deploying

### ISSUE THREAD

**Issue by HeyRoach** [bwsw/cloudstack-ui#1316]
### Description
An error appears in console (see attached pic) while vm deploying

### Steps:
Go to VM
Click on "+" button
Reload page
Click on "Create" button

### Actual result: 
Vm is'not created, an error in console appears

### Expected result:
Vm is created without any errors

### Environment
<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] Opera version XX
- [ ] IE version XX
- [ ] Edge version XX

</code></pre>

### Connected feature ID
vm_creation

![image](https://user-images.githubusercontent.com/11550134/46592428-d3d75f80-caec-11e8-8e3b-427a1dc86c92.png)

**Comment by wowshakhov** [comment]
To test:
vm_creation through (+) button on /instances and through /instances/create.
Security groups in VM creation

**Comment by chewlite** [comment]
@wowshakhov 
Tested on 1317
