### ISSUE TITLE
[Log View] Load logs for a VM

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#1320]
This issue covers the following requirements:

1. [REQ-LOGS-002] A user should be able to select VM when setting the log view parameters
2. [REQ-LOGS-008] A user should be able to view logs of VM
3. [REQ-LOGS-009] A user should be able to change parameters for viewing VM logs.

**Comment by Nadya913** [comment]
1. Layout of the log text in Firefox, Edge, IE: text should have margin on the end and transfer to other row.
![text](https://user-images.githubusercontent.com/33111683/46934173-f46d5f80-d080-11e8-9480-67ac2a5d9476.png)
2. Header of table columns are not vertical alligned in IE11.
![ie](https://user-images.githubusercontent.com/33111683/46934197-0ea73d80-d081-11e8-8b06-5f5f04821f8f.png)

**Comment by wowshakhov** [comment]
2. Header of table columns are not vertical alligned in IE11.
Discussed with PO, decided not to fix.
