### ISSUE TITLE
Implement filtering area in VM snapshots list

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#1331]
A part of an epic #412

This issue covers the following requirements:
1. [REQ_SNAP_LIST_011] A user should be able to filter the list of VM snapshots
2. [REQ_SNAP_LIST_012] A user should be able to group the list of VM snapshots
3. [REQ_SNAP_LIST_013] A user should be able to select a date in the list of VM snapshots

Mockup

![925](https://user-images.githubusercontent.com/26703076/35896647-c76ce376-0bef-11e8-8892-006605e566f1.jpg)

**Comment by tamazlykar** [comment]
Test to:
[REQ_SNAP_LIST_011]
[REQ_SNAP_LIST_012]
[REQ_SNAP_LIST_013]
Regression:
[REQ_SNAP_LIST_003]
[REQ_SNAP_LIST_005]

**Comment by rennervo** [comment]
Tested on 1430

**Comment by ershovaelena** [comment]
@rennervo Decided to move REQ_SNAP_LIST_012 (group by) to a separate issue (to fix lack:1 there VMs and Volume grouping)
