### ISSUE TITLE
Implement VM snapshots details sidebar

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#1332]
A part of an epic #412

This issue covers the following requirements:
1. [REQ_SNAP_DTLS_002] A user should be able to view information about VM snapshot: details, description, VM information

Mockup

![925](https://user-images.githubusercontent.com/26703076/35896647-c76ce376-0bef-11e8-8892-006605e566f1.jpg)

**Comment by tamazlykar** [comment]
To test:
REQ_SNAP_DTLS_002
Regression:
Added a state icon for volume snapshots in the sidebar
