### ISSUE TITLE
New Virtual machine Dialog minor fixes

### ISSUE THREAD

**Issue by bwsw** [bwsw/cloudstack-ui#1335]
Minor fixes to SO chooser dialog:
1. Round values (Click "Show additional fields")
2. Rename "Show/hide additional fields" to "Show/hide details"

**Comment by rennervo** [comment]
### Additional display problems with the October 16 demo:

**1) The title with the size of the disk runs over the icon for opening information in the selection dialog of the disk offering**

**Description:**
This behavior is observed in two cases:
- When the size of the disk offers more than two characters (for example 120 GB)
- When the name and description of the DO are long

**Steps:**
1. Log in and go to Storage
2. Click to the button of creation
3. Click to "SELECT" button in disk offering string

**Actual result:** The title with the size of the disk runs over the icon for opening information in the selection dialog of the disk offering when the size of the disk offers more than two characters or the name and description of the DO are long (screenshots)

**Expected result:** The title with the size of the disk does not run over the icon, regardless of the number of characters in the title and the length of the name and description.

**Feature ID:** storage_disk_create, vm_creation_diskoffering

**Screenshots:**
![layout 1](https://user-images.githubusercontent.com/26665398/46995828-973ae200-d144-11e8-9909-c92de98c4382.png)
![layout 2](https://user-images.githubusercontent.com/26665398/46995831-9a35d280-d144-11e8-85f2-5b7853e4cd52.png)


**2) The disk offering description should be a smaller line under the name**

**Description:**
At the request of the PO, the description should be displayed in a smaller line, which is under the name of the disk offering.

**Steps:**
1. Log in and go to Storage
2. Click to the button of creation
3. Click to "SELECT" button in disk offering string

**Actual result:** The description is the same size as the name, and is on the same line as it. (screenshot)

**Expected result:** The description should be displayed in a smaller line, which is under the name of the disk offering.

**Feature ID:** storage_disk_create, vm_creation_diskoffering

**Screenshots:**
![description do](https://user-images.githubusercontent.com/26665398/46996119-ba19c600-d145-11e8-9e72-f539795ebfba.png)

**Comment by wowshakhov** [comment]
1) Round values (Click "Show additional fields") - not tested locally because of #1372 
2) The disk offering description should be a smaller line under the name - will be done in a separate task

To test:
VM creation/Service offering/Show details - values should not have long decimal parts
VM/Resource usage:
Fractional quantities (memory, storage) should have 1 decimal digit
Integer quantities (number of VMs, number of CPUs...) should not have decimal part

Need to add requirements about precision of numbers

**Comment by ershovaelena** [comment]
For QA: please refer to req doc 1.411.24 for 1 and 2 points of the main description

**Comment by ershovaelena** [comment]
This issue covers the following requirements:
1. [REQ_VM_CREATE_004]
2. [REQ_VM_LIST_002]
