### ISSUE TITLE
The user sees an empty element for selecting the color of the VM if the configuration of the "vmColors" is empty

### ISSUE THREAD

**Issue by rennervo** [bwsw/cloudstack-ui#1336]
### Description
If the user in the "vmColors" configuration leaves the body empty, then he does not want to be able to choose colors for the VM. In this case, the color selection element does not need to be output, and all current VMs should be made white.

### Steps to reproduce
1. Set following value for "securityGroupTemplates" in config.json:
"vmColors": []
2. Go to the system in the VM section
3. Click to any VM
4. Click on the button to change the color of the VM

### Actual result
Element for change the color of the VM is opened, but it's empty (screenshot), all VMs have retained their colors. (screenshot)

### Expected result
Element for change the color of the VM is not opened, all VMs have a white color.

### Environment

<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

### Connected feature ID
vm_colorpicker

### Screenshots
![Снимок экрана от 2018-10-15 13-29-20.png](https://images.zenhubusercontent.com/5a5c77c24b5806bc2bc2be22/2b55dd43-7999-46e4-87b8-855f61efa4cb)

**Comment by HeyRoach** [comment]
Test to:
vm_colorpicker

**Comment by chewlite** [comment]
@HeyRoach 
Tested on 1336-vm-colors
