### ISSUE TITLE
[Log View] Show logs in a real-time mode

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#1341]
This issue covers the following requirements:
[REQ-LOGS-011] The user should be able to view the logs in real time

**Comment by Nadya913** [comment]
1. By clicking Follow Log button table becomes emty with No results (in case no new logs are sent).

Steps:
- Login and go to Logs
- Select VM with logs and press Show Logs (See the logs appear)
- Press Follow Logs 

Expected: Logs are the same as before pressing Follow log
Actual: No results is present
![logs](https://user-images.githubusercontent.com/33111683/47629937-96f10c80-db70-11e8-9a58-b6ba365e06f3.png)
