### ISSUE TITLE
Research Danger.js 

### ISSUE THREAD

**Issue by elenaustyugova** [bwsw/cloudstack-ui#1349]
1. Research [Danger.js](https://github.com/danger/danger-js), decide if we want to use it and if we do, suggest possible scenarios.

Examples:
- Enforce CHANGELOGs
- Enforce links to tickets
- Enforce using descriptive labels
- Look out for common anti-patterns
- Give warnings when specific files change

2. Approve proposed changes with PM and the team
3. Implement changes (to decide whether to do it in this issue or to create another)

**Comment by ershovaelena** [comment]
Max time for this research is 3 hours
