### ISSUE TITLE
When changing the color of one VM, the color of another VM can be randomly changed when the grouping by colors is turned on

### ISSUE THREAD

**Issue by mdbardina** [bwsw/cloudstack-ui#135]
See the screenshots.
The color of the BM 454544gtdgtyrty is green, the color of the VM vm-develop-18 is light green.
![2017-05-12 09-22-23](https://cloud.githubusercontent.com/assets/25217218/25980096/a8695988-36f6-11e7-9c62-346db2d0ee47.png)

Change the color of the BM 454544gtdgtyrty to violet, the color of VM vm-develop-18 changes to blue independently.
![2017-05-12 09-23-15](https://cloud.githubusercontent.com/assets/25217218/25980100/abbf8b48-36f6-11e7-8bfa-12d06e19fced.png)

Plus the strange logic of grouping by colors. The same colors are not near.

**Comment by ershovaelena** [comment]
Can not reproduce. Please, reopen this issue if QA reproduces this bug.
