### ISSUE TITLE
Unable to change disk offering

### ISSUE THREAD

**Issue by tamazlykar** [bwsw/cloudstack-ui#1352]
### Description
Unable to change disk offering from fixed to fixed, because of wrong API request. The app should not pass a `size` parameter to request if newly selected a fixed offering.

### Steps to reproduce
1. Create fixed/custom volume.
2. Try to change disk offering to another fixed disk offering of newly created volume.

### Actual result

Error, see a screenshots.

### Expected result

Disk offering changed succesfully.

### Environment
<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] Opera version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

### Connected feature ID

storage_disk_resize

### Screenshots

An error:
![screenshot from 2018-10-18 11-29-51](https://user-images.githubusercontent.com/18456914/47131850-27a32f00-d2cb-11e8-99bb-85552bb6f15a.png)
Actual API request:
![screenshot from 2018-10-18 11-29-56](https://user-images.githubusercontent.com/18456914/47131865-3558b480-d2cb-11e8-9deb-04fd2d068eb2.png)

**Comment by HeyRoach** [comment]
Test to:
storage_disk_resize

**Comment by chewlite** [comment]
lack:1

@HeyRoach 

Error when resizing the disk to the same DO 

![2018-10-29 15-11-48](https://user-images.githubusercontent.com/32011943/47639449-dd0b9780-db93-11e8-830b-bb0e566e49a1.png)

**Comment by HeyRoach** [comment]
@chewlite it would be great if you add more info about DO (type, for example, and steps)
'cause I spend time trying to reproduce it

**Comment by chewlite** [comment]
@HeyRoach 
I'm so sorry. I will change the comment

**Comment by HeyRoach** [comment]
@Nadya913 
I can't reproduce an error like in fail
When I repeat steps above I get another one error (see my attach)
![image](https://user-images.githubusercontent.com/11550134/47763838-ea8c6300-dcf4-11e8-97e7-6a3e050cc481.png)

**Comment by Nadya913** [comment]
Erroe for resizing Root volume in console:  ERROR TypeError: Cannot read property 'iscustomized' of undefined
Steps:

- Login and go to Storage 
-  Resize Root (of VM without VM shapshots) with some bigger size 
Expected: disk is resized
Actual: error in console, disk isn't resized
![root](https://user-images.githubusercontent.com/33111683/47902732-2d953480-deb5-11e8-8486-9f8efe6d8b0e.png)

**Comment by Nadya913** [comment]
Lack 3:
Error when resizing the disk to the same fixed disk offering (DO)

Steps:

- Open  the action box of the data disk with some fixed DO
- Click  "Resize the disk"
- In the "Resize volume" window click "Resize" button
or
select the same fixed DO that is already selected then click "Resize" button
Actual result: Error appears
Expected: disk is resized
![resize](https://user-images.githubusercontent.com/33111683/48182110-a5071000-e35c-11e8-8ee4-ea3f5f64d43e.png)
