### ISSUE TITLE
Dialog about the deletion of attached data disk does not appear when VM destroyed if the disk doesn't have snapshots

### ISSUE THREAD

**Issue by chewlite** [bwsw/cloudstack-ui#1355]
### Description

If VM has a data disk attached and you destroy this VM then there is no dialog about the deletion of attached data disk if this disk doesn't have the snapshot
### Steps to reproduce
1. Create a VM
2. Attach some data disk with no snapshots to this VM
3. Destroy this VM

### Actual result

There is no dialog about the deletion of attached data disk and error in the console
![2018-10-19 14-23-08](https://user-images.githubusercontent.com/32011943/47205811-33692100-d3b1-11e8-8225-86195b5dca82.png)

### Expected result

There is the dialog about the deletion of attached data disk (+ option for deleting snapshots of this disk)
![2018-10-19 15-08-58](https://user-images.githubusercontent.com/32011943/47205797-2815f580-d3b1-11e8-9036-c5e6c9417a76.png)

### Environment

<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Chromium version XX
- [ ] Firefox version XX
- [ ] Opera version XX
- [ ] Safari version XX
- [ ] IE version XX
- [ ] Edge version XX
</code></pre>

### Connected feature ID
vm_destroy_datadrives

**Comment by HeyRoach** [comment]
Test to:
vm_destroy_datadrives

**Comment by chewlite** [comment]
@HeyRoach 
Tested on 1360
