### ISSUE TITLE
Implement TestStore 

### ISSUE THREAD

**Issue by tamazlykar** [bwsw/cloudstack-ui#1357]
Implement the TestStore, update all the tests that use it and fix the menu tests.
See for info `https://github.com/ngrx/platform/issues/915`

**Comment by ershovaelena** [comment]
To test vm logs #1341

**Comment by ershovaelena** [comment]
To create an issue - after adding test store we should check existing unit tests and change those that do not work properly

**Comment by HeyRoach** [comment]
Check also commented tests with "todo"
