### ISSUE TITLE
Config loading error for deprecated allowReorderingSidebar, sidebarOrder

### ISSUE THREAD

**Issue by Nadya913** [bwsw/cloudstack-ui#1361]
### Description
Config isn't loading and no validation error in console for deprecated allowReorderingSidebar, sidebarOrderfor for Config.

### Steps to reproduce
1. Set in config.json allowReorderingSidebar or  sidebarOrder with the values
2. Start the application

### Actual result

Config isn't loading.
An error:
 meta-reducers.ts:12 action LoadConfigError {payload: {…}, type: "[Http] Load config error"}payload: {error: Error: schema should be object or boolean
    at Ajv._addSchema (http://localhost:8080/vendor.js:131…}type: "[Http] Load config error"__proto__: Object

### Expected result

Config is loading and error in console for deprecated allowReorderingSidebar, sidebarOrderfor options.

### Connected feature ID

config_sidebar_reorder
config_configure_sidebar

**Comment by chewlite** [comment]
@wowshakhov 
Tested on 1361-config-error
