### ISSUE TITLE
VM creation window collapses and console error appears sometimes when page refresh

### ISSUE THREAD

**Issue by chewlite** [bwsw/cloudstack-ui#1372]
### Description
There is the supposition that sometimes when you open VM creation window something in code downloads faster or slower then it should.
The problem may be somewhere in this piece of code:
```
    VmCreationComponent.prototype.isSubmitButtonDisabled = function (isFormValid) {
        return (!isFormValid ||
            this.nameIsTaken() ||
            !this.vmCreationState.template ||
            !this.vmCreationState.serviceOffering.isAvailableByResources);
    };
```

### Steps to reproduce
This bug is hard to catch. Frequent page refresh or slow internet may work

### Actual result
![image](https://user-images.githubusercontent.com/32011943/47540451-7b32ff80-d8ff-11e8-8eb2-0fad67f05be0.png)

### Expected result
VM creation window opens with all its contents, no errors in the console

### Connected feature ID
vm_creation

**Comment by ershovaelena** [comment]
To discuss with PO: this problem occurs when a user sets SO in config which ID is incorrect.
We suggest to treat this case the following way: 
1. VM creation dialog opens
2. An error message (red color) in SO section: "ID of SO that you set in config is invalid. Please change your configurations"
3. Create button is disabled

**Comment by ershovaelena** [comment]
The previous comment was discussed with PO. 

This issue covers the following requirements:
[REQ_VM_CREATE_024] If an invalid ID is specified in the default compute offering configuration, then it should be missing when creating a VM

**Comment by HeyRoach** [comment]
Test to:
REQ_VM_CREATE_024
