### ISSUE TITLE
Tabs Template/Iso are dissapeared in resizing case

### ISSUE THREAD

**Issue by Nadya913** [bwsw/cloudstack-ui#1378]
### Description
Tabs Template/Iso for Image section are dissapeared in resizing case.

### Steps to reproduce
1. Login and go to Image
2. Resize the window by width 

### Actual result
Tabs Template/Iso for Image section are dissapeared.

### Expected result
Tabs Template/Iso for Image section are present. Filters come to next row.

### Connected feature ID
image_list_switch
![image](https://user-images.githubusercontent.com/33111683/47555484-2363bb00-d936-11e8-8bf9-62b42bd25b53.png)

**Comment by HeyRoach** [comment]
To test:
image_list_switch

**Comment by chewlite** [comment]
@HeyRoach 
Tested on 1386
