### ISSUE TITLE
When mouse is on "enter" button - cursor doesn't become active in Chrome browser

### ISSUE THREAD

**Issue by mdbardina** [bwsw/cloudstack-ui#138]
If the login and password are stored in chrome, then at the log in to the system they are already entered. And when mouse is on "enter" button - cursor doesn't become active. But if you click on the button, you can log in.
Expected result: the mouse cursor changes to the cursor-hand, the "enter" button is highlighted and becomes active.
![_001](https://cloud.githubusercontent.com/assets/25217218/25988084/de8e5bec-3720-11e7-9956-2ff590fd1315.png)

**Comment by andrewbents** [comment]
@zolotyx @ershovaelena this is the way Chrome Autofill works. It fills the fields, but it doesn't expose the password field value to JS until a user interacts with the page, which causes the form to be invalid. The only workarounds I found involve checking the field value over time
