### ISSUE TITLE
[Log View] Request logs with defined parameters

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#1383]
This issue covers the following requirements:
1. [REQ_LOGS_016] Logs should be updated in the UI with a defined frequency in the real-time mode
2. [REQ_LOGS_017] Logs should be requested every time for a defined period of time in the real-time mode

**Comment by wowshakhov** [comment]
To test:
REQ_LOGS_016
REQ_LOGS_017
