### ISSUE TITLE
[Log View] Filter parameters should be stored in user tags

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#1384]
This issue covers the following requirements:
1. [REQ_LOGS_019] Filter parameters should be stored in user tags

**Comment by Nadya913** [comment]
1. For user undefined NAN in calendars.
![dates](https://user-images.githubusercontent.com/33111683/49360308-60785580-f70b-11e8-8456-4953a177b32b.png)
2. After logout/login the filters ate not saved.
Steps:

- Login by user 
- Go to VMs logs and set vm filter
- Logout and Login one more time

Expected: vm is selected 
Actual: no vm selected
