### ISSUE TITLE
Support letters of all existing languages as the 1st letter of entities

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#1391]
This issue covers the following requirements:
[REQ_GEN_008] If the first element of an entity name should be a letter, then this letter can be a letter of any language

The first element of entity's names should be a letter of all langagues (not only russian and english).
This requirement is to be applied **only for cases where we now have A-Z / А-Я letters as the 1st element.**

**Comment by bwsw** [comment]
It also called as "non-space character" usually.

**Comment by HeyRoach** [comment]
List of entities:
affinity-group
vm

**Comment by rennervo** [comment]
Tested on master

**Entities tested:**
- affinity-group
- template-group
- instance-group

**Languages for testing:**
- Russian
- English
- Deutsch
- Chinese
- Arab
- Hindi
