### ISSUE TITLE
Add an overflow and a tooltip to VM card (CPU, RAM, DISKS) in case of long values

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#1398]
This issue covers the following requirements:
[REQ_VM_LIST_001] A user should be able to view the list of VMs.

Please see the screen attached. This issue is dedicated to avoid a change of card's height when values of CPU, RAM, DISKS are long.

<img width="668" alt="2018-10-31 11 59 10" src="https://user-images.githubusercontent.com/26703076/47767047-6c37bd00-dd04-11e8-8d67-1c4d53711bc8.png">

**Comment by HeyRoach** [comment]
Test to:
REQ_VM_LIST_001
