### ISSUE TITLE
Use ngrx store for account capabilities

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#1403]
Now it is received in AuthService

**Comment by wowshakhov** [comment]
To tests
REQ_LOGIN_001
REQ_LOGIN_004
REQ_VM_CREATE_011
REQ_VM_DTLS_013
REQ_VM_DTLS_046
REQ_STORAGE_LIST_008
REQ_STORAGE_LIST_015
REQ_VM_CREATE_010
REQ_VM_CREATE_012
Allowed to view destroyed VMs

- Login, logout, and refresh (F5)
- Min and max sizes of volume creation and resize everywhere (they should be loaded properly when controls appear on screen)
- VM destroy and expunge (check that canExpungeOrRecoverVm in CS capabilities works correctly)

**Comment by rennervo** [comment]
Lack: 1

**The status "Destroyed" is not in the filter by VM status**

The error repeats regardless of the value of the global setting "allowuserviewdestroyedvm"

**Steps to reproduce:**
1) Make sure the global setting "allowuserviewdestroyedvm" is set to "true"
2) Log in to the "Virtual machines" section
3) Open the drop-down list of the filter "Select states"

**Actual result:** "Destroyed" item is not on the list
**Expected result:** The item "Destroyed" is on the list

**Comment by rennervo** [comment]
Tested on 1466
