### ISSUE TITLE
Create VM with default name even when user deletes proposed name 

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#141]
To avoid system naming when a user deletes proposed name during VM creation. To assign default name for VM even in this situation. 

See the screenshot attached.

**Comment by ershovaelena** [comment]
![2](https://cloud.githubusercontent.com/assets/26703076/25989307/bf7955a4-3725-11e7-9112-50f62cdda593.PNG)

**Comment by andrewbents** [comment]
fixed in #181
