### ISSUE TITLE
No modal dialog "Save for all VMs" appears  if No was chosen previously

### ISSUE THREAD

**Issue by Nadya913** [bwsw/cloudstack-ui#1418]
### Description
No modal dialog "Save for all VMs" appears for after VM creation modal, VM password resetting in case if No was select on such previous modal.

### Steps to reproduce
1. Log in as user
2. Create VM from template with password enabled option
3. Press Save password and press No for modal dialog "Save for all VMs" 
4. Create VM from template with password enabled option
5. Press Save password

### Actual result
No modal dialog "Save for all VMs" appears, password is saved

### Expected result
Modal dialog "Save for all VMs" appears, password is saved.
If NO was clicked - This dialog appears every time a user clicks a save password button.

### Environment

<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] IE version XX
- [ ] Edge version XX
Others:
</code></pre>

### Connected REQ ID
REQ_VM_LIST_016

### Screenshots
![modal.png](https://images.zenhubusercontent.com/59faba338a75884b9085bd93/f3f5f03f-d4d9-43d8-b921-481598b1eff2)

**Comment by tamazlykar** [comment]
Not a bug, see #1140 
Requirements will be changed.
