### ISSUE TITLE
VMs color can't be changed

### ISSUE THREAD

**Issue by Nadya913** [bwsw/cloudstack-ui#1419]
### Description
Color of VMs can't be changed.

### Steps to reproduce
1. Log in as user
2. Click on any VM
3. Select any color

### Actual result
VM doesn't change the color

### Expected result
VM color is changed ro selected one

### Environment

<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] IE version XX
- [ ] Edge version XX
Others:
</code></pre>

### Connected REQ ID
REQ_VM_DTLS_001

### Screenshots
![color](https://user-images.githubusercontent.com/33111683/48751264-095b9500-ecb6-11e8-9cb3-27667ab3775a.png)

**Comment by tamazlykar** [comment]
To test:
REQ_VM_DTLS_001
