### ISSUE TITLE
Errors in attached data disk section in VM sidebar

### ISSUE THREAD

**Issue by Nadya913** [bwsw/cloudstack-ui#1420]
### Description
Errors for view attached data disk on VM sidebar.

### Steps to reproduce
1. Log in as user
2. Click on any VM, go to Storage
3. Press arrow for any attached data disk

### Actual result
Arrow is stil open, element are present (see the screen)
ERROR TypeError: Cannot read property 'miniops' of undefined
    at Object.updateDirectives (main.fb9c33d7b9e111edc2c0.js:1)
    at Object.updateDirectives (main.fb9c33d7b9e111edc2c0.js:1)

### Expected result
Arrow is switched to close, no errors in console, no elements like in attach appear

### Environment

<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] IE version XX
- [ ] Edge version XX
Others:
</code></pre>

### Connected REQ ID
REQ_VM_DTLS_010

### Screenshots
![storage](https://user-images.githubusercontent.com/33111683/48751397-c221d400-ecb6-11e8-8e06-c42439624af9.png)

**Comment by tamazlykar** [comment]
To test:
REQ_VM_DTLS_010
