### ISSUE TITLE
Manage "Revert VM to snapshot" and "Create VM snapshot" limitations for stopped VMs

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#1428]
This issue covers the following requirements:
1. [REQ_SNAP_LIST_015] A user should be able to revert VM to VM snapshot 
2. [REQ_VM_DTLS_042] A user should be able to revert VM to VM snapshot  in VM details sidebar
2. [REQ_VM_DTLS_040] A user should be able to create VM snapshot in VM details sidebar

**Comment by HeyRoach** [comment]
TEST:
[REQ_SNAP_LIST_015]
[REQ_VM_DTLS_042]
[REQ_VM_DTLS_040]

Also in this pull request was implemented #1416

**Comment by Nadya913** [comment]
1. If  run the stopped VM (or vice versa) and try to create vm snapshot, got error VM snapshot creation is unavailable for destroyed VMs
![stopped](https://user-images.githubusercontent.com/33111683/51464498-49afc000-1d98-11e9-951c-e2c930e82b5c.png)

**Comment by HeyRoach** [comment]
@Nadya913 
Which message did you expect?
VM snapshot creation is unavailable for stopped VMs / Создание снимков ВМ недоступно для остановленных ВМ

**Comment by Nadya913** [comment]
> @Nadya913
> Which message did you expect?
> VM snapshot creation is unavailable for stopped VMs / Создание снимков ВМ недоступно для остановленных ВМ

@HeyRoach sorry for missing the expect result: VM snapshot creation is unavailable for stopped VMs / Создание снимков ВМ недоступно для остановленных ВМ
