### ISSUE TITLE
Update Angular to version 7

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#1444]
https://update.angular.io/

**Comment by wowshakhov** [comment]
To test:
General visual QA: buttons, cards and other components.
Idle logout
Grouping
Clipboards

**Comment by rennervo** [comment]
**1) Error in the console when opening dropbox grouping**

Steps:
1. Go to any section with grouping.
2. Open/close the grouping box.

Actual result: In the console, an error occurred when opening and closing the dropbox
Expected result: No error in the console
![2018-12-14 15-05-39](https://user-images.githubusercontent.com/26665398/49990875-d2755800-ffb1-11e8-9ef2-2515d77a1e70.png)

**2) Filters moved down in the snapshot section [FF]**

Steps:
1. Go to the snapshots section.

Actual results: Filters are shifted down
Expected Result: Filters aligned to the center of the Volume / VM switch
![filters from ff](https://user-images.githubusercontent.com/26665398/49990867-ca1d1d00-ffb1-11e8-83e4-2207124b6701.png)

**3) The buttons in the Service Offerings selection window are shifted to the center**

Steps 1:
1. Go to the VM section
2. Click on the "Create" button
3. Go to Service offering selecting dialog

Steps 2:
1. Go to the VM section
2. Go to the sidebar of any VM
3. Go to Service offering changing dialog

Actual results: The buttons "Cancel", "Select", "Show details" are shifted to the center
Expected Result: The buttons are aligned to the right
![so buttons](https://user-images.githubusercontent.com/26665398/49990991-3435c200-ffb2-11e8-9108-6e467f1c7fed.png)
