### ISSUE TITLE
[Log View] Implement "Log View" section in VM details sidebar

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#1445]
This issue covers the following requirements:
1. [REQ_LOGS_021] A user should be able to сreate token in VM action box
2. [REQ_LOGS_022] A user should be able to copy token in VM action box
3. [REQ_LOGS_023] A user should be able to open a documentation link after the token is created
4. [REQ_LOGS_024] A user should be able to invalidate created token in VM action box

**Comment by wowshakhov** [comment]
To test:
REQ_LOGS_021
REQ_LOGS_022
REQ_LOGS_023
REQ_LOGS_024
