### ISSUE TITLE
Sidebar Resize Bugs

### ISSUE THREAD

**Issue by rennervo** [bwsw/cloudstack-ui#1446]
### VM Section:
**1) Action box button goes off the screen when compressing the sidebar**

Steps:
1. Go to VM sidebar
2. Reduce to the end sidebar size

Actual result: The button of action box is missing from the sidebar
Expected result: The button of action box is present on the sidebar and is aligned to the right
![Action box from VM sidebar.png](https://images.zenhubusercontent.com/5a5c77c24b5806bc2bc2be22/0f7df5b4-782b-4d9a-bd55-0e23512cd38f)

**2) The tooltips of the "Details" area are below and to the left when the sidebar is expanded**

Steps:
1. Go to VM sidebar on "Virtual machine" tab
2. Maximum expand the sidebar
3. Hover over the value of "VM host name" or "Zone" fields

Actual result: The tooltip is lower and to the left than necessary
Expected result: The tooltip is immediately below the value
![Tooltips in Details.png](https://images.zenhubusercontent.com/5a5c77c24b5806bc2bc2be22/666baef7-26d6-4131-8926-e2112a993260)

**3) The tooltip values for the "Disk offering" field are above and to the left**

Steps:
1. Go to VM sidebar on "Storage" tab
2. Maximum expand the sidebar
3. Open advanced options for a disk that has disk offering data
4. Hover over the value of "Disk offering" field

Actual result: The tooltip is higher and to the left than necessary
Expected result: The tooltip is immediately below the value
![Tooltip for disk offering.png](https://images.zenhubusercontent.com/5a5c77c24b5806bc2bc2be22/2b4b59fd-4c97-4689-ae68-724161d16f89)

**4) The "Eye" icon is shifted to the left when the sidebar is expanded**

Steps:
1. Go to VM sidebar on "Network" tab
2. Maximum expand the sidebar

Actual result: The "Eye" icon of SG is shifted to the left in "Firewall rules" area
Expected result: The "Eye" icon of SG is aligned to the right in "Firewall rules" area
![eye icon for SG in VM sidebar.png](https://images.zenhubusercontent.com/5a5c77c24b5806bc2bc2be22/51ebb138-f0d7-4b87-8668-79d2614cb205)

### Images section:

**1) The button of action box moves to the left when expanding the sidebar**

Steps:
1. Go to ISO or Templates sidebar, that has action box button
2. Maximum expand the sidebar

Actual result: Action box button moves to the left
Expected result: Action box button is aligned to the right
![Action box in Image sidebar.png](https://images.zenhubusercontent.com/5a5c77c24b5806bc2bc2be22/a5869daa-fcaa-4e3f-984d-c1fe00f39639)

### Firewall section:

**1) Tabs do not stretch along the entire length when expanding the sidebar**

Steps:
1. Go to Firewall Template, Shared SG or Private SG sidebar
2. Maximum expand the sidebar

Actual result: Tabs are aligned to the left.
Expected result: The tabs are evenly stretched along the entire length of the sidebar, as well as in the sidebars of other sections.
![Tabs in Firewall sidebar.png](https://images.zenhubusercontent.com/5a5c77c24b5806bc2bc2be22/974d3f6b-6787-4c16-b612-e8bd5acd8000)

### Accounts section:

**1) Values and icons of fields "Secret key" and "API key" are shifted to the left when expanding the sidebar**

Steps:
1. Go to Account sidebar on "Users" tab
2. Expand information for a user with Secret and API keys

Actual result: Values and icons of keys are shifted to the left
Expected result: Values and icons of keys are aligned to the right
![Values and icons of account keys .png](https://images.zenhubusercontent.com/5a5c77c24b5806bc2bc2be22/340adf69-ec5c-496b-aa75-c5f9fc10b114)

### Additional:

**1) The resize feature does not work at the bottom of the sidebar**
Make sure that you can correct this error and it is necessary. If necessary, discuss with the PM or PO.

Steps:
1. Open any sidebar that has a lot of data in the tab (for example VM "Virtual machine" tab or Account "General" tab)
2. Scroll down to the bottom of the tab

Actual result: Unable to resize sidebar at the bottom
Expected result: You can change the size of the sidebar in any of its parts

### Environment

<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:
</code></pre>

### Connected REQ ID
REQ_GEN_007

**Comment by wowshakhov** [comment]
To test:
REQ_GEN_007

Regression:
Text formatting in sidebar in all places

**Comment by ershovaelena** [comment]
@rennervo the last additional fail is the fail of the used library. Not fixed.
