### ISSUE TITLE
Notification bell icon does not change position when switching to a section without a sidebar

### ISSUE THREAD

**Issue by rennervo** [bwsw/cloudstack-ui#1453]
### Description
When switching between sections, notification bell icon should always accept the default position, regardless of whether there is a sidebar in the section or not.

### Steps to reproduce
1) Go to VM section
2) Click on any VM card/string to open the sidebar
3) Go to "View logs" section

### Actual result
Notification bell icon does not change position

### Expected result
The icon is located in the default position (top right corner of the window)

### Environment

<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Opera version XX
- [ ] Chromium version XX
- [ ] Safari version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:
</code></pre>

### Connected REQ ID
REQ_GEN_003

### Screenshots
![peek 2018-11-30 10-30](https://user-images.githubusercontent.com/26665398/49267359-9a87f400-f48c-11e8-9fa5-e115448e7c72.gif)

**Comment by wowshakhov** [comment]
To test:
REQ_GEN_003

**Comment by rennervo** [comment]
Lack: 1

The additional problem described by Elena is not completely fixed.

**The number of unread notifications shifted down [FF, Edge]**

**Steps:**
1. Perform any action that is displayed in the notification bell.

**Actual result:** The digit is shifted down (see screenshot)
**Expected result:** The digit is displayed in the center of its area.

**Environment:**
- Mozilla Firefox ( ver. 61.0.1 [x64] )
- Microsoft Edge ( ver. 41.16299.785.0 )  

**Screenshot:**
![2018-12-05 14-17-29](https://user-images.githubusercontent.com/26665398/49498307-33f44300-f89d-11e8-9dc3-ddd079fdac91.png)

**Comment by rennervo** [comment]
Tested on 1459
