### ISSUE TITLE
[RSC request/release] View and update resource limits by domain administrator

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#1458]
This issue covers the following requirements:
[REQ_RSC_001] A user (administrator) should be able to view and update resource limits

First, provide mockups

**Comment by wowshakhov** [comment]
https://github.com/bwsw/cloudstack-ui/issues/1457 and https://github.com/bwsw/cloudstack-ui/issues/1519 are done in https://github.com/bwsw/cloudstack-ui/pull/1505

**Comment by Nadya913** [comment]
1. After the resources were updated the dialog isn't closed.
2. Resourse current values are not alligned with the sliders.
3. Slider circle is trimmed. 
![testresource](https://user-images.githubusercontent.com/33111683/51096668-cb2fad00-17f0-11e9-8187-c9d411ccd984.png)

**Comment by Nadya913** [comment]
@HeyRoach  Discussed with PM  - first issue shouldn't be fixed.
Second issue isn't repeat any more.
Ticket should return to retesting as for blocking third issue is fixed.

**Comment by HeyRoach** [comment]
@Nadya913 What about translating an error (which I got yesterday)?
Also, I can't reproduce the third issue

**Comment by Nadya913** [comment]
> @HeyRoach please also check the font size. It seems to be too large. To discuss with PM.

in failed point 2 there is this issue with fonts.

**Comment by Nadya913** [comment]
1. For failed case 3 there is no translation for error 'max must be between 2 and 1' error from backend.
Expected:  'Maximum must be between 2 and 1 ' /  'Максимальное значение должно быть между 2 и 1'
![max](https://user-images.githubusercontent.com/33111683/51656419-9f23e100-1fd3-11e9-9aea-fca11edfe3a0.png)

2. Incorrect value for min slider value for  Instances appears. 
Expected: max (min qouta, used resources) Expected: slider on 2 (min = max=2 )

**Comment by HeyRoach** [comment]
@Nadya913 
After discussion with PM:
Change button in Resourse page in dialog
from 'Request' to Update / Обновить
