### ISSUE TITLE
[User data] Manage user data in VM details sidebar

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#1461]
This issue covers the following requirements:
1. [REQ_VM_DTLS_003] A user should be able to view general information about VM in VM details sidebar
2. [REQ_VM_DTLS_053] A user must be able to view and edit user data in VM details sidebar 
3. [REQ_VM_DTLS_054] A user should be able to copy user data in VM details sidebar

Implement through POST-request.

*To provide PM with mockups*

**Comment by dron8552** [comment]
TO TEST:
REQ_VM_DTLS_003,
REQ_VM_DTLS_053,
REQ_VM_DTLS_054

**Comment by ershovaelena** [comment]
Includes #1460

**Comment by Nadya913** [comment]
1.  "Просмотреть" instead of “Посмотреть” in tooltip. 
![view](https://user-images.githubusercontent.com/33111683/52928475-7b558000-3372-11e9-9737-5be29b11a099.png)
2. "Отмена" instead of "Закрыть" for edit User data modal.
3. Different spaces between buttons Copy, Edit and Cancel.
![cancel](https://user-images.githubusercontent.com/33111683/52929529-5ca5b800-3377-11e9-8693-8140b8f9a64f.png)

**Comment by ershovaelena** [comment]
@dron8552 @Nadya913 considering the 4th fail: I agree, the exception added to the requirement REQ_VM_DTLS_054 (If No User Data, the copy button should be hidden)

**Comment by dron8552** [comment]
Fixed, except:
1 - now we have translate VIEW = Просмотреть, for all cases. We need to use this translation or rename it to "Посмотреть" for all cases.
2 - now spaces between buttons Copy, Edit and Cancel are the same, but it looks like different because buttons types are different

**Comment by Nadya913** [comment]
1. Copy button should be left aligned as for details error accordion for vm creation.  
![copy](https://user-images.githubusercontent.com/33111683/53314926-6b4e1b00-38f3-11e9-856c-ec252cedc384.png)
2. Still 2 scrolls appear for multiline User Data in Safari 12 (Mojave). 
![scroll](https://user-images.githubusercontent.com/33111683/53317003-8b360c80-38fc-11e9-8b64-18fef4faccfc.png)

**Comment by ershovaelena** [comment]
@Nadya913 @dron8552 a separate issue for changing "Просмотреть" to "Посмотреть" is created #1614
