### ISSUE TITLE
Attached ISO does not appear in VM sidebar

### ISSUE THREAD

**Issue by rennervo** [bwsw/cloudstack-ui#1468]
### Description
Attached ISO should always be displayed in the VM sidebar after attachment. However, it is not displayed there after reloading the page or after logout/login.

### Steps to reproduce

1. Open the sidebar of any VM on the "Storage" tab
2. Make sure that the ISO is not attached to the VM, otherwise detach
3. Attach new ISO to VM
4.1 Reload page
4.2 Log out and Log In
5. Return to the sidebar of the selected VM on the "Storage" tab

### Actual result
ISO value - "No medium attached"

### Expected result
ISO value - Name of ISO attached

### Environment

<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Chromium version XX
- [ ] Opera version XX
- [ ] Safari version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:
</code></pre>

### Connected REQ ID
REQ_VM_DTLS_023

**Comment by wowshakhov** [comment]
To test:
REQ_VM_DTLS_023
