### ISSUE TITLE
No available service offerings appears if go to instances/create

### ISSUE THREAD

**Issue by Nadya913** [bwsw/cloudstack-ui#1473]
### Description
If go to instances/create no available service offerings appears.

**Steps to reproduce:**

1. Login and navigate to instances/create

Actual result: no available service offerings appear
Expected result: default SO is selected (if predefined in config.json) or first SO is selected

### Environment

<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Chromium version XX
- [ ] Opera version XX
- [ ] Safari version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:
</code></pre>

### Connected REQ ID
[REQ_VM_CREATE_003]

### Screenshots
![noso](https://user-images.githubusercontent.com/33111683/49628101-ccf99a00-fa14-11e8-8937-369a3d127ec1.png)

**Comment by wowshakhov** [comment]
To test: 
REQ_VM_CREATE_003
Test that initial values for VM creation are loaded correctly in different scenarios:
- When we open VM creation via the floating action button 
- When we go directly to /instances/create
- With different network speeds
