### ISSUE TITLE
Table headers apear in VM sidebar if no elements in affinity group change dialog

### ISSUE THREAD

**Issue by Nadya913** [bwsw/cloudstack-ui#1474]
### Description
No 'No affinity group' row with checked radiobutton  appears in sidebar in case if no affinity group exists and not selected. 

**Steps to reproduce:**

1. Login 
2. Open sideber of any vm without aff group

Actual result: No results and empty table
Expected result: No table headers and 'no results' in top instead of headers

### Environment

<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Chromium version XX
- [ ] Opera version XX
- [ ] Safari version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:
</code></pre>

### Connected REQ ID
[REQ_VM_DTLS_006] 

### Screenshots
![aff](https://user-images.githubusercontent.com/33111683/49628626-c7ea1a00-fa17-11e8-981c-95110e1d09ac.png)

**Comment by rennervo** [comment]
Lack: 1

**Fields for adding new affinity groups are missing if there are no affinity groups created**

If there are no affinity groups created in the window, the headings of the Name and Type tables should not be displayed, and the fields for creation should be present here.

**Steps to reproduce:**
1. Make sure there are no affinity groups created
2. Go to a sidebar of any VM
3. Go to the window of selecting/creating an affinity group

**Actual result:** In the window, there is the name of the window, the inscription "No results"
**Expected result:** In the window, there is the name of the window, the fields for creating a new group, the inscription "No results".

**REQ_ID:**
REQ_VM_DTLS_006

**Screenshots:**
![2018-12-14 09-42-34](https://user-images.githubusercontent.com/26665398/49980095-9f689f80-ff84-11e8-9a2a-3b7c08001dbe.png)

**Comment by rennervo** [comment]
Tested on 1483
