### ISSUE TITLE
SO choice dialog in VM creation: open Fixed/Custom by default depending on availability of SOs

### ISSUE THREAD

**Issue by bwsw** [bwsw/cloudstack-ui#1477]
This issue covers the following requirements:
1. [REQ_VM_CREATE_003]A user must be able to set SO in VM creation 
2. [REQ_VM_DTLS_005] A user must be able to manage SO in VM details sidebar

**Comment by rennervo** [comment]
Lack: 1

**1) SO change unavailable from VM sidebar**

The SO change button is not available in the sidebar of the VM, regardless of the availability of SO for selecting and configuring settings.

Steps:
1. Make sure that the user has available SO for selection
2. Go to the sidebar of any VM

Actual result: The SO change button is unavailable for clicking, the "There are no service offering available" notification is displayed
Expected Result: The CO change button is available for clicking.

**2) Invalid notification text**

Change the text of the notice in about the absence of available SO

Actual result: Notification text "No offerings available" / “Нет доступных сервисных предложений”
Expected result: Notification text “There are no service offering available” / “Нет доступных вычислительных предложений”

**Comment by rennervo** [comment]
Tested on 1509 on simulator
