### ISSUE TITLE
Incorrect domain display when grouping by accounts

### ISSUE THREAD

**Issue by bwsw** [bwsw/cloudstack-ui#1479]
This issue covers the following requirement:
[REQ_ACCOUNT_LIST_003] A user should be able to group accounts

Only last segment of 'do/ma/in" is displayed, e.g. "in", not "do/ma/in", so it's impossible to track hierarchy. Must use domain 'path', not 'name'.

**Comment by ershovaelena** [comment]
To test: REQ_ACCOUNT_LIST_003

**Comment by rennervo** [comment]
Tested on 1524 (in simulator)
