### ISSUE TITLE
Edge 18 - Filters dropdowns are expanded 

### ISSUE THREAD

**Issue by Nadya913** [bwsw/cloudstack-ui#1486]
### Description
All the Filters dropdowns are expanded for whole window width.

**Steps to reproduce:**

1. Login 

Actual result: All Filters dropdowns are in the same row
Expected result: All the Filters dropdowns are expanded for whole window width in each row.

### Environment

<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Chromium version XX
- [ ] Opera version XX
- [ ] Safari version XX
- [ ] IE version XX
- [ X] Edge version 18

Others:
</code></pre>

### Connected REQ ID
REQ_VM_LIST_004

### Screenshots
![edge18.png](https://images.zenhubusercontent.com/59faba338a75884b9085bd93/0f84b0be-9da4-435a-8f31-de453c5db9d0)

**Comment by wowshakhov** [comment]
This is an Angular Material bug: https://github.com/angular/material2/issues/14406
