### ISSUE TITLE
Error in console for snapshots page

### ISSUE THREAD

**Issue by Nadya913** [bwsw/cloudstack-ui#1487]
### Description
Error in console for snapshots page.

**Steps to reproduce:**

1. Login 
2. Go to Snapshots

Actual result: Error: Uncaught (in promise): TypeError: e.getTime is not a function
TypeError: e.getTime is not a function
Expected result: No errors in console

### Environment

<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Chromium version XX
- [ ] Opera version XX
- [ ] Safari version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:
</code></pre>

### Connected REQ ID
REQ_SNAP_LIST_001

### Screenshots
![image.png](https://images.zenhubusercontent.com/59faba338a75884b9085bd93/09978bda-302a-4ada-9f36-b349aaf250d6)

**Comment by wowshakhov** [comment]
To test:
REQ_SNAP_LIST_001

**Comment by rennervo** [comment]
Tested on 1489
