### ISSUE TITLE
Disk offering label is cut after radiobutton selected

### ISSUE THREAD

**Issue by Nadya913** [bwsw/cloudstack-ui#1500]
### Description
Disk offering label is cut after radiobutton selected. The same for disk offering selection in VM creation.

### Steps to reproduce

1. Go to Storage and Resize disk
2. Select any disk offering and click on radibutton

### Actual result
Label is cut

### Expected result
Label is readable

### Environment

Others:
</code></pre>

### Connected REQ ID
REQ_VM_CREATE_012
REQ_STORAGE_LIST_015

**Comment by wowshakhov** [comment]
To test:
REQ_VM_CREATE_012
REQ_STORAGE_LIST_015
