### ISSUE TITLE
Account long first (more than 100 symbols) name are above the other labels in account sidebar

### ISSUE THREAD

**Issue by Nadya913** [bwsw/cloudstack-ui#1503]
### Description
Account long first (more than 100 symbols) name are above the other labels in account sidebar. 

### Steps to reproduce

1. Login and Go to Accounts
2. Click on develop acoount to expand the sidebar
3. Go to Users tab and expand the user

### Actual result
Account long first (more than 100 symbols) name are above the other labels

### Expected result
 Name are cut with ... as (last name)

### Connected REQ ID
REQ_ACCOUNT_DTLS_004
![accounts](https://user-images.githubusercontent.com/33111683/50272448-69d32300-046a-11e9-93e8-c326ac72af62.png)

**Comment by HeyRoach** [comment]
To test:
REQ_ACCOUNT_DTLS_004
