### ISSUE TITLE
No radiobutton for disk offering is selected in disk offering if data disk is creating

### ISSUE THREAD

**Issue by evgeniiamokhova** [bwsw/cloudstack-ui#1530]
### Description
Issue was verified only in Chrome.

### Steps to reproduce
1) Login by user
2) Go to Storage
3) Press Create Volume
4) Click Select button

### Actual result
No Disk offering is selected

### Expected result
The first disk offering is selected according to REQ_STORAGE_LIST_012

### Connected requirement IDs
[REQ_STORAGE_LIST_012] 

### Screenshots
![2019-01-18 11-12-20](https://user-images.githubusercontent.com/45107015/51365324-56bb7d80-1b12-11e9-852c-0af0b8dfe794.png)

**Comment by HeyRoach** [comment]
Test:

REQ_STORAGE_LIST_012
