### ISSUE TITLE
Login button is enabled when username and/or password are empty

### ISSUE THREAD

**Issue by evgeniiamokhova** [bwsw/cloudstack-ui#1534]
### Description
According requiments [REQ_LOGIN_001] for empty case of username and/or password Login button should be disabled. If no data was entered  in username and/or password inputs  login button is enabled. 

### Steps to reproduce
1) Go to login page
2) Press Tab button to leave username empty

### Actual result
Login button is enabled when Username or Password or both are not filled and empty

### Expected result
Login button should be disabled when Username or Password or both are empty
### Environment

<pre><code>
Browser:
- [х] Chrome version XX
- [х] Firefox version XX
- [х] Safari version XX
- [х] Opera version XX
- [ ] IE version XX
- [х] Edge version XX
</code></pre>

### Connected requirement IDs
[REQ_LOGIN_001]

### Screenshots
![2019-01-24 14-41-18](https://user-images.githubusercontent.com/45107015/51662511-9c7eb700-1fe6-11e9-8e16-b5009200943b.png)

**Comment by HeyRoach** [comment]
Test:
REQ_LOGIN_001

**Comment by HeyRoach** [comment]
@nikonov1996
 you should add description of fail

**Comment by nikonov1996** [comment]
@HeyRoach 
The fail repeats. Login button is enabled when Username or Password, or both, are not filled and empty.
