### ISSUE TITLE
VM filter errors in disk snapshots

### ISSUE THREAD

**Issue by rennervo** [bwsw/cloudstack-ui#1541]
### 1) The item "No VM" is not in the filter list
According to REQ_SNAP_LIST_003 - the first item in the list of filtering by VM should be the item "No VM". When it is selected, only snapshots that do not have active VMs should be displayed.

**Steps to reprosuced:**
1. Go to the "Snapshots" section.
2. Open the filter by VM in the "Volume" section

**Actual result:** In the list there is no item "No VM"
**Expected result:** "No VM" item is on the list

### 2) VMs that do not have snapshots VM are present in the filtering list
According to REQ_SNAP_LIST_003 - only VMs with VM snapshots should be present in the filtering list.

**Steps to reprosuced:**
1. Create a new VM
2. Go to the section "Snaps" in the section "Volum"
3. Open the filter on VM

**Actual result:** In the filtering list there is a new VM that does not have VM snapshots
**Expected result:** There is no new VM in the filtering list.

### Environment

<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] Opera version XX
- [ ] Chromium version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:
</code></pre>

### Connected requirement IDs
REQ_SNAP_LIST_003

**Comment by HeyRoach** [comment]
About the second one:

_2) VMs that do not have snapshots VM are present in the filtering list_
Why are you talking about Vm snapshot?
Here should be a VM with volume which has a snap.

**Comment by Nadya913** [comment]
Empty value VM appears in list.
![empty](https://user-images.githubusercontent.com/33111683/51957348-e7347f00-247d-11e9-8d95-714c0e79e069.png)
