### ISSUE TITLE
Accordion slams when the module with the Accordion opening

### ISSUE THREAD

**Issue by evgeniiamokhova** [bwsw/cloudstack-ui#1547]
### Description
When opening a module with an accordion, the accordion is opened for a few milliseconds, then it closes. Inside the accordion, there is a lot of empty space.  This is repeated when choosing DO for Volume Creation and when opening a modal with some error. 

### Steps to reproduce
1) Login by user
2) Go to Storage
3) Click Create volume
4) Click Select DO

### Actual result
Accordion is opened for a few milliseconds

### Expected result
For opening the modal the accordion is closed

### Environment

<pre><code>
Browser:
- [x] Chrome version XX
- [x] Firefox version XX
- [x] Safari version XX
- [x] Opera version XX
- [x] IE version XX
- [x] Edge version XX

</code></pre>

### Connected requirement IDs
REQ_STORAGE_LIST_012

### Screenshots
![2019-01-31 09-20-21](https://user-images.githubusercontent.com/45107015/52028894-722b7d00-2543-11e9-83d3-e5ce8e78c58a.png)
![2019-01-31 09-29-34](https://user-images.githubusercontent.com/45107015/52028897-75266d80-2543-11e9-9383-ead491c34838.png)
<img width="568" alt="2019-01-30 14 42 45" src="https://user-images.githubusercontent.com/45107015/52252215-c2d01b00-2933-11e9-883e-e443518f457b.png">

**Comment by dron8552** [comment]
TO TEST:
REQ_STORAGE_LIST_012

**Comment by dron8552** [comment]
I hide content on loading accordion, but it can't be fully fixed because of https://github.com/angular/material2/issues/13870
