### ISSUE TITLE
Pulse - Remove restriction of "100" for shift

### ISSUE THREAD

**Issue by Nadya913** [bwsw/cloudstack-ui#1559]
### Description
 - Login by user
 - Press Pulse in action box for any VM
 - Input all filters (1 day, 1 hour for example) and set 100 value for shift

### Actual result
Shift buttons are inside the chart, "100" is a max number if enter by increase button

### Expected result
 1. Shift buttons are outside the chart if no data appears in chart
 2. The only restriction for "shift" is non negative integer value
### Screenshots
![shift.png](https://images.zenhubusercontent.com/59faba338a75884b9085bd93/eb2d07c0-6864-4f99-85f1-82f584fdad9a)

### Connected requirements:
REQ_PLS_005, REQ_PLS_010, REQ_PLS_015

**Comment by ershovaelena** [comment]
Connected requirements: 
- REQ_PLS_005
- REQ_PLS_006
- REQ_PLS_009
- REQ_PLS_013
- REQ_PLS_014
- REQ_PLS_017
- REQ_PLS_021
- REQ_PLS_022
- REQ_PLS_025

**Comment by bwsw** [comment]
Not a bug. Lack of stats.

**Comment by Nadya913** [comment]
> Not a bug. Lack of stats.

Ok, just needed to fix the layout of the shift button in charts.

**Comment by bwsw** [comment]
@Nadya913 I don't get what to fix. It's normal if no stats. The system shouldn't care about that.

**Comment by Nadya913** [comment]
@bwsw @bwsw-Andrey-Andreev 
The shift value input has the restriction in UI as maximum 100, the value more than 100 can't be set by increase button. 
But you can input the value more than 100 by the keyboard.
Also, the visible size is for 5 digits.
![max](https://user-images.githubusercontent.com/33111683/52328376-fbe6b900-2a21-11e9-8e84-f85f585786b1.png)

Question: what the restriction we have for shift value?

**Comment by ershovaelena** [comment]
@bwsw  Please see the comment above. What is preferable?

**Comment by ershovaelena** [comment]
@Nadya913 @bwsw-Andrey-Andreev @evgeniiamokhova @nikonov1996 discussed with PO:
remove the constraint of 100 for the shift, a user should be able to enter any *non negative integer value*

**Comment by dron8552** [comment]
TO TEST:
REQ_PLS_005,
REQ_PLS_010,
REQ_PLS_015

**Comment by evgeniiamokhova** [comment]
1) Actual result: When enter numbers and point in input, system clear field
Expected result: When enter numbers and point in input, system ignore point  and leave only numbers according to exception in REQ_PLS_005, REQ_PLS_010, REQ_PLS_015
2) Actual result: When enter plus and numbers in input, system don't change value on 0
Expected result: When enter plus in input, system change value on 0 according to REQ_PLS_005, REQ_PLS_010, REQ_PLS_015
3) Actual result: When enter negative number in input system change value on 0, but negative value is saved on other tabs 
Expected result: When enter negative number in input system change value on 0, values on all tabs should be the same according to REQ_PLS_005, REQ_PLS_010, REQ_PLS_015

**Comment by dron8552** [comment]
Fixed. It should work like Session timeout input in the Settings. But if this behavior isn't correct, create a separate ticket, please.
