### ISSUE TITLE
Settings fields display bug

### ISSUE THREAD

**Issue by bwsw** [bwsw/cloudstack-ui#156]
![Settings](https://box.bw-sw.com/f/76a7fcd24e/?raw=1)

1. First day of the week field
2. Language field

**Comment by mdbardina** [comment]
Key and Secret Key don't display too
![cloudstack ui - google chrome_014](https://cloud.githubusercontent.com/assets/25217218/26478923/d4092916-41f9-11e7-9f00-bec7991190f5.png)
