### ISSUE TITLE
Pulse  - no russian localization for filter values, charts

### ISSUE THREAD

**Issue by Nadya913** [bwsw/cloudstack-ui#1562]
### Description
No russian localization for filter values, charts for all the tabs and no support for 24 time format.

### Steps to reproduce
 - Login by user
 - Press Pulse in action box for any VM

### Actual result
Filter Range values for Russian/English: 15m, 30m, 1h, 2h, 4h, 12h, 1d, 1w, 1month.
No russian localization for Charts: dimensions, Day of week in tooltip, monthes.
No support for 24 hour time in chart.

### Expected result
1.   Order and values for filters should be according to the lists below.

Range  filter values:
15m / 15 мин
30m / 30 мин
1h / 1 ч
2h / 2 ч
4h / 4 ч
12h / 12 ч
1d / 1 день
1w / 1 нед
30d / 30 дн

Aggregation filter values:
1m / 1 мин
5m / 5 мин
15m / 15 мин
30m / 30 мин
1h / 1 ч
4h / 4 ч
1d / 1 д

Shift filter values: 
m / мин
h / час
d / день

2.  Russian localization for Charts: dimensions in russian,  Day of week in tooltip in Russian, monthes in Russian.
No support for 24 hour time in chart. @dron8552 please check out if localization is possible. If yes, then requirements will be changed. 

### Connected requirement IDs
REQ_PLS_003
REQ_PLS_004
REQ_PLS_005
REQ_PLS_008
REQ_PLS_009
REQ_PLS_010
REQ_PLS_013
REQ_PLS_014
REQ_PLS_015
REQ_PLS_019

### Screenshots
![russian](https://user-images.githubusercontent.com/33111683/52320175-70a8fb80-2a00-11e9-86c6-c2e590cab5b4.png)
![month](https://user-images.githubusercontent.com/33111683/52329986-c5f80380-2a26-11e9-92af-3b4fa551184f.png)

**Comment by dron8552** [comment]
TO TEST:
REQ_PLS_003
REQ_PLS_004
REQ_PLS_005
REQ_PLS_008
REQ_PLS_009
REQ_PLS_010
REQ_PLS_013
REQ_PLS_014
REQ_PLS_015
REQ_PLS_019

**Comment by nikonov1996** [comment]
@dron8552  is it possible to translate month, day of the week and hour on the chart? Can it be fixed or it's not a bug? because year is translated. 
![image](https://user-images.githubusercontent.com/39374425/52926234-835bf280-3367-11e9-83cf-480cdce9c620.png)

**Comment by nikonov1996** [comment]
@dron8552 
1. log in by user
2. press "Pulse" in action box for running VM
3. in filters choose "1 w" in Range 
4. hover mouse pointer over a chart point

**Comment by dron8552** [comment]
run tests

**Comment by nikonov1996** [comment]
@dron8552 
1) In filters, value "4h" in the "Range" list is not translated
Steps to reproduce:
1. Login by user
2. Press "Pulse" in action box for running VM
3. Click filter "Range" 
![image](https://user-images.githubusercontent.com/39374425/52944355-ccc93380-33a1-11e9-89c4-d60ebe3cf6ea.png)

2) In tooltip, aggregation value is not translated
Steps to reproduce:
1. Log in by user
2. Press "Pulse" in action box for running VM
3. Hover mouse pointer over a chart point
![image](https://user-images.githubusercontent.com/39374425/52944597-5aa51e80-33a2-11e9-8521-0e042c55845b.png)

**Comment by nikonov1996** [comment]
@dron8552  
If the input "Range" set to "3ч" then:

1) Values in field "Aggregation" are not translated 
     Steps to reproduse:
       1. Login by user
       2. Press "Pulse" in action box for running VM
       3. Set value "3 ч" in filter input "Range"
![image](https://user-images.githubusercontent.com/39374425/53219229-caacf080-3691-11e9-8479-ca9f84ccdbde.png)

2) On charts in all tabs, aggregation values in tooltip aren't translated and in "ЦПУ/ОЗУ" and "Диск" tabs aggregation values in uppercase.
      Steps to reproduse:
       1. Login by user
       2. Press "Pulse" in action box for running VM
       3. Set value "3 ч" in filter input "Range"
       4. Hover mouse pointer over a chart point
![image](https://user-images.githubusercontent.com/39374425/53219437-8837e380-3692-11e9-8003-ec5590ce5110.png)
![image](https://user-images.githubusercontent.com/39374425/53219466-a1409480-3692-11e9-8ff4-82c3fa292d79.png)
![image](https://user-images.githubusercontent.com/39374425/53219491-b61d2800-3692-11e9-918b-2867e3383312.png)

**Comment by dron8552** [comment]
@ershovaelena There is no 3h range in requirements, please add.
I've already added it to the code.
