### ISSUE TITLE
Pulse  - layout filter and chart issues

### ISSUE THREAD

**Issue by Nadya913** [bwsw/cloudstack-ui#1564]
### Description
There are some design issues as for screenshots.

### Steps to reproduce
-  Login by user
-  Resize the window for half screen
-  Press Pulse in action box for Resource Limits VM, go to all the tabs

### Actual result
Dimensions cross the chart. Filter and chart in the same line. The tooltip is cut.

### Expected result
Filters are in separate line. Each chart is on a separate line. Dimensions don't cross the chart. The tooltip isn't cut.

### Connected requirement IDs
REQ_PLS_006, REQ_PLS_011, REQ_PLS_016, REQ_PLS_007, REQ_PLS_019

### Screenshots
![chart3](https://user-images.githubusercontent.com/33111683/52322941-b5875f00-2a0d-11e9-8fa9-1392af93ee83.png)
![chart2](https://user-images.githubusercontent.com/33111683/52322942-b5875f00-2a0d-11e9-9d02-83b3e4e6c3ac.png)
![chart1](https://user-images.githubusercontent.com/33111683/52322943-b61ff580-2a0d-11e9-9145-a5f5f8f5f844.png)
![nic](https://user-images.githubusercontent.com/33111683/52322952-bb7d4000-2a0d-11e9-9099-35ec6bb4a641.png)
![tooltip](https://user-images.githubusercontent.com/33111683/52391674-0f049200-2ad1-11e9-87c4-e655ddd3050f.png)

**Comment by dron8552** [comment]
TO TEST:
REQ_PLS_024
REQ_PLS_010
REQ_PLS_003

**Comment by ershovaelena** [comment]
To test: REQ_PLS_006, REQ_PLS_011, REQ_PLS_016, REQ_PLS_007, REQ_PLS_019

**Comment by evgeniiamokhova** [comment]
Lack:1
### Drop-down NIC on the separate line in Network when Safari is fullscreen

Actual result: Drop-down NIC on the separate line in Network when Safari is fullscreen
Expected result: Drop-down NIC in line with other filters in Network when Safari is fullscreen
![2019-02-18 09-15-08](https://user-images.githubusercontent.com/45107015/52924572-e47fc800-335f-11e9-908d-31dfb049aeac.png)

**Comment by evgeniiamokhova** [comment]
@dron8552 Is it possible to fix?

**Comment by dron8552** [comment]
Yes, it is possible, but it will take a lot of time. @ershovaelena should I fix it?

**Comment by ershovaelena** [comment]
@dron8552 @evgeniiamokhova Fail is moved to a separate task #1594. This issue can be resolved.
