### ISSUE TITLE
Pulse  - dimension for Ram chart is Mib instead of MB

### ISSUE THREAD

**Issue by Nadya913** [bwsw/cloudstack-ui#1565]
### Description
According to backend response example, RAM is in MB but in the chart, Mib appears.  1 MiB = 1.048576 MB
Ram response (MB):
{
    measurement: ram,
    uuid: 550e8400-e29b-41d4-a716-446655440000,
    range: 15m,
    aggregation: 1m,
    shift: 1d,
    result: 
    [
        {
            ram: 3500
        },
        {
            ram: 3300
        },
        {
            ram: 3600
        }
    ]
}

### Steps to reproduce
-  Login by user
-  Resize the window for half screen
-  Press Pulse in action box for any VM

### Actual result
Mib dimension is used

### Expected result
Сhart dimension should be in MB.

### Connected requirement IDs
REQ_PLS_006

### Screenshots
![ram](https://user-images.githubusercontent.com/33111683/52390306-43288480-2aca-11e9-86dd-bf9e47c5578c.png)

**Comment by dron8552** [comment]
TO TEST:
REQ_PLS_006
