### ISSUE TITLE
Pulse - filter values are the same for different users in the one account

### ISSUE THREAD

**Issue by nikonov1996** [bwsw/cloudstack-ui#1566]
### Description
Filter values must be different for different users in the same account. 

### Steps to reproduce

1. Login by the first user in account
2. Press "Pulse" in action box for running VM  
3. Change filter values 
5. Log out
6. Login by the second user in the same account
7. Press "Pulse" in action box for running VM

### Actual result
Filter values of the second user are the same as filter values of the first user in the same account.

### Expected result
Filter values of the second user are not changed. Filter values for different users in the same account are different.

Browser:
- [x] Chrome version XX
- [x] Firefox version XX
- [x] Safari version XX
- [x] Opera version XX
- [x] IE version XX
- [x] Edge version XX

### Connected requirement IDs
[REQ_PLS_012]
[REQ_PLS_013]
[REQ_PLS_014]
[REQ_PLS_015]

### Screenshots
![case1](https://user-images.githubusercontent.com/39374425/52399730-a4af1a00-2aef-11e9-9d6e-e279e3f7bf30.png)
![case2](https://user-images.githubusercontent.com/39374425/52399732-a4af1a00-2aef-11e9-88c5-6fc0045537e5.png)
![case3](https://user-images.githubusercontent.com/39374425/52399733-a547b080-2aef-11e9-909f-e2b174086805.png)

**Comment by bwsw** [comment]
Usually one account = one user. Change to minor.
