### ISSUE TITLE
VM password problem with Access helpers

### ISSUE THREAD

**Issue by bwsw** [bwsw/cloudstack-ui#1567]
### Description

During the VM creation password save selected but when access VM is clicked, the password is "Not Set".

### Steps to reproduce

Create VM, when created click to save the password.
In the final dialog click "Access VM", it shows that the password is not set.

In tags, the password is set. When "Access VM" dialog is selected from the context menu, it shows that the password exists.

### Actual result

No password exist when Access helper is called at the end of VM creation.

### Expected result

If the password is saved, then it must be accessible.

### Environment

Template: VestaCP Nginx+PHP-FPM
Browser: Chrome / Linux
Test Acct: cloud2test15569

<pre><code>
Browser:
- [x] Chrome version 69.0.3497.100
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] Opera version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

### Connected requirement IDs
REQ_VM_CREATE_021, REQ_VM_CREATE_028, REQ_VM_LIST_017

**Comment by bwsw** [comment]
@ershovaelena @Nadya913 important

**Comment by dron8552** [comment]
TO TEST:
REQ_VM_CREATE_021,
REQ_VM_CREATE_028, 
REQ_VM_LIST_017
