### ISSUE TITLE
Default Language Problem

### ISSUE THREAD

**Issue by bwsw** [bwsw/cloudstack-ui#1568]
### Description

When entered into 'cloud2test15569', ui was in English, but in settings was 'Russian', after clicking to 'English' and back to 'Russian', ui became 'Russian'.

### Steps to reproduce

See above

### Actual result

Wrong locale

### Expected result

Correct locale by default

### Environment

<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] Opera version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

### Connected requirement IDs
REQ_SET_010

**Comment by dron8552** [comment]
TO TEST:
REQ_SET_010
