### ISSUE TITLE
No notification about copying API logs in snackbar when VM creation error

### ISSUE THREAD

**Issue by evgeniiamokhova** [bwsw/cloudstack-ui#1569]
### Description
No notification “Copied successfully” / “Успешно скопировано” about copying API logs in snackbar when VM creation error

### Steps to reproduce
1) Login by user
2) Click Create VM
3) Enter VM display name
4) Go to tab Advanced
5) Enter VM host name "123"
6) Click Create
7) Open drop-down Details
8) Click Copy

### Actual result
No notification "Copied successfully" in snackbar when API logs are copied

### Expected result
Notification "Copied successfully" appears  in snackbar when API logs are copied accordingly with REQ_VM_CREATE_025

### Environment

<pre><code>
Browser:
- [ x ] Chrome version XX
- [ x ] Firefox version XX
- [ x ] Safari version XX
- [ x ] Opera version XX
- [ x ] IE version XX
- [ x ] Edge version XX
</code></pre>

### Connected requirement IDs
REQ_VM_CREATE_025

**Comment by dron8552** [comment]
TO TEST:
REQ_VM_CREATE_025
