### ISSUE TITLE
Button "Request resources" looks pressed after closing the modal

### ISSUE THREAD

**Issue by nikonov1996** [bwsw/cloudstack-ui#1570]
### Description
Button "Request resources" looks pressed after closing the "Request resources" modal.

### Steps to reproduce
1. Login by user
2. Click button "Request resources"
3. Click button "Cancel"

### Actual result
Button "Request resources" looks pressed.

### Expected result
Button "Request resources" looks nonpressed.

### Environment

<pre><code>
Browser:
- [x] Chrome version XX
- [x] Firefox version XX
- [x] Safari version XX
- [x] Opera version XX
- [x] IE version XX
- [x] Edge version XX

### Screenshots
![image](https://user-images.githubusercontent.com/39374425/52458379-987b9900-2b91-11e9-8e97-59fa2176121e.png)

**Comment by Nadya913** [comment]
Not a bug
