### ISSUE TITLE
HTTP Helper wrong window style

### ISSUE THREAD

**Issue by bwsw** [bwsw/cloudstack-ui#1576]
### Description

HTTP helper opens in a modal-like window, must open if full-featured tab or window. for SSH/VNC current way is OK.

### Steps to reproduce

Create VM from a template with HTTP helper enabled. Click Access VM for HTTP helper.

### Actual result

Open in the modal control window.

### Expected result

Must open in normal reusable window or tab.

### Connected requirements:
REQ_VM_LIST_021

**Comment by ershovaelena** [comment]
@bwsw-Andrey-Andreev please also check MAC OS - helpers in all 3 tabs VNC, SSH, HTTP open in separate browser tab, but SSH, HTTP should open in modal as it works now for windows

**Comment by dron8552** [comment]
@ershovaelena I can't reproduce the bug in MAC OS using the `browserstack`, need to create a separate issue.

**Comment by dron8552** [comment]
TO TEST:
REQ_VM_LIST_019,
REQ_VM_LIST_020,
REQ_VM_LIST_021

**Comment by dron8552** [comment]
@nikonov1996 you are right, thanks.
