### ISSUE TITLE
User tags updated after user logged in

### ISSUE THREAD

**Issue by dron8552** [bwsw/cloudstack-ui#1578]
### Description
When the user changed user-tags and log out then log in again (or using other credentials), the application sends requests to change those user-tags again. 

### Steps to reproduce
1. Log in
2. Change user-tags in settings (ex. language or theme)
3. Log out
4. Log In by the same user or another
- if you logged in by another user you can see language or theme changing and see requests like `api?command=deleteTags...` and `command=createTags` in the console.
- if you logged in by the same user just watch the console

### Actual result
User tags were changed

### Expected result
User tags should not be changed

### Environment
Browser:
- [x] Chrome version XX
- [x] Firefox version XX
- [x] Safari version XX
- [x] Opera version XX
- [x] IE version XX
- [x] Edge version XX

### Connected requirements:
All functions based on user tags are involved. See [Wiki: Supported tags](https://github.com/bwsw/cloudstack-ui/wiki/Tags).

REQ_VM_LIST_022, REQ_STORAGE_LIST_013, REQ_VM_LIST_016, REQ_SET_003, REQ_SET_011, REQ_SET_010, REQ_SET_002, REQ_SET_012, REQ_SET_013, REQ_GEN_007, REQ_SET_009, REQ_VM_CREATE_003, REQ_VM_DTLS_005, REQ_LOGS_014, REQ_LOGS_019 and the option to show/hide system tags in all details sidebars ("csui.user.show-system-tags")

**Comment by rennervo** [comment]
Tested on 1579
