### ISSUE TITLE
Can't see the selected entity in the Firewall rules for VM window

### ISSUE THREAD

**Issue by mdbardina** [bwsw/cloudstack-ui#158]
In the Firewall rules for VM window when selecting a type and protocol, the selected entities do not appear. See the screenshot.
But you can create a rule. And there will be the correct parameters (which you chose)
![1_004](https://cloud.githubusercontent.com/assets/25217218/26434341/7bc540fe-4132-11e7-8502-d08c43d01fd2.png)
![cloudstack ui - google chrome_003](https://cloud.githubusercontent.com/assets/25217218/26434308/403aaf9c-4132-11e7-9ee4-7b850659220c.png)
![_002](https://cloud.githubusercontent.com/assets/25217218/26434486/3e3f6f4c-4133-11e7-9c7d-ed3d89b45d2e.png)

**Comment by wowshakhov** [comment]
done in #156
