### ISSUE TITLE
User can log in, if entered a few spaces after login

### ISSUE THREAD

**Issue by nikonov1996** [bwsw/cloudstack-ui#1588]
### Description
If enter a few spaces after the correct login and enter correct password, user log in system.

### Steps to reproduce
1. Enter correct login and few spaces in input field "login"
2. Enter correct password
3. Click "Login" button

### Actual result
User log in.

### Expected result
Login does not occur. The system shows a message in the snackbar "Incorrect username or password” /"Неверный пользователь или пароль”

### Connected requirement IDs
[REQ_LOGIN_001] 

### Screenshots
![00101](https://user-images.githubusercontent.com/39374425/52786939-e9f2bf00-308e-11e9-9947-7554c2133a40.jpg)
![00202](https://user-images.githubusercontent.com/39374425/52786941-e9f2bf00-308e-11e9-9a1c-ba0685b4f8e0.jpg)

**Comment by dron8552** [comment]
@Nadya913 @nikonov1996 @evgeniiamokhova @ershovaelena From UI we send username with spaces, CloudStack trims it by itself.
