### ISSUE TITLE
Button "Create"  is enabled when mandatory input field "Name" is not filled in Snapshot creation

### ISSUE THREAD

**Issue by nikonov1996** [bwsw/cloudstack-ui#1589]
### Description
Button "Create"  is enabled when mandatory input field "Name" is not filled in snapshot creation modal dialog (Storage section)

### Steps to reproduce
1. Login by user
2. Go to Storage section
3. Click "Take a snapshot"
4. Delete values in input "Name"

### Actual result
Button "Create" is enabled

### Expected result
Button "Create" is disabled

### Connected requirement IDs
[REQ_STORAGE_LIST_006] 

### Screenshots
![5xuxs7d9cvm](https://user-images.githubusercontent.com/39374425/52787518-aac56d80-3090-11e9-85d4-3513071709ed.jpg)

**Comment by dron8552** [comment]
TO TEST: 
[REQ_STORAGE_LIST_006]

**Comment by rennervo** [comment]
Tested on 1665
