### ISSUE TITLE
Error text appears in English when Russian langauge is set 

### ISSUE THREAD

**Issue by evgeniiamokhova** [bwsw/cloudstack-ui#1593]
### Description
When Error appears error text on English when Russian is setted

### Steps to reproduce
Login by user
Go to Settings and set Russian language
### 1
1. Go to Image
2. Click create ISO
3. Enter URL (example “https://yandex.ru”)
4. Fill other fields
5. Click Create(Image 1)
### 2
1. Go to VM sidebar
2. Click Create VM Snapshot
3. Go to Storage in VM sidebar
4. Click Create Snapshot in action box of disk
5. Go to Snapshot
6. Go to tab Disk
7. Click Revert disk to snapshot in action box(image 2)
### 3
1. Go to Storage in VM sidebar
2. Click Create Snapshot in action box of disk
3. Go to Snapshot
4. Click Create volume in active box of snapshot
5. Enter name and click create in dialog
6. Go to Storage
7. Click Attach in action box in created volume
8. Choose VM and click Attach in dialog(image 3)
### 4
1. Go to Storage in VM sidebar
2. Click Create Snapshot in action box of disk
3. Click Destroy in action box of VM
4. Click Yes in dialog
5. Go to Snapshot
6. Click Revert volume to snapshot in action box in snapshot of destoyed VM
7. Click Yes in dialog(image 4)
### 5
1. Go to SHH keys
2. Click Create
3. Enter Name and Public Key ”123”
4. Click Create(image 5)
### 6
1. Go to VM
2. Click Destroy in action box of VM
3. Go to Storage
4. Click Create volume
5. Enter data and click create
6. Click Attach in action box in created volume
7. Choose VM and click Attach in dialog(image 6)

### Actual result
Error text on English when the system on Russian

### Expected result
Error text should be on Russian when the system on Russian

### Environment
<pre><code>
Browser:
- [ x ] Chrome version XX
- [ x ] Firefox version XX
- [ x ] Safari version XX
- [ x ] Opera version XX
- [ x ] IE version XX
- [ x ] Edge version XX
</code></pre>

### Connected requirement IDs
REQ_GEN_005
REQ_IMAGE_LIST_006 (1)
REQ_IMAGE_LIST_007 (2)
REQ_STORAGE_DTLS_009 (2) (4)
REQ_VM_DTLS_017 (2) (4)
REQ_STORAGE_LIST_009 (3) (6)
REQ_SSH_LIST_004 (5)

### Screenshots
![2019-02-13 17-24-21](https://user-images.githubusercontent.com/45107015/52927609-0e3feb80-336e-11e9-9fdc-b1e70ddbb375.png)
![2019-02-13 17-45-39](https://user-images.githubusercontent.com/45107015/52927682-53641d80-336e-11e9-8bb6-f7b298ed4bca.png)
![2019-02-14 11-11-19](https://user-images.githubusercontent.com/45107015/52927691-5bbc5880-336e-11e9-850e-07f9a398a082.png)
![2019-02-14 11-59-22](https://user-images.githubusercontent.com/45107015/52927743-97efb900-336e-11e9-8c49-550ba7801770.png)
![2019-02-14 12-13-37](https://user-images.githubusercontent.com/45107015/52927755-a047f400-336e-11e9-8fdc-8d67dfd7503b.png)
![2019-02-18 11-03-16](https://user-images.githubusercontent.com/45107015/52927777-b48bf100-336e-11e9-8d4b-d101a30a13d6.png)

**Comment by dron8552** [comment]
:

**Comment by dron8552** [comment]
TO TEST:
REQ_IMAGE_LIST_006
REQ_IMAGE_LIST_007
REQ_STORAGE_DTLS_009
REQ_VM_DTLS_017
REQ_STORAGE_LIST_009
REQ_SSH_LIST_004

**Comment by nikonov1996** [comment]
@dron8552  Error text not translated. [REQ_STORAGE_LIST_009]
Steps to reproduce:
1. Go to VM
2. Click Destroy in action box of VM
3. Go to Storage
4. Click Create volume
5. Enter data and click create
6. Click Attach in action box in created volume
7. Choose VM and click Attach in dialog
![error text not translated disk created from the snapshot disk](https://user-images.githubusercontent.com/39374425/53391060-c18c8e00-39c7-11e9-9a3a-7f38fe659fdd.png)
