### ISSUE TITLE
Type Error 'memory' of undefined appears if refresh the vm sidebar page

### ISSUE THREAD

**Issue by Nadya913** [bwsw/cloudstack-ui#1595]
### Description
Error appears in console if refresh the vm sidebar page: 
for main.8b3d15f2c9d16bb1d18f.js:1 ERROR TypeError: Cannot read property 'memory' of undefined

### Steps to reproduce
 - Login and open vm sidebar
 - Press f5 

### Actual result
Error appears in console if refresh the vm sidebar page: 
for main.8b3d15f2c9d16bb1d18f.js:1 ERROR TypeError: Cannot read property 'memory' of undefined

### Expected result
No console errors

### Environment

<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] Opera version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:
</code></pre>

### Screenshots
![error.png](https://images.zenhubusercontent.com/59faba338a75884b9085bd93/9cab572e-8f68-475a-9ae0-1cd924d89b2e)

**Comment by dron8552** [comment]
TO TEST: 
REQ_VM_DTLS_003,
REQ_VM_DTLS_005

**Comment by nikonov1996** [comment]
@dron8552 
1) VM sidebar does not display elements and information (empty field) after statistics update:
Steps to reproduce:
1. Login by user
2. Open VM sidebar
3. Click "Refresh" button in "Statistics"
![2019-02-28 12-20-20](https://user-images.githubusercontent.com/39374425/53542933-4a840080-3b53-11e9-8d5d-e3bf4a7f0456.png)

2) VM sidebar does not display elements and information (empty field) after updating values in " Service offering"
Steps to reproduce:
1. Login by user
2. Open VM sidebar
3. Click button "Change" in "Service offering"
4. Change any value in "Custom offering" and click "Confirm"
5. Click "Change" 
![2019-02-28 12-19-18](https://user-images.githubusercontent.com/39374425/53542938-51127800-3b53-11e9-8b6e-6cdb384e152c.png)

**Comment by ershovaelena** [comment]
@bwsw-Andrey-Andreev please also fix here the following: "add" (+) button for secondary IP is absent in Network tab of VM details (req. REQ_VM_DTLS_026, additional description)
