### ISSUE TITLE
Pulse - values in the "Range" filter list are not sorted in ascending order

### ISSUE THREAD

**Issue by nikonov1996** [bwsw/cloudstack-ui#1596]
### Description
Values in "Range" filter list must be sorted in ascending order.

### Steps to reproduce
1. Login by user
2. Press Pulse in action box for any running VM
3. Click filter "Range"

### Actual result
List not sorted in ascending order.

### Expected result
List sorted in ascending order.

### Connected requirement IDs
[REQ_PLS_003]
[REQ_PLS_008]
[REQ_PLS_013]

### Screenshots
![image](https://user-images.githubusercontent.com/39374425/52946606-f89ae800-33a6-11e9-9d89-4a72ba8dc6ea.png)

**Comment by Nadya913** [comment]
Dublicate of #1562
