### ISSUE TITLE
Pulse - dimensions cross the first chart in Network and Disk tabs

### ISSUE THREAD

**Issue by evgeniiamokhova** [bwsw/cloudstack-ui#1597]
### Description
Dimensions cross the first chart in Network and Disk tabs when there are large dimensions

### Steps to reproduce
1) Login by user
2) Press Pulse in action box of VM
3) Go to Network tab 
4) Fill in data (for example Range = 30m, Aggregation = 1m, Shift = 0m)

### Actual result
Dimensions cross the first chart

### Expected result
Dimensions don't cross the first chart 

### Environment

<pre><code>
Browser:
- [x] Chrome version XX
- [x] Firefox version XX
- [x] Safari version XX
- [x] Opera version XX
- [x] IE version XX
- [x] Edge version XX
</code></pre>

### Connected requirement IDs
REQ_PLS_011

### Screenshots
![2019-02-19 10-57-40](https://user-images.githubusercontent.com/45107015/52989446-ff247080-3435-11e9-8787-c962bf102df2.png)
![2019-02-19 14-25-39](https://user-images.githubusercontent.com/45107015/52997179-5afcf280-3452-11e9-815a-2d326c59f677.png)

**Comment by Nadya913** [comment]
Also issue appers for disk chart, add the screenshot
