### ISSUE TITLE
No dialog for save password for all vms if tag csui.user.save-password-for-all-vms is deleted

### ISSUE THREAD

**Issue by Nadya913** [bwsw/cloudstack-ui#1599]
### Description
No dialog for saving the password for all VMs if tag csui.user.save-password-for-all-vms is deleted. This dialog appears if the page is refreshed after the deletion.

### Steps to reproduce
- Log in and go to Accounts/Settings/User tags
- Delete csui.user.save-password-for-all-vms tag
- Go to VM
- Create new VM with Template (Password enabled: for example, debian-9-np-nolvm-10gb)
- Press Create and wait for the deployment
- Press Save for password

### Actual result
No dialog for save password for all vms 

### Expected result
Dialog for save password for all vms is opened

### Environment

<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] Opera version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:
</code></pre>

### Connected requirement IDs
REQ_VM_CREATE_021
REQ_VM_LIST_016
REQ_SET_003

**Comment by dron8552** [comment]
TO TEST:
REQ_VM_CREATE_021
REQ_VM_LIST_016
REQ_SET_003
Also? after the tag will be deleted it will be restored by default (if it exists)
