### ISSUE TITLE
When edit VM description edit field is displayed bad way

### ISSUE THREAD

**Issue by bwsw** [bwsw/cloudstack-ui#160]
- Description should not have 3 lines, it looks weird. Make one line, and if description text exceeds this line, than expand it. 
- Add "edit" button (pencil) as for all other sections on the left side. When clicking this button, editing opens (no modal  
windows)
- Add "save" button on the right side

![See a screenshot](https://box.bw-sw.com/f/08c652b809/?raw=1)

**Comment by ershovaelena** [comment]
TBD in #184
