### ISSUE TITLE
Empty space inside accordion in error modal dialog

### ISSUE THREAD

**Issue by evgeniiamokhova** [bwsw/cloudstack-ui#1600]
### Description
Empty space inside accordion in error modal appears after error with API logs

### Steps to reproduce
1) Login by user
2) Click Create VM 
3) Enter VM name
4) Go to tab "Advanced"
5) Enter host name "123"
6) Click "Create" button
7) Go to SSH keys section
8) Click "Create SSH key"
9) Enter name"1" and public key "1"
10) Click "Create"
11) Open accordion in error modal dialog

### Actual result
Empty space in accordion in error modal dialog

### Expected result
No empty space in accordion in error modal dialog

### Environment
<pre><code>
Browser:
- [x] Chrome version XX
- [x] Firefox version XX
- [x] Safari version XX
- [x] Opera version XX
- [x] IE version XX
- [x] Edge version XX
</code></pre>

### Connected requirement IDs
REQ_GEN_009

### Screenshots
![2019-02-20 13-33-15](https://user-images.githubusercontent.com/45107015/53071296-64e72a00-3514-11e9-8763-79ad0dfb664e.png)

**Comment by andrewbents** [comment]
Fixed in #1672
