### ISSUE TITLE
Add billing hook notifications to UI

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#1602]
### Description
User should be able to see readable error messages/notifications when updating resources

### This issue covers the following requirements:
REQ_RSC_001

**Comment by ershovaelena** [comment]
To test: 3 test cases mentioned in Requirements 1.411.29 doc

**Comment by dron8552** [comment]
Test on PR using Netpoint users with domains.

**Comment by Nadya913** [comment]
Error text contain not requested amount resources (DATABOX). 
1. Case RAM: The current amount of Ram is 4 GB and min quota is 2 GB. According to the error was requested 6 GB, but it wasn't  - please see the video.
Expected: 4 GB 
 ![peek 2019-02-28 16-15](https://user-images.githubusercontent.com/33111683/53555533-b9be1c80-3b74-11e9-9eba-eebada9f4ac4.gif)
2. Case Primary: 
The current amount of Primary is 1100 GB and min quota is 1000 GB. According to the error was requested 1000 GB, but it wasn't  - please see the video.
Expected: 1000 GB 
![peek 2019-02-28 16-26](https://user-images.githubusercontent.com/33111683/53556067-b70ff700-3b75-11e9-9b3e-881dfe871f86.gif)

**Comment by ershovaelena** [comment]
@Nadya913 2nd fail is fixed by Ivan

**Comment by dron8552** [comment]
Fixed multiple requests when updated resources by the user and admin (send all changed resources in one request).

**Comment by ershovaelena** [comment]
@Nadya913 also please test 
- main cases for admin (changing quotas)
- main cases for user (requesting resources)

**Comment by Nadya913** [comment]
1. Setting quota is broken for zero value. The minimum qouta parameter isn't sent in this case. 
![zero](https://user-images.githubusercontent.com/33111683/53718617-40813b00-3e8e-11e9-88a4-885970777429.gif)

**Comment by dron8552** [comment]
Fixed except the third point.

**Comment by Nadya913** [comment]
The first and second issues are fixed.

**Comment by ershovaelena** [comment]
@Nadya913 third issue was fixed by Ivan. let's check it and if there are no other cases for regression - please resolve the issue

**Comment by Nadya913** [comment]
4. Request resource button isn't alligned with free/user switcher in Firefox.
![requestbutton](https://user-images.githubusercontent.com/33111683/53781814-f99e4e80-3f3c-11e9-8288-4fca8177998b.png)
