### ISSUE TITLE
[Resource limits management plugin] Use GB instead of MB for RAM 

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#1608]
### Description
Changes to be applied for:
1. "Resource quotas" section (admin role)
2. Resource request dialog (user role)

## Connected requirements ID: 
REQ_RSC_003, REQ_RSC_001

**Comment by dron8552** [comment]
TEST IN #1604

**Comment by Nadya913** [comment]
1. No translation GB for Secondary storage in error message
![gb](https://user-images.githubusercontent.com/33111683/53481117-1e16a880-3aaf-11e9-965e-fc4b6aeea6b8.png)
