### ISSUE TITLE
Menu of 1 level  isn't opened when clicked on sandwich and after on darkened background

### ISSUE THREAD

**Issue by evgeniiamokhova** [bwsw/cloudstack-ui#1616]
### Description
Menu of 1 level isn't opened when clicked on sandwich and after on darkened background. Menu can be opened after refreshing page.

### Steps to reproduce
1) Login by user
2) Click sandwich
3) Click on darkened background
4) Click sandwich

### Actual result
Menu of 1 level doesn't open when clicking on sandwich

### Expected result
Menu of 1 level opens when clicking on sandwich

### Environment

<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] Opera version XX
- [ ] IE version XX
- [ ] Edge version XX
</code></pre>

### Connected requirement IDs
REQ_GEN_006

**Comment by dron8552** [comment]
TO TEST:
REQ_GEN_006
