### ISSUE TITLE
[Pulse] - Fix filters sorting

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#1617]
### Description
Now backend returns sorted values, but it is necessary to make changes so that it works with the list, not with map (before map was used)

### This issue covers the following requirements:
REQ_PLS_003
REQ_PLS_004
REQ_PLS_005
REQ_PLS_008
REQ_PLS_009
REQ_PLS_010
REQ_PLS_014
REQ_PLS_015

**Comment by dron8552** [comment]
TO TEST:
REQ_PLS_003
REQ_PLS_004
REQ_PLS_005
REQ_PLS_008
REQ_PLS_009
REQ_PLS_010
REQ_PLS_014
REQ_PLS_015
