### ISSUE TITLE
The system deletes the VM in the deleted status after some time

### ISSUE THREAD

**Issue by evgeniiamokhova** [bwsw/cloudstack-ui#1639]
### Description
The system deletes the VM in the deleted status after 8-10 minutes 

### Steps to reproduce
1) Login by user 
2) Go to action box of VM
3) Click button Delete(don't click "Expunge")
4) Click "Yes" in the dialog
5) Wait 8-10 minutes
6) Refresh the page

### Actual result
 VM in the deleted status is expunged

### Expected result
VM in the deleted status is not expunged

### Environment

<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] Opera version XX
- [ ] IE version XX
- [ ] Edge version XX
</code></pre>

### Connected requirement IDs
REQ_VM_LIST_010
### Screenshots
![Peek 2019-03-20 13-58](https://user-images.githubusercontent.com/45107015/54665063-87229680-4b18-11e9-92a3-8cf6d38f14a2.gif)

**Comment by bwsw** [comment]
Not a bug. Normal behaviour.
