### ISSUE TITLE
Dialog with suggestion about deleting snapshot appears when the snapshot is already deleted

### ISSUE THREAD

**Issue by evgeniiamokhova** [bwsw/cloudstack-ui#1640]
### Description
Dialog with the suggestion about deleting snapshot appears after  deleting snapshot

### Steps to reproduce
1) Login by user
2) Create a VM in the VM section
3) Create Disk in Storage section 
4) Click Attach in action box of created disk 
5) Select created VM and click Attach
6) Go to Storage and create snapshot 
7) Go to the VM section
8) Click Delete in action box of VM 
9) Click the checkbox "Expunge" and click Yes in the dialog
10) Click checkbox "Delete snapshot" and click Yes in the dialog

### Actual result
Dialog with the suggestion about deleting snapshot appears

### Expected result
Dialog with suggestion about deleting snapshot doesn't appear

### Environment
<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] Opera version XX
- [ ] IE version XX
- [ ] Edge version XX
</code></pre>

### Connected requirement IDs
[REQ_VM_LIST_013] 

### Screenshots
![Peek 2019-03-20 14-49](https://user-images.githubusercontent.com/45107015/54667724-a3760180-4b1f-11e9-952f-e29526ab9309.gif)

**Comment by dron8552** [comment]
TO TEST:
[REQ_VM_LIST_013]

**Comment by rennervo** [comment]
Tested on 1663
