### ISSUE TITLE
No zone by default is selected in VM creation modal dialog

### ISSUE THREAD

**Issue by Nadya913** [bwsw/cloudstack-ui#1650]
### Description
No zone by default is selected in VM creation modal dialog

### Steps to reproduce
The issue does not reproduce in the stable way. The issue can be reproduced if press 'Create new VM' and cancel few times.

### Actual result
No zone by default is selected in VM creation modal dialog.

### Expected result
Zone by default is selected in VM creation modal dialog.

### Connected requirement IDs
[REQ_VM_CREATE_002]

### Screenshots
![noZone](https://user-images.githubusercontent.com/33111683/55541025-56cd2180-56ee-11e9-9ce4-e92bbebe9d02.png)

**Comment by bwsw** [comment]
I also meet it rare with normal usage.
