### ISSUE TITLE
Volume created from snapshot doesn't appear in Storage list

### ISSUE THREAD

**Issue by Nadya913** [bwsw/cloudstack-ui#1653]
### Description
Created Volume from snapshot doesn't appear in Storage list, it appears after refreshing the page.

### Steps to reproduce
- Login and go to Storage
- Create Snapshot for any volume in status "Ready"
- Create volume from snapshot in action box

### Actual result
Created Volume from snapshot doesn't appear in Storage list and notification appears

### Expected result
After the notification appears the created volume from snapshot appears in Storage list 

### Connected requirement IDs
[REQ_STORAGE_DTLS_008] 

### Screenshots
![createVolumeFromSnapshot](https://user-images.githubusercontent.com/33111683/55603032-c85eab80-5792-11e9-9bed-f2e0eb11749c.gif)

**Comment by dron8552** [comment]
TO TEST:
[REQ_STORAGE_DTLS_008]

**Comment by rennervo** [comment]
Tested on 1664
