### ISSUE TITLE
Show templates/ISO only of types "my", "featured" by default in VM creation

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#1659]
### Description
Only "my" and "featured" types of templates and ISO files should be shown and activated in dropdown by default. "Community" templates should not be shown in the list by default until selected in the dropdown

N.B.Make Images list regression.

### This issue covers the following requirements:
REQ_VM_CREATE_006, REQ_VM_CREATE_008, REQ_VM_DTLS_023

**Comment by ershovaelena** [comment]
To test: 
REQ_VM_CREATE_006, 
REQ_VM_CREATE_008, 
REQ_VM_DTLS_023
+ Regression of the Images list functionality

**Comment by rennervo** [comment]
Tested on 1662
