### ISSUE TITLE
Can't create VMs if security groups feature is disabled

### ISSUE THREAD

**Issue by gentakojima** [bwsw/cloudstack-ui#1667]
### Description
Get this error:

Can't create vm with security groups; security group feature is not enabled per zone 

Details:

deployVirtualMachine | "id": "abd1c4f3-fbc4-403f-949e-1532d2c9b134", {   "startVm": "true",   "keyboard": "us",   "displayName": "prueba",   "serviceOfferingId": "26491ced-a1ed-4bc1-9047-d509b679e485",   "templateId": "df83bae7-099c-46ea-b40e-c4fc24f9d9c9",   "zoneId": "5bf53e8f-3609-454f-a52d-18b9d4728971",   "securityGroupIds": "b4bc824e-957f-4fac-af34-dd923fc788d1",   "rootDiskSize": 10 } | {   "uuidList": [],   "errorcode": 431,   "cserrorcode": 4350,   "errortext": "Can't create vm with security groups; security group feature is not enabled per zone",   "message": "Can't create vm with security groups; security group feature is not enabled per zone" }

### Steps to reproduce
Try to use Cloudstack UI with a Cloudstack installation with a zone having Security Groups disabled.

### Actual result
Get this error, VM is not created.

### Expected result
VM should be created without a security group

### Environment
Cloudstack 4.12.0, updated from an old 4.1.x installation to 4.3, then 4.6, and 4.9.

**Comment by bwsw** [comment]
@gentakojima thank you for the bug report.
