### ISSUE TITLE
VueJS remake?

### ISSUE THREAD

**Issue by jbonnett92** [bwsw/cloudstack-ui#1670]
I would love to see this in VueJS, can we remake this is VueJS?

Thanks,
Jamie

**Comment by bwsw** [comment]
@jbonnett92 We spent about 2 man-years to deliver the current code. Do you want to sponsor remake or it's just an idea. The cost to do the same with our team will be pretty expensive. Would you want to discuss it, contact me at ivan@bw-sw.com.
