### ISSUE TITLE
Unable to login using docker image.

### ISSUE THREAD

**Issue by goaliejordan** [bwsw/cloudstack-ui#1673]
Running Cloudstack 4.11.2.0 on Ubuntu 16.04.5 with HTTPS.
I followed the steps to run the docker image and can reach the login screen.
`docker run -d -p 8080:80 --name cloudstack-ui -e CLIENT_ENDPOINT=https://cloudstack-example.com:8443/client -e BASE_HREF=base_href bitworks.software:8443/cloudstack-ui:1.411.29`.

When trying to login with any admin account both ldap and local I am unable to do so.
Cloudstack apilog:
[a.c.c.a.ApiServer] -- POST command=login domain=
 [a.c.c.a.ApiServer] -- GET command=listCapabilities&response=json&sessionKey=somekey 401 unable to verify user credentials and/or request signature
[a.c.c.a.ApiServer] -- POST command=logout=== Logging out ===
The web inspection for chrome and edge show:
HTTP401: DENIED - The requested resource requires user authentication.
[object Error]: {description: "Unable to get property 'user' of undefined or null reference", message: "Unable to get property 'user' of undefined or null reference"

Have you seen this before? I cannot find any examples of logins to see if I am missing a step or if something is wrong in Cloudstack settings.
Any help would be greatly appreciated. Thanks

**Comment by goaliejordan** [comment]
I was able to login setting https=false on the cloudstack manager and using http instead for the endpoint.

**Comment by bwsw** [comment]
@goaliejordan in our deployments it works well.

**Comment by bwsw** [comment]
@goaliejordan The issue is found and fixed in recent update #1681 you can check it now.
