### ISSUE TITLE
DirectDownload Feature

### ISSUE THREAD

**Issue by bwsw** [bwsw/cloudstack-ui#1700]
### Description

Templates in CS support the "direct download" option. When template is uploaded from the URL, the user can set "direct download" and fill the "checksum" field. This implements another internal workflow for a template, but no other "UI-like" changes.

### Acceptance criteria:

[  ] User can check "Direct download from source" / "Скачивать непосредственно с источника"
[  ] User **may** optionally fill checksum if "Direct download" is selected 

These changes must be implemented in the template registration dialog.

**Comment by andrewbents** [comment]
Available for admins only
