### ISSUE TITLE
"Insufficient resources" error when clicking VM creation button 

### ISSUE THREAD

**Issue by mdbardina** [bwsw/cloudstack-ui#174]
Error message "Insufficient resources"

The most important thing is to describe what exacly is insufficient.
![2017-05-30 13-34-36](https://cloud.githubusercontent.com/assets/25217218/26570923/3b24fba2-453d-11e7-9a35-98f3e504f141.png)

**Comment by bwsw** [comment]
Also. The most important thing is to describe what exacly is insufficient.

**Comment by ershovaelena** [comment]
To be solved in #28 (Refactor VM creation)
