### ISSUE TITLE
Ingress/Egress Firewall rules display strings

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#18]
1. It would be nice to reorganize Firewall rules section in VM sidebar and in VM creation (Firewall rules -> Network rules).

Ingress 0.0.0.0/0 TCP 80 80 -> Incoming **TCP** traffic to ip **0.0.0.0/0** to **port 80**
Ingress 0.0.0.0/0 TCP 80-443 -> Incoming **TCP** traffic to ip **0.0.0.0/0** to **port range 80-443**
Ingress 0.0.0.0/0 ICMP -1 -1 -> Incoming **ICMP** traffic to ip **0.0.0.0/0** of **Any** ICMP type and **Any** ICMP code

There should be all codes/types mnemonic lines (except any).
 
2. Use the same approach for created rules as for templates (except for currently edited rule), because otherwise, it looks crazy when for ICMP we see start port/end port however it is nonsense or upgrade the current view to make it proper.

**Comment by qqcky** [comment]
@bwsw, should we show and use deprecated ICMP types?
