### ISSUE TITLE
Upgrade information organization in VM details (Storage) and Spare drives details

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#180]
There are some changes that should be done in the Storage view tab for root and attached drives:

1. Rename titles:

ENG Details -> General information
RU Подробности -> Общая информация

ENG Disk offering ->Performance
RU Дисковая услуга -> Производительность

2.  Rename "Name" in Performance to "Disk offering"
Move "Disk offering" from Performance to General information (in the last line)
3. Remove "Description" from Performance and put it as a tooltip to Disk offering
4. Change units of measure, keep it according to standards (eng version) even in RU layout:

IO/s, IO/сек -> IOPS 
МБайт/сек -> MB/s

5. Put all the units in value, not in label (as it is in Size field):

e.g. Read rate (MB/s) 100  -> Read rate 100 MB/s

**Comment by bwsw** [comment]
@ershovaelena 
Storage View / Storage Pane also is the subject of modification
