### ISSUE TITLE
Affinity Group Change Dialog enhancement

### ISSUE THREAD

**Issue by bwsw** [bwsw/cloudstack-ui#225]
It basically doesn't support creating a new group and just removal from the existing group. I suppose it should be unified with "group edit" dialog. After the fix #224.

![image](https://box.bw-sw.com/f/f749010013/?raw=1)

**Comment by bwsw** [comment]
It basically doesn't support creating a new group and just removal from the existing group. I suppose it should be unified with "group edit" dialog. After the fix #224.

**Comment by wowshakhov** [comment]
done in #224
