### ISSUE TITLE
Utilize listApis to handle unavailable API calls in a better way

### ISSUE THREAD

**Issue by bwsw** [bwsw/cloudstack-ui#236]
In ACS the administrator can configure some API calls unavailable for users in global server configuration, so it's wise to get all API calls on login and further correctly handle unaccessible API calls to hide controls, show proper warning messages, etc.

https://cloudstack.apache.org/api/apidocs-4.8/user/listApis.html

**Comment by andrewbents** [comment]
there is also listCapabilities request. We should dig into this one.

**Comment by zolotyx** [comment]
Closing this ticket, as we added support for listCapabilities command.
