### ISSUE TITLE
Cannot create a VM with KVM

### ISSUE THREAD

**Issue by immortalday** [bwsw/cloudstack-ui#244]
Trying to create basic VM in my test CL 4.9 environment running KVM (CentOS Linux release 7.3.1611 (Core)).

The UI returns the following error : 

`wrong response`

**Comment by bwsw** [comment]
@immortalday Hello. Could you please provide us with form screenshot before submit vm creation response. It could help to find the bug.

**Comment by zolotyx** [comment]
Hi @immortalday. please check the latest master update. 
Reopen if not fixes
Thanks
