### ISSUE TITLE
Browser compatibility

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#26]
Browser compatibility should be checked:

- Check against modern browsers 
- Build compatibility list 
- Build warning message when user uses a browser with version below required

**Comment by qqcky** [comment]
❌ IE11  (Win7): 

- Button on login page ('show more parameters') doesn't display correct;
- List of VM doesn't load;
- The activity log page doesn't load events;
- Color picker doesn't look correct... etc.
![](http://i.imgur.com/Llyc8Ar.png)
![](http://i.imgur.com/tIPrp8X.png)
![](http://i.imgur.com/3FHGryO.png)
![](http://i.imgur.com/mhKrcyT.png)

 ✅ EDGE (Win 10)
 ✅ Safari 10.0.2 (MacOS Sierra 10.12.2)

**Comment by qqcky** [comment]
:x: Mozilla Firefox < 43.0.0
