### ISSUE TITLE
[MDL=> Material2] Autocomplete

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#282]
We need to get rid of MDL components.
Need to replace them by angular-material component: Autocomplete

**Comment by andrewbents** [comment]
There is an issue with autocomplete in time zone component. It behaves as a usual html select. You can choose only a listed option and can't introduce your own. With angular2-mdl, this is sorta what you get with mdl-select with autocomplete turned on. But in case of material2, it is not. And their md-select doesn't provide this either (until next beta).
