### ISSUE TITLE
Please add listall=true  to all API calls

### ISSUE THREAD

**Issue by serverchief** [bwsw/cloudstack-ui#305]
I logged in as admin user and i'm not seeing all VMs. 

I expect to see all VMs - even the ones deployed by my customers.

**Comment by bwsw** [comment]
@serverchief 
Yes, it seems the attribute can be added to all lists without any damage. We will schedule it for the next iteration.

**Comment by bwsw** [comment]
To consult with PO about the implementation. Task is not full. To add required properties.

**Comment by bwsw** [comment]
- just add account filtering option for VM view, Disk view, Template view
- add vm free-form search field

**Comment by ershovaelena** [comment]
@ksendart please, check API on admin's rights to delete other users' entities. If there are no rights to do so, disable delete buttons for entities of other users.

**Comment by bwsw** [comment]
@zolotyx @ksendart 
Add account when group by account, because Name Surname is meaningless usually.
