### ISSUE TITLE
"e.vmList is undefined" error when creating VM

### ISSUE THREAD

**Issue by mdbardina** [bwsw/cloudstack-ui#318]
Steps:
1. Go to http://192.168.2.39:8888/master/instances page
2. Click on "add new VM" button
3. Create VM with default parameters
Result: "e.vmList is undefined" error 

![photo_2017-07-28_09-49-47](https://user-images.githubusercontent.com/25217218/28702749-4bd9c4bc-7389-11e7-864c-eea53cc5c212.jpg)

The bug is not always, I can't find conditions

**Comment by ershovaelena** [comment]
@mdbardina we can not reproduce this bug. Could you please repeat it and if you can not - close it ?
