### ISSUE TITLE
You can't do any activity with VM after reinstall

### ISSUE THREAD

**Issue by mdbardina** [bwsw/cloudstack-ui#320]
1. Go to http://192.168.2.39:8888/master/instances page
2. Create VM (or take existent)
3. Reinstall this VM
 Result: you still can see details, but you can't do any activity with VM after reinstall

![2017-07-28 12-04-12](https://user-images.githubusercontent.com/25217218/28703235-e3307452-738c-11e7-979b-effe0bf0a8fb.png)

**Comment by qqcky** [comment]
List is not updated after reinstall of VM
