### ISSUE TITLE
Upgrade ACS to 4.10 and check current features works

### ISSUE THREAD

**Issue by bwsw** [bwsw/cloudstack-ui#414]
Ensure all current functionality works well for ACS 4.10. Upgrade dev stand to ACS 4.10

1. Go through all features
2. Make a list of bugs and problems, provide @ershovaelena with this list to create issues

**Comment by ershovaelena** [comment]
1. In images: Common templates' zone tab request respondes with 531 error ({"listtemplatesresponse":{"uuidList":[],"errorcode":531,"cserrorcode":4365,"errortext":"Acct[162b26e6-052a-43bb-9116-acb7555b6d7d-develop] does not have permission to operate within domain id=6764b1a8-c69b-11e7-bdcf-0242ac110004"}})


Другие баги:
2. Создание ВМ. При выделении поля “аффинитетная группа” выделяется и поле “группа”.
Создаю группу, задаю новую группу, ВМ добавляется в список, но в фильтре по группам, созданной группы ещё нет
3. Создала новый storage, открываю вкладку “снимков”, написано “невозможно сделать снимок, диск не готов”, но в action’ах это действие есть и при попытке создать появляется соответствующая ошибка (то же самое и с расписанием снимков)
4. Открыла существующий storage -> сделать снимок, открывается диалог, нажимаю “ок”, ничего не происходит, нажимаю еще раз “ок”, ругается, т.к. уже выполняется действие со снимками (нужно долго ждать)
5. Удаление снимка -> ничего не происходит
6. Создание нового аккаунта - вместе с именем аккаунта выделяется и email
7. сайдбар в Account'ах не все может загрузить. проблемы с доступом


8. После закрытия диалогов в сайдбаре ВМ кнопка редактирования выделяется как будто на нее навели мышь (диалоги Service offering, VM group)
9. Диалог изменения аффинитетной группы в сайдбаре ВМ: нет отступов, текст обрезан краем диалога
10. Создание снэпшота диска в сайдбаре ВМ: 
- после нажатия на кнопку "создать" диалог не закрывается, хотя снэпшот уже начинает создаваться
- снэпшот создается, но в карточке не отображается сразу. перейти в другой таб, вернуться - отобразился
- при открытии "view all" лишняя кнопка "+", кнопка удаления без тултипа, при наведении на кнопку удаления она не выделяется
- не отображается описание снэпшота (а где оно должно, кстати, отображаться?)
11.
