### ISSUE TITLE
Change version enumeration to correspond ACS compatibility

### ISSUE THREAD

**Issue by bwsw** [bwsw/cloudstack-ui#417]
We need to invent how to aligne CSUI version to ACS version. E.g. 1.0.8 -> 1.49.8. 

ACS has next model
4.9.X (4.9.2 currently) -> 49
4.10.X (4.10.0 currently) -> 410

When we move our stand to 410, version will be 1.410.X, we should support last csY for 4.csX.csY in our 1.4csX.Z version.

1.0.8 has to be renamed to 1.49.8 and is last 4.9 compatible version. Next will be 1.410.X

**Comment by bwsw** [comment]
@ershovaelena 
Move information to wiki. Close the ticket.

**Comment by ershovaelena** [comment]
CS UI version naming scheme is described in wiki: https://github.com/bwsw/cloudstack-ui/wiki/CS-UI-version-enumeration
