### ISSUE TITLE
VM created from template with SSH auth mode

### ISSUE THREAD

**Issue by zolotyx** [bwsw/cloudstack-ui#434]
User should be able to see the modal dialog with password and button to open a webshell.

**Comment by bwsw** [comment]
If a webshell plugin is enabled. If not, then to native NoVNC console. 

Nb. Also it seems that we need to integrate it somehow in context actions menu, like now we have for ShellInABox, but it can be skipped for current iteration because we don't yet tackle with passwords yet.

**Comment by ksendart** [comment]
![2017-09-14 09-35-38](https://user-images.githubusercontent.com/23372522/30409612-7a04db48-9930-11e7-9ad6-10e4c6825313.png)
