### ISSUE TITLE
Create new template window stuck if template with already exist name

### ISSUE THREAD

**Issue by mdbardina** [bwsw/cloudstack-ui#442]
Steps:
1. create template
2. create another one with same name

See video
https://drive.google.com/open?id=0BzF_eUSNFENweHpPTGJrT2tWeEk

**Comment by mdbardina** [comment]
and layout not good too. The letters are cut off
![2017-08-23 15-14-12](https://user-images.githubusercontent.com/25217218/29606108-6395df08-8817-11e7-903e-d642a79a3bb2.png)

**Comment by ksendart** [comment]
solved in #278
