### ISSUE TITLE
"you are not logged in"

### ISSUE THREAD

**Issue by s-seitz** [bwsw/cloudstack-ui#443]
Using 1.0.7 release, I'm unable to login. 
cloudstack-management log shows:
`Attempting to log in user: NNNN in domain N`
`Retrieving user: NNNN`
`User: NNNN in domain N has successfully logged in`
`Current user logged in under Europe/Berlin timezone`
`Timezone offset from UTC is: 2.0`
`GET  command=listSnapshots&response=json`
`Expired session, missing signature, or missing apiKey -- ignoring request. Signature: null, apiKey: null`

The last two lines iterate with the very same result through the commands listOsTypes, listServiceOfferings, listSecurityGroups and so on.

I've tried both, our regular API endpoint via https and nginx as proxy, as well as forwarded native 8080 to my docker host with the very same result.

config.json has been setup as documented.

Using wrong credentials results in an (expected) "Incorrect username".

**Comment by bwsw** [comment]
@s-seitz Hi, Stephan, what ACS version you are using?

**Comment by s-seitz** [comment]
@bwsw  Hi!, it's cloudstack 4.9.0.1

**Comment by zolotyx** [comment]
Hi @s-seitz, could you please provide the following things for investigation?
1. browser console output
2. `login` command request/response with headers and cookies
3. `listSnapshots` command request/response from native UI

Does your Native UI pass sessionkey in cookies or via query params to the API

**Comment by s-seitz** [comment]
Hi @zolotyx, the Native UI as well as cloudmonkey are passing the sessionkey as query parameter. I'll provide the requested output hopefully tomorrow.

**Comment by s-seitz** [comment]
Gathering the Info, i found the solution: if "enable.secure.session.cookie" is set back to "false", cloudstack-ui is able to login. The difference is in the HTTP Response Header 
(true) -> Set-Cookie: JSESSIONID=[REDACTED];Secure;HttpOnly;Path=/client
vs
(false) -> Set-Cookie: JSESSIONID=[REDACTED]; Path=/client; HttpOnly
