### ISSUE TITLE
Error after vm destroying

### ISSUE THREAD

**Issue by ksendart** [bwsw/cloudstack-ui#453]
I got an error after vm destroying, But now i cannot reproduce it, or i get other error (with other text message). It's probably some sort of research task. I suppose it can be connected with tag creations, because new tag has been creating after vm deleting, but this tag already exist

**Comment by ksendart** [comment]
![2017-08-25 10-37-07](https://user-images.githubusercontent.com/23372522/29759438-051aea2c-8be6-11e7-937d-625d02335b2e.png)

**Comment by ershovaelena** [comment]
can not reproduce
