### ISSUE TITLE
[MDL=> Material2] Popover

### ISSUE THREAD

**Issue by wowshakhov** [bwsw/cloudstack-ui#457]

**Comment by wowshakhov** [comment]
It's possible that @angular-mdl/popover works without @angular-mdl/core. In that case we can just leave <mdl-popover>.

Alternatively, we can try https://github.com/joejordanbrown/material2/tree/extra/popover/src/lib/popover or write our own popover component based on <md-menu> from material2.

**Comment by andrewbents** [comment]
fixed in #516
