### ISSUE TITLE
Selects are cut off by dialogs

### ISSUE THREAD

**Issue by wowshakhov** [bwsw/cloudstack-ui#462]
Timezone select is cut off by dialog.
Also focus looks weird. The minute field is focused first, but then focus disappears and tab gets focused instead.

![29768441-69d7fdea-8c10-11e7-81c4-d6734435bb2f](https://user-images.githubusercontent.com/22027198/29769118-1fb1b618-8c13-11e7-9a9a-34baed70c723.png)

**Comment by ksendart** [comment]
close in #265
