### ISSUE TITLE
Improve VM creation throbber window

### ISSUE THREAD

**Issue by bwsw** [bwsw/cloudstack-ui#494]
It looks like there are a lot of background actions happen, like adding SG, adding rules to SG, creating VM. I think it's great to show the progress commenting it like:

Deploying the firewall ... OK
Deploying the firewall rule "..." ... OK
....
Deploying the VM "vm-develop-13" ... OK
Done

**Comment by zolotyx** [comment]
@ksendart, please make the modal dialog's height more not to add scroll after vm is created
