### ISSUE TITLE
Change disk offering chooser component in VM creation

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#501]
Change disk offering selector in VM creation when VM is being created from ISO to allow seeing details. It should provide user with information about existing offerings. He should understand what exactly he is creating.

**Acceptance criteria:**
1. Apply these changes to:
- VM creation 
- Resize disk dialog for custom disk offerings (Storage)
- Volume creation form (Storage)
2. Add a "select" button for disk offering (as for Installation source) in VM creation and in Storage that opens a list with characteristics of each. It might be a table or cards.
3. Add a possibility to set parameters of Disk Offerings that we want to show as enum in config. If all parameters are set in config - add a horizontal scroll in a table and put these parameters after default ones + all these parameters must appear in the sidebar of a disk (in Storage).
4. Document this feature in Config Guide and in Custom features local document

Parameters to show by default:
- Read rate (MB/s)
- Write rate (MB/s)
- Read rate (IO/s)
- Write rate (IO/s)

**Connected feature ID:** 
- _vm_creation_diskoffering_,
- _storage_disk_resize_,
- _storage_diskoffering_display_
- _storage_disk_create_

Mockup
![501](https://user-images.githubusercontent.com/26703076/31978953-4d04c596-b96e-11e7-80bd-272101d91f37.jpg)

**Comment by HeyRoach** [comment]
HeyRoach/501-do-selector
Test:
vm_creation_diskoffering
storage_disk_resize

**Comment by ksendart** [comment]
@ershovaelena  We also use Disk offering selector in Storage creation form. Should we use the same component there?

**Comment by ershovaelena** [comment]
@ksendart yes you are right! @HeyRoach make sure it is applied to Storage creation form

**Comment by Nadya913** [comment]
**storage_disk_resize**
For ROOT the disk offering option appears. Expected: no disk offering, just disk size.

**storage_disk_create**
Value None is displayed for new creating disk. Expected: Select button is on Line with Disk offering like for VM, no None appears.
![501-disk](https://user-images.githubusercontent.com/33111683/35376322-2ca28024-01dd-11e8-8f92-e2b0f105cc76.png)

**Comment by HeyRoach** [comment]
We have discussed with PO the first remark. 
Conclusion of this discussion:
In this ticket we don't want to add fixed column name.
Maybe in the future we will create a separeted task with this feature (for all tables in app)

**Comment by Nadya913** [comment]
Provisioning type values in table is doubled. For Russian - both in English and in Russian appear. 
Expected: value appears once in Russian and English
![501-provisioningtype](https://user-images.githubusercontent.com/33111683/35429754-f412ee3a-02a7-11e8-9059-c9b07a988bfb.png)
