### ISSUE TITLE
Change service offering chooser component in VM creation and VM details sidebar (main characteristics)

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#502]
Change service offering chooser component **in VM creation and VM details (SO changing)** to allow seeing details of the offering. It should provide the user with information about existing cloud offers. He should understand what exactly he is creating.

**Acceptance criteria:**
1. Add a "select" button for Service offering (as for Installation source) in VM creation
2. Add a switch Fixed/Custom 
3. Characteristics of SOs should be presented in a table (it is possible to use an expansion panel https://material.angular.io/components/expansion/overview)
4. Add filtering by classes (#498). E.g. a class "high CPU performance"
- nothing is chosen / everything is chosen - display all SOs
- when one class is chosen - display SOs only from this class, already grouped
5. Characteristics should be separated in "main" (основные) and additional (дополнительные) (additional will be done in #859)
6. A table should contain main characteristics of each service offering. Additional characteristics should open only when needed (by clicking or hovering).
- Main characteristics: 
-- CPU Cores (Ядра CPU)
-- CPU (MHz) (CPU (МГц))
-- Memory (Память (МБ))
-- Network Rate (Mb/s) (скорость сети)
- Additional characteristics: all the rest from original CS interface (#859)
7. Requirements for Custom tab
- when a user opens "custom" tab for the first time, the table should be empty (dashes for all columns). Then he can click any line to open Custom SO builder (to update its characteristics).
- show predefined characteristics of SO in edit dialog 
- show characteristics in a table after edit dialog is closed (if a user didn't edit anything and just clicked CONFIRM or if he edited some characteristics)
- store saved SO characteristics in account tags (consult #824 as an example) if account tags are supported, to configure behavior in config file
- when a user opens this dialog next time, SOs that have been edited before (those stored in tags) should be shown with characteristics

8. Document this feature in Custom features local document, in Config Guide and in Tags (wiki)

**Pay attention to units of measure!** (not KB, but MB etc)

Connected to #498

Mockup (the same dialog is accessible from VM sidebar when a user wants to change Service offering)

**Connected feature ID:**
- _vm_creation_so_
- _vm_creation_so_custom_
- _vm_SO_display_
-  _vm_SO_change_

![502](https://user-images.githubusercontent.com/26703076/34864846-c6331bca-f7a8-11e7-9c85-51211d059502.JPG)

**Comment by ksendart** [comment]
test on: http://cs-ui-ci.z1.netpoint-dc.com:8080/ksendart/502-so-chooser
to test: 
vm_creation_so
vm_creation_so_custom
vm_SO_display
vm_SO_change

**Comment by Nadya913** [comment]
**vm_creation_so**
Change style header SO from h5 to h4.
![502-so](https://user-images.githubusercontent.com/33111683/35262547-aed12510-0047-11e8-8a97-21d46a7f6da8.png)

**Comment by ksendart** [comment]
1. replace h5 with h4
2. add Missed dimension for Network Rate
3,4 - set filter view mode
5 - fix style for FireFox
6 - network rate value appears because this custom service offering initially has that parameter

**Comment by Nadya913** [comment]
vm creation dialog isn' respond for case: Use filter by classes, searching for no selection rows appaer and then Cancel SO change.

**Comment by Nadya913** [comment]
Tested on ksendart/502-so-chooser/
