### ISSUE TITLE
Change zone chooser component in VM creation

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#503]
Change zone selector in VM creation to allow seeing details. It should provide a user with information about existing zones. 
Add a "select" button for zones (as for Installation source) in VM creation that opens a list with characteristics of each. It might be a table or cards.

Each zone should contain zone description, location, other information

**Comment by bwsw** [comment]
Zone should include Geographical information which can be used for groupping, like:
Russia, USA or [Russia, Tomsk], [Russia, Novosibirsk], so zones can be groupped on the page with such geographical tagging.

**Comment by bwsw** [comment]
Also, Zone should allow setting purpose of it. Like [[Tomsk, Russia], General]

**Comment by bwsw** [comment]
Support Country, Town, CustomPurpose hierarchy.

**Comment by bwsw** [comment]
If there is only one zone, then hide zone chooser when VM is created and just .
