### ISSUE TITLE
Modify firewall view and editing (for SG templates and shared SGs)

### ISSUE THREAD

**Issue by bwsw** [bwsw/cloudstack-ui#506]
Acceptance criteria:
1. Remove edit button from an action box for Security groups (both templates and shared). There should be only View and Delete buttons.
2. View modal window should have a filtering by  Ingress/Egress and TCP/UDP/ICMP. Grouping will be added later (issue #578)
2. View dialog should contain Edit button that opens another dialog to edit and create rules (it stays the same, just remove horizontal separation rule between existing lines).
3. Add routes
4. If the group that user wants to edit is Shared, then show a warning dialog before opening an editing (described in #560).

Connected to #560 

Mockup
![506](https://user-images.githubusercontent.com/26703076/31063308-07885f10-a75c-11e7-92a6-a3ba421500f6.jpg)

**Comment by qqcky** [comment]
was closed with PR #590  (#560)
