### ISSUE TITLE
TypeError: Cannot read property 'isTemplate' of undefined

### ISSUE THREAD

**Issue by andrewbents** [bwsw/cloudstack-ui#522]
When use switch zones in vm creation, use get an error
TypeError: Cannot read property 'isTemplate' of undefined
    at e.get [as diskOfferingsAreAllowed] (main.d04d50b2f18c11a9a6f5.bundle.js:1)
    at e.PiO1.e.filterDiskOfferings

**Comment by ksendart** [comment]
The original task - https://github.com/bwsw/cloudstack-ui/issues/461
