### ISSUE TITLE
Installation source can be choosen for the wrong Zone

### ISSUE THREAD

**Issue by mdbardina** [bwsw/cloudstack-ui#523]
Steps:

1. Go to create VM
2. Choose Installation source for Zone RU1.Compute (e.g. OS template: test-template-2)
3. Change Zone from RU1.Compute to US1.HighIO

**Actual Result:** Installation source stay 'OS template: test-template-2' and Create button is available. 'The template 609 is not available for use' message displayed after click 'create'

**Expected Result:** Installation source should be cleaned if chosen Zone doesn't have such template, Create button is not available

![2017-09-14 11-53-11](https://user-images.githubusercontent.com/25217218/30412683-5819e81c-9943-11e7-8e1d-8fe6f26aa8a6.png)
![2017-09-14 11-52-47](https://user-images.githubusercontent.com/25217218/30412682-581588d0-9943-11e7-80d9-d05128782f93.png)

**Comment by andrewbents** [comment]
i think it was fixed in #524
