### ISSUE TITLE
Error in VM creation when affinity group contains commas

### ISSUE THREAD

**Issue by wowshakhov** [bwsw/cloudstack-ui#544]
If affinity group in VM creation contains commas, they are treated as separators for a list of affinity groups, which causes the following error: 

1) VM creation input:
![_058](https://user-images.githubusercontent.com/22027198/30536201-22f40da8-9c8f-11e7-81ae-9d6791085a35.png)

2) Request:
command:deployVirtualMachine
affinitygroupnames:a,b,c

3) Response:
errortext: "Unable to find affinity group by name a"

Changes to be implemented: Do not let enter commas as our interface is not going to support assigning of many affinity groups. Add this restriction.

**Comment by zolotyx** [comment]
We need to prevent user from entering comma in the affinity group name field
