### ISSUE TITLE
Incorrect buttons layout at Recurring Snapshots dialog

### ISSUE THREAD

**Issue by bwsw** [bwsw/cloudstack-ui#547]
![](https://box.bw-sw.com/f/00b08e3178c34e44be1e/?dl=1)

**Comment by ksendart** [comment]
![2017-09-26 11-04-54](https://user-images.githubusercontent.com/23372522/30842174-9f687934-a2aa-11e7-8dc3-413c63d1ea6a.png)

**Comment by ksendart** [comment]
![image](https://user-images.githubusercontent.com/23372522/30856480-b2c03426-a2e2-11e7-8546-1da684ca9bf5.png)

**Comment by ksendart** [comment]
![image](https://user-images.githubusercontent.com/23372522/30856502-c78e07d4-a2e2-11e7-8202-f6d1531b025d.png)
