### ISSUE TITLE
Where is the actual code?

### ISSUE THREAD

**Issue by maq123** [bwsw/cloudstack-ui#55]
Hi All,

looking at the description I got pretty enthusiastic about the stuff you did, wanted to check it out. 
But I do not see any code available, I guess you have it in some private branch?

**Comment by bwsw** [comment]
Hello, right now the team is doing latest tests before public release. We are going to publish up to the next friday. Will keep you in touch.

**Comment by maq123** [comment]
Awesome, looking forward to test it. Screens look really nice!

**Comment by bwsw** [comment]
Hello, Initial release is deployed. We still have some open issues regarind the current release, but most of the functions must be functional.
