### ISSUE TITLE
ISO delete "TEST.key" doesn't work

### ISSUE THREAD

**Issue by bwsw** [bwsw/cloudstack-ui#556]
```
http://192.168.2.39:8888/master/templates/iso/f8230f72-13e1-4be5-baac-0a45d1619286/tags?categoryFilters=featured&categoryFilters=self&zones=031a55bb-5d6b-4336-ab93-d5dead28a887&zones=3fcdb37c-1c0b-4728-b62f-970c765c3fbc
```
Go to Tags section and try to remove TEST.key. Deleting is not possible as there are no permissions.

We should check which conditions cause this error. E.g. If template/ISO is not "ours", then we should hide delete button. In general, there should be a verification for permissions in order to avoid these errors

**Comment by bwsw** [comment]
The same is true for templates.

**Comment by ershovaelena** [comment]
Do not show editing and creation if there are no permissions
