### ISSUE TITLE
Offering Compatibility Policy Enforcing

### ISSUE THREAD

**Issue by bwsw** [bwsw/cloudstack-ui#567]
Each zone can contain one or more pods [(About Pods)](http://docs.cloudstack.apache.org/en/latest/concepts.html#about-pods). A pod consists of one or more clusters of hosts. 

**Zone Wide storage (ZW)** - a storage is for the whole zone, all clusters can use it. 
**Cluster Wide storage (CW)** - a storage is dedicated for one concrete Cluster. 

There are Service Offerings with tags in Clusters. For example,
Cluster1: SO1 has a tag T=C1
Cluster2: SO2 has a tag T=C2
 
There are no problems with ZW. If VMs are from different clusters but they all have ZW, they all can be converted (SO changed). VMs from one cluster also can be converted as they have a storage of the same type.
But if VMs have CW storage, there is a problem: 
_Imagine there is a VM1 in a Cluster1 and a user wants to change its Serice Offering (C1) on another one (C2). Running VM in Cluster2 will not be possible because a Storage does not migrate automatically and it will still be in Cluster1._

So if there is a CW storage used, we should enforce offering change policy. **There are three possible policies and other restriction:**
R. Shared <> Local - impossible

Tags are received from HostTags. So for every HostTags:
- P1. TagSetOld == TagSetNew - exact tags match
- P2. TagSetNew E TagSetOld - old offering tags contains new offering tags
- P3. No restrictions

Policy should be specified in configuration file like
```
offeringChangePolicy: contains-all|exactly-match|no-restrictions
offeringChangePolicyIgnoreTags: [t1, t2, t3]
Default: no-restrictions
```
E.g. HostTags: PERMIT,GENERAL

It's also important to ignore tags because they don't influence on compatibility, but just placement. Aso ignore hostTags.

This is very useful when you have several clusters in one zone and you want to protect a user from converting offerings between incompatible states because it might happen that selected offering is not supported in the cluster where storage of current VM relates to.

**Feature must be documented very carefully**

**Connected feature ID:** _vm_SO_change_

![567](https://user-images.githubusercontent.com/26703076/31978148-27e142b6-b96a-11e7-86be-1ae99a252427.jpg)

**Comment by bwsw** [comment]
Define feature documentation very carefully.

**Comment by ksendart** [comment]
https://docs.google.com/document/d/1EdlQQC1MXeB7YIkh0xsOmj5ddGwyJe2DaWUc63GvAxI/edit#

**Comment by ksendart** [comment]
test on: http://cs-ui-ci.z1.netpoint-dc.com:8080/bwsw/567-offering-policy
to test: vm_SO_display, vm_SO_change

**Comment by Nadya913** [comment]
Tested on http://cs-ui-ci.z1.netpoint-dc.com:8080/bwsw/567-offering-policy
simulator
