### ISSUE TITLE
Template/ISO Terms and Conditions Agreement

### ISSUE THREAD

**Issue by bwsw** [bwsw/cloudstack-ui#593]
For some templates, the agreement should be approved by the user. The agreement might define licensing terms and conditions, for example, for Windows VMs user should acquire a license to legally use VM. It might apply to other templates/ISOs as well. We have to support it internationally. 

The administrator defines texts/translations for certain template/iso and when the template/ISO is chosen for VM deployment the dialog with agreement should be shown (when user clicks "Deploy") where user clicks Accept / No, if user accepts then acceptance tag (csui.terms.accepted=true) is placed to VM tags, if no then the deployment doesn't happen. It's not a case that user can remove tag becuse it still is present in logs and can be used as a proof if necessary.

The agreement can be quite big, thus it's impossible to use template tags. It should be specified in a configuration for the UI (preferable as external MD documents by locales ru/en/..):
```json
"agreements": {
  "template-uuid": {"ru" : 'agreements/template-uuid-agreement-ru.md', ...}
   ....
}
```

if no agreement specified, the pipeline works by default the same way it does now.

You are going to use a paid software. You should acquire a license to legally use VM. Are you sure you want to use this installation source? (Вы собираетесь использовать платное ПО. Вы должны приобрести лицензию, чтобы пользоваться им легально. Вы уверены, что хотите выбрать данный источник?)

**Acceptance criteria:**
1. If an agreement is specified for a template/ISO, then after choosing it in VM creation and clicking on "choose" show the dialog with Agreement
2. Two options in Agreement dialog: "I agree" and "Cancel"
- If "I agree" is clicked, come back to VM creation form (installation source is chosen) and remember that user agreed (put to tags (e.g. csui.terms.accepted=true))
- If "Cancel" is clicked, then do not close Installation source dialog, return a user to Templates/ISO list to choose another one
3. There should be a possibility to set a **default** agreement (e.g. english version). If there is no localized version of an agreement, system should show the default version.

Mockup 
![593](https://user-images.githubusercontent.com/26703076/31326655-62415b0e-acf3-11e7-8a6b-47feb53f09e7.jpg)

**Comment by bwsw** [comment]
@zolotyx 
Could we use template tags to refer to required MD file. Regular users can't change admin tags for templates, it could work well.

**Comment by ershovaelena** [comment]
@bwsw yes, it is possible, we will use template tags
