### ISSUE TITLE
Getting started guide for developers?

### ISSUE THREAD

**Issue by rhtyd** [bwsw/cloudstack-ui#605]
Can you start a guide/section in README on how to build, run your UI for developers?

**Comment by bwsw** [comment]
@rhtyd hi, we hopefuly do the first version guide next week.

**Comment by ksendart** [comment]
[start guide.txt](https://github.com/bwsw/cloudstack-ui/files/1459669/start.guide.txt)

**Comment by zolotyx** [comment]
@ksendart , please update readme.md with that guide.
Please include section with Proxy configuration
