### ISSUE TITLE
Review all features and define which should be documented because of implicit behaviour

### ISSUE THREAD

**Issue by bwsw** [bwsw/cloudstack-ui#612]
Some features we do assume specific behaviour based on business logic. We should define how they work, why they work that way, how they should be configured to work the way they supposed to do.

**Comment by bwsw** [comment]
@ershovaelena 
Write release notes with screenshots (to wiki) for 1.49.13 with all features from last published (I mean published to community) release (1.49.9).

**Comment by ershovaelena** [comment]
A separate issue was created for Release notes #635

**Comment by ershovaelena** [comment]
Special functions
1. How it works
2. How to make sure that it works
3. If there are some policies e.g. in config that influence its behavior (There is an "x" setting that influences function's behavior in this and that way. It is set in config)

**Comment by zolotyx** [comment]
Proposing to remove config options from readme, and add them to wiki
list of features to move:

- defaultServiceOfferingConfig
- customOfferingRestrictions
- offeringAvailability
- securityGroupTemplates

**Comment by ershovaelena** [comment]
WIll be done by tech writer as a part of writing User and Administrator documentation
