### ISSUE TITLE
Validate how service offerings limited to specific domains are handled in CSUI

### ISSUE THREAD

**Issue by bwsw** [bwsw/cloudstack-ui#614]
@ershovaelena @zolotyx 
Service offering can be created for specific domain and thus it should be handled appropriately.

**Comment by bwsw** [comment]
@ershovaelena @qqcky 
I suppose those service offerings should be available for domain and subdomain accounts.

**Comment by ksendart** [comment]
Service offering can be limited for accounts on the creation stage. When user create service offering, the CSUI offers user to make it public or not. If user choose this option, then service offering became avaliable for all users. In another case, if user doesn't choose public option, he should specify domain, and only accounts, which belongs this domain can use created service offering. 
Also, if user requests service offering list, he can specify domainid and get only domain service offerings. And, if user uses another domainid (doesn't belong), then user get an error.
