### ISSUE TITLE
Add a capability to copy API Log in case of error during VM creation

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#645]
Now we have a list of operations and their status after VM creation, but there are no raw answers from the server. 

This issue covers the following requirements:
[REQ_VM_CREATE_025] A user should have an opportunity to copy API log in case of VM creation error

Mockup
![645](https://user-images.githubusercontent.com/26703076/35895919-2d9bb360-0bec-11e8-96d3-2b0a043f52f3.jpg)

**Comment by bwsw** [comment]
API log.

**Comment by ershovaelena** [comment]
partly done. to check the code

**Comment by bwsw** [comment]
@ershovaelena Use "Capability", not "Possibility" everywhere except the meaning "chance".

**Comment by rennervo** [comment]
Lack: 1

**1) The "Close" button is superimposed on the copy icon**
It is necessary that the "close" button and the "Details" element (in compressed or measured form) do not overlap.

Steps:
1. Go to VM creation.
2. Select the data for the error during deployment
3. Click Create
4. Expand the details window in the error window
5. Scroll to the bottom of the details window to display the copy icon

Actual result: Close button superimposed on copy icon
Expected Result: The close button is below the Details element and does not intersect with it
![close and copy icon](https://user-images.githubusercontent.com/26665398/51666354-372fc380-1ff0-11e9-9c4b-a6f564045a5a.png)

**2) The data is aligned vertically at the center of the columns in the error details table**

Steps:
Repeat steps 1 through 4 from the previous item.

Actual results: The data inside the columns are vertically centered
Expected Result: The data inside the columns are vertically aligned with the top edge
![vertical aligment](https://user-images.githubusercontent.com/26665398/51666366-40209500-1ff0-11e9-9689-a2bbd555b2e1.png)

**3) There is no "id" parameter in the table with details**
In the request to create a VM, in addition to "request", "params" and "response", the "id" parameter is also present. This parameter is missing in the "Details" element inside the window with a VM deployment error.

Steps:
Repeat steps 1 through 4 of the first item.

Actual result: The parameter "id" is not in the table
Expected result: The parameter "id" is present in the table

**Comment by rennervo** [comment]
Lack: 2

### The "Close" button is superimposed on the details window

When the browser window is resized, elements should not move inside the VM deployment information window. Including the "Close" button should not run into the "Details" window.

**Steps:**
1. Go to VM creation
2. Select the data for the error during deployment
3. Click Create
4. Expand the details window in the error window
5. Scroll to the bottom of the details window to display the copy icon
6. Reduce browser window size

**Actual result:** the "Close" button is superimposed on the "Details" area (screenshot 1).
**Expected Result:** The Close button does not move inside its window. As well as implemented in other system errors that have a drop-down area. (screenshot 2)
![645screen1](https://user-images.githubusercontent.com/26665398/51814080-1fa45380-22ec-11e9-819c-b12e3aea7286.png)
![645screen2](https://user-images.githubusercontent.com/26665398/51814081-1fa45380-22ec-11e9-802c-318cba8e4517.png)

**Comment by Nadya913** [comment]
The titles in Details isn't translated to Russian.
![title](https://user-images.githubusercontent.com/33111683/51883789-116f3980-23b7-11e9-9c5f-19ae8334b70c.png)
