### ISSUE TITLE
Use ngrx store for VM creation

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#646]
Use ngrx store for VM creation. Connected to #630

**Comment by qqcky** [comment]
**To test:** _vm_creation_name, vm_creation_zone, vm_creation_so, vm_creation_so_custom, vm_creation_installsource, vm_creation_installsource_filter, vm_creation_installsource_search,  vm_creation_diskoffering, vm_creation_diskoffering_disksize, vm_creation_vmgroup, vm_creation_affinitygroup, vm_creation_firewall_template, vm_creation_firewall_shared, vm_creation_keyboard, vm_creation_sshkeypair, vm_creation_vmstart, vm_creation_agreement, vm_postcreation_ISO, vm_postcreation_SSH, vm_postcreation_HTTP, vm_postcreation_log_copy, vm_deploy, vm_creation_progress_logger_

**Regression**: _vm_ISO_attach_

Test on `bwsw/646-ngrx-vm-creation`

@ershovaelena

**Comment by Nadya913** [comment]
Tested on http://cs-ui-ci.z1.netpoint-dc.com:8080/bwsw/646-ngrx-vm-creation
Found issues:
1. vm_creation_installsource - no available templates error appears
Steps:
1. Press create new VM
2. Open Installsource dialog, select iso tab
3. Use filter for group 
Actual result: no available templates error appears on Create VM dialog
Expected result: no errors appears

2. vm_creation_installsource_filter, vm_creation_installsource_search - group value and searching value isn't saved for close/open dialog Installation sourse
Steps:
1. Press create new VM
2. Open Installsource dialog, select group and input  searhing value
3. Close Installsource dialog and open again
Actual result:  group value and searching value isn't saved for close/open dialog Installation sourse
Expected result:  group value and searching value is saved for close/open dialog Installation sourse

3. vm_creation_diskoffering_disksize - size disk value empty
Steps:
1. Press create new VM
2. Open Installsource dialog, select iso tab and choose any value
3. Select custom disk offering
4. Input disk size or increase the value
Actual result: inputed value disappears
Expected result: value is present

4. vm_creation_progress_logger - infinitely loading throbber for already exist affinity group
Steps:
1. Press Create VM, fill mandatories
2. Input already existing value for affinity group (use one letter with upper case )
3. press Create
Expected result: error appears in logger dialog
Actual result: infinitely loading throbber, error in console
{"createaffinitygroupresponse":{"uuidList":[],"errorcode":431,"cserrorcode":4350,"errortext":"Unable to create affinity group, a group with name new123 already exists."}}

5. vm_postcreation_ISO - no vnc console button, no ip address
Steps:
1. Create VM
2. Fill mandatories
3. Press Create
Expected result:  vnc console button, no ip address appear
Actual result: no vnc console button, no ip address

Please. see the attach

![646-emptysize](https://user-images.githubusercontent.com/33111683/34241901-28c948fa-e64b-11e7-89a3-89befd538f97.png)
![646-templates](https://user-images.githubusercontent.com/33111683/34241902-28eb281c-e64b-11e7-9c01-703933020cb6.png)
![646-throbber](https://user-images.githubusercontent.com/33111683/34241903-290cdb88-e64b-11e7-8dc5-c36ff58cd8f1.png)
![646 - vncconsole](https://user-images.githubusercontent.com/33111683/34241904-292d5b4c-e64b-11e7-9738-8068933921b5.png)

**Comment by zolotyx** [comment]
<img width="770" alt="screen shot 2017-12-21 at 23 04 52" src="https://user-images.githubusercontent.com/2853979/34263848-70b81710-e6a3-11e7-9b74-d366fa729be6.png">

Nothing is loading(spinning) during vm deployment stage

**Comment by Nadya913** [comment]
http://cs-ui-ci.z1.netpoint-dc.com:8080/bwsw/master/instances/create
develop

**vm_creation_installsource_filter**
Steps:
1. Login by develop and press Create VM 
2. Press installation source, apply filter os or types
3. Select any value and close  installation source dialog
4. Press again  installation source
Expected result: all values are checked for os, types
Actual result:  filtering values are saved for os, types

![646 - os](https://user-images.githubusercontent.com/33111683/34334124-503d56a0-e976-11e7-8115-928ef679a2b3.png)

**Comment by Nadya913** [comment]
**vm_creation_agreement**
After creation dialog is open with still  with throbber. Would you please switch to Create VM for cancel button.
**Create VM**
Steps:
1. Login by develop
2. Press create VM and cancel
3. Press create VM again
Expected result: Create VM dialog opens
Actual result: throbber is loading too long

**Comment by Nadya913** [comment]
Tested on bwsw/646-ngrx-vm-creation
