### ISSUE TITLE
VM sidebar bugs 

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#679]
1. После закрытия диалогов в сайдбаре ВМ кнопка редактирования выделяется как будто на нее навели мышь (диалоги Service offering, VM group, add secondary IP)
2. Storage сайдбара ВМ: resize root disk
2.1. в диалоге плохое выравнивание элементов ("10" число выше по выравниванию, чем "GB")
2.2. не работает. после нажатия на resize ничего не просиходит, значение не меняется

**Comment by ksendart** [comment]
в #630 вся
