### ISSUE TITLE
Snapshot management bugs

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#681]
Снэпшоты дисков (в сайдбаре ВМ и в разделе Storage): 
1.1. после нажатия на кнопку "создать" диалог не закрывается, хотя снэпшот уже начинает создаваться
1.2. снэпшот создается, но в карточке не отображается сразу. перейти в другой таб, вернуться - отобразился. то же самое с удалением
1.3. при открытии "view all" лишняя кнопка "+" (создание темплейта, при нажатии открывается белая полоса слева), кнопка удаления без тултипа, при наведении на кнопку удаления она не выделяется
1.4. не отображается описание снэпшота (должно ли оно, кстати, отображаться?)
1.5.  диалог создания шаблона из снэпшота не открывается (белая полоса слева экрана)
1.6.  диалог создания расписания снэпшотов - неправильный padding (слишком большой отступ снизу от кнопки close)
1.7. после создания нового диска нельзя создать снэпшот, ошибка “невозможно сделать снимок, диск не готов”, но в action’ах это действие есть и при попытке создать появляется соответствующая ошибка (то же самое и с расписанием снимков). возможно, нужно проверять это и дизейблить соответствующую кнопку

**Comment by ksendart** [comment]
в #630 исправлю создание (1), удаление снепшота (), создание темплейта из снепшота (5), обновление информации (2),  добавлю условия для экшена "создать снепшот" для нового диска  (7),

**Comment by ershovaelena** [comment]
TBD in #630
