### ISSUE TITLE
Replace current timezone selector 

### ISSUE THREAD

**Issue by qqcky** [bwsw/cloudstack-ui#683]
Now it is not easy and comfortable to choose timezone. It should hint or autocomplete user's query. It should be sorted by ABC. (Selector with search function?). 

Connected to #625

**Comment by ksendart** [comment]
https://github.com/angular/material2/pull/7835

**Comment by jrood** [comment]
The author of https://github.com/angular/material2/pull/7835 seems to be waiting feedback regarding a11y, so if you have any, please leave it there.

**Comment by bwsw** [comment]
@ershovaelena 
support default timezone, specified globally in config and remembered in account tags for account.

**Comment by ershovaelena** [comment]
Depreciated. A default timezone and account tags support TBD in #977
