### ISSUE TITLE
There is no Firewall section in VM creation

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#687]
1. Go to VM list
2. CLick on VM creation button

Expected result: there is a Firewall section 
Actual result: there is no firewall section 
![4qqq](https://user-images.githubusercontent.com/26703076/33167124-21dd45a6-d06f-11e7-9494-c6ea0f51e2d1.PNG)

**Comment by qqcky** [comment]
UI shows firewall section if `securitygroupsenabled` capability is enabled, however if Zone does not have `localstorageenabled`, security group can not be attached to VM.
