### ISSUE TITLE
There is no "Custom" in service offering selector in VM creation

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#688]
1. Go to VM list
2. Click on VM creation button
3. Click on SO selector

Expected result: there is a Custom variant
Actual result: there is no Custom variant
![4sss](https://user-images.githubusercontent.com/26703076/33167215-68b1e4b4-d06f-11e7-909a-46cde291821d.PNG)

**Comment by bwsw** [comment]
@ershovaelena just create it for your domain.
