### ISSUE TITLE
Get rid of BaseModel

### ISSUE THREAD

**Issue by zolotyx** [bwsw/cloudstack-ui#697]
We need to get rid of BaseModel, let's use just interfaces for entities

**Comment by ershovaelena** [comment]
there is a problem with root disks. Sometimes there are 2 actions in actionbar that appear for root disks (detach and delete), though they should be available only for data disks. This is a model problem, fixed in #630, but it is proposed to make a refactoring in this ticket (c) @ksendart

**Comment by zolotyx** [comment]
@ershovaelena , how your comment relates the ticket?
