### ISSUE TITLE
List view / box view switch

### ISSUE THREAD

**Issue by bwsw** [bwsw/cloudstack-ui#7]
Develop the switch which allows switching every screen between list view and boxed view. Selected switch position should be remembered for future for the screen.

Base on Google Inbox https://inbox.google.com

**Acceptance criteria:**
1. Table view with no column boards. But data in columns should be positioned strictly one under another. 
2. If an entity has a description, it should be placed under the name
3. If there are icons or state bullets, it should be placed on the left side of the name
4. A switcher (List view - Box view) should be placed on the bottom of the screen, use toggle buttons with pictures (pictures can be taken from Google Drive switcher). Leave a narrow line for it
5. The view should be remembered for each page separately.

Mockup
![7](https://user-images.githubusercontent.com/26703076/31324897-8c500632-ace1-11e7-858c-b241b2fd4801.jpg)

**Comment by ershovaelena** [comment]
Changes to apply (from the meeting October 26th with PO):
1. Change a state bullet into a strip and move it on the left side of each element
2. OS family should be the last element (after Disks)
3. Remove borders between CPU, RAM and Disks
4. Put all elements in one line (e.g. CPU:...., RAM: ...,)
5. Use one font size for all elements (all sections)
6. Make sure that all elements (state bullet, "triple points" action button) are aligned properly
7. Adapt the height of elements according to amount of text inside (e.g. lines in Storage sections will be smaller)
