### ISSUE TITLE
Template/ISO switcher in VM creation wrong behaviour

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#716]
Steps to reproduce:
1. Go to VM creation
2. Open an Installation Source dialog

Expected result: "Templates" are chosen in a switcher
Actual result: Both tabs are grey, ISO are in the list as if they were chosen. Reproduces not every time. Hard to find the logic.

**Connected feature ID:** _vm_creation_installsource_display_

![imagesswitcher](https://user-images.githubusercontent.com/26703076/33466447-ad5e1c10-d680-11e7-91d1-1885d063c09d.png)

**Comment by qqcky** [comment]
The same view bug (both tabs are grey) is on switcher in Security Group rules dialog in VM creation.
