### ISSUE TITLE
"Group by" wrong behaviour when changing group tag of a template

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#717]
Steps to reproduce:
1. Go to Images
2. Choose a template with a group
3. Go to tags tab of this template in its sidebar
4. Change a **csui.template.group** tag value (e.g. if template group is **test**, change it to **tests**)
5. Go to Images list
6. Apply "group by groups"

Expected result: the template is in the group "General" (as the tag was changed to the one that is not specified in config - it must be moved to General)
Actual result: the template is in **tests** group

This bug occurs only for grouping. Filtering works well.

![567](https://user-images.githubusercontent.com/26703076/33467505-79e5f7fc-d687-11e7-9372-3c1ea0c9321e.PNG)

**Comment by Nadya913** [comment]
Tested on master
