### ISSUE TITLE
Show localized message when error for set up hourly schedule for snapshot appears

### ISSUE THREAD

**Issue by Nadya913** [bwsw/cloudstack-ui#722]
Url: http://cs-ui-ci.z1.netpoint-dc.com:8888/master/storage
User: develop

The hourly schedule is turned off for the domain. We should manage cases like this by showing an informal message for users.

Please transform this error into a localized message.
RU "Почасовое расписание отключено"
EN "Hourly schedule is turned off"

**Connected feature ID:** _storage_snap_schedule_

![hourly_schedule](https://user-images.githubusercontent.com/33111683/33474275-7b49b1a4-d6ac-11e7-894e-2ae162d8c1d7.png)

**Comment by ksendart** [comment]
@zolotyx Error is reproduced in current Cloudstack version, and not reproduced in Cloudstack simulator

**Comment by HeyRoach** [comment]
HeyRoach/722-localized-error-message-for-hourly-schedule
To test: storage_snap_schedule

**Comment by Nadya913** [comment]
Tested on HeyRoach/722-localized-error-message-for-hourly-schedule/
