### ISSUE TITLE
Do not close, but redirect back to dialog when error occurs

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#734]
Please do not close a dialog when an error occurs and it is needed to click OK in error dialog. It is inconvenient for a user to start from scratch. Please check out that all dialogs have a proper behavior.

Example:
1. Go to Images, templates
2. Click on template creation button
2. Fill in unvalid URL 
3. Click CREATE
4. A message with error appears
5. Click OK

Expected result: user is redirected back to template creation dialog, filled data is saved
Actual result: dialog is closed, user is redirected to Images list

**Change dialogs:**
- template creation
- volume resize
- account creation
- volume creation

**Connected feature ID:**
- _image_template_creation_
- _image_iso_creation_
- _storage_disk_create_
- _storage_disk_resize_
- _vm_disk_resize_
- _account_create_

**Comment by HeyRoach** [comment]
- [ ]  Template creation dialog

**Comment by Nadya913** [comment]
in Testing on Master

**Comment by Nadya913** [comment]
Tested on Master, https://github.com/bwsw/cloudstack-ui/issues/795 opened
