### ISSUE TITLE
Unify selectors displaying in dialogs 

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#735]
All selectors (except filtering and grouping in lists) should display the current element in a list as a preselected one (see the 1st picture - small instance is current element chosen by a user).
Now a "disk resize" dialog in Storage does not correspond to this behavior (see the 2nd picture). Please, fix this and check out all dialog selectors. 

**Connected feature ID:** _storage_disk_resize_  + all dialogs with selectors

![qwert](https://user-images.githubusercontent.com/26703076/33642388-64e090ae-da6c-11e7-9fa2-f99e94cbb445.PNG)

![qwert1](https://user-images.githubusercontent.com/26703076/33642393-693fbcd8-da6c-11e7-83d3-576f59d08932.PNG)

**Comment by HeyRoach** [comment]
Changes:

- [ ] Vm sidebar -> Service offering dialog

- [ ] Vm sidebar -> Edit SSH key dialog

- [ ] Volume -> resize dialog
