### ISSUE TITLE
Sorting by elements in lists does not work 

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#736]
Elements in lists in each section should be sorted by name.
Sorting is not applied to following sections:
- VMs
- Storage
- Images
- Accounts 

Please make sure that it works in Firewall and SSH keys as well.

**Comment by HeyRoach** [comment]
Sections:
- [ ] Vms

- [ ] Storage

- [ ] Images

- [ ] Accounts

- [ ] Firewall

- [ ] SSH

**Comment by Nadya913** [comment]
QA Tasks:
1. Verify sorting by name for sections: VM, Storage, Images, Accounts
  - lowercase and uppercase, digits, symbols, spaces, by length.
2. Regression:  sorting by name for sections: Firewall, SSH keys.
3. Update the test cases for Test Plan.
4. Update the bugs statistics table.

**Comment by Nadya913** [comment]
Tested for Firewall, SSH keys, Images. Blocked testing for VM, Storage.
Found issues:
http://cs-ui-ci.z1.netpoint-dc.com:8888/736-list-sorting-by-elements/templates?viewMode=Template
Same image appears few times. Please see the attach.
![736-images](https://user-images.githubusercontent.com/33111683/33706904-302cdaa0-db68-11e7-9a55-b66384fb46da.png)
