### ISSUE TITLE
Limit available size of a custom disk offering in volume creation dialog

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#738]
Steps to reproduce:
1. Go to Storage
2. Click on creation button
3. Fill in data, choose a custom service offering in the list (e.g. "test-do-1")
4. Set a size of 2 GB
5. Click CREATE

Actual result: An error occurs "Volume size: 2GB is out of allowed range. Max: 480 Min:10".
Expected result: there are limitations on disk size according to disk offering limits.
  
Please set minimum and maximum disk sizes in slider to avoid this error.

**Connected feature ID:** _storage_disk_create_

![default](https://user-images.githubusercontent.com/26703076/33647045-7b22b07c-da85-11e7-993d-952c04a99a5e.PNG)
![cc](https://user-images.githubusercontent.com/26703076/33647063-90364406-da85-11e7-8396-a5f6af4857c8.PNG)

**Comment by bwsw** [comment]
@ershovaelena @ksendart 
Conventionally first goes Min, next goes Max:
Incorrect: Volume size: 2GB is out of allowed range. Max: 480 Min:10
Correct: 
EN: Volume size 2GB is out of allowed range. Size must be between 10 and 480 GB
RU: Том размером 2GB вне границ допустимого размера. Размер тома должен находиться между 10 и 480 ГБ

**Comment by ksendart** [comment]
@bwsw, Hi! UI gets this error as the response to resizing request from BE. So, this is the typical BE answer, and we do not change it. As the solution for this bug, we should set the valid limits for resizer from account resource and capabilities.
