### ISSUE TITLE
Volume actions should use effects

### ISSUE THREAD

**Issue by zolotyx** [bwsw/cloudstack-ui#742]
1 - Rewrite volume actions to be just a list of actions without any logic
2 - move confirm dialogs to ngrx effects

**Comment by ksendart** [comment]
Test on: http://cs-ui-ci.z1.netpoint-dc.com:8080/ksendart/742-volume-action
Regression: 
vm_disk_snap_create
vm_disk_snap_schedule
vm_disk_resize
vm_disk_snap_display
vm_disk_snap_delete
vm_disk_attach
vm_disk_detach
vm_disk_attached_delete
vm_disk_attach_new
storage_actionbox
storage_snap_create
storage_snap_schedule
storage_disk_resize
storage_disk_attach
storage_disk_detach
storage_disk_delete
storage_snap_delete
