### ISSUE TITLE
Show API key and Secret key in User details and add a copy button

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#745]
1. Request both API key and Secret key in User's tab of Account sidebar
2. Add a copy buttons for both keys (the same as for URL in Image sidebar)

Connected to #625 

**Connected feature ID:** _account_user_apikey_display, account_user_secretkey_display, account_user_apikey_copy, account_user_secretkey_copy_

**Comment by ksendart** [comment]
Test on: http://cs-ui-ci.z1.netpoint-dc.com:8080/ksendart/745-user-keys/accounts
To test: account_user_apikey_display, account_user_apikey_copy, account_user_secretkey_display, account_user_secretkey_copy
Regression: account_user_key_regenerate

**Comment by Nadya913** [comment]
Tested on ksendart/745-user-keys
