### ISSUE TITLE
Disk size selector is empty for custom disk offerings 

### ISSUE THREAD

**Issue by zolotyx** [bwsw/cloudstack-ui#761]
Steps to reproduce:
1. Go to Storage 
2. Click on new volume creation button
3. Choose a custom disk offering in a selector

Expected result: Minimum value is selected by default
Actual result: empty field

**Connected feature ID:** _storage_disk_create_

![emptydo](https://user-images.githubusercontent.com/2853979/33876627-9d59048e-df58-11e7-83a1-d3b1eea7e07b.png)

**Comment by Nadya913** [comment]
Tested on Master
