### ISSUE TITLE
Get rid of BaseModel for AsyncJob model 

### ISSUE THREAD

**Issue by HeyRoach** [bwsw/cloudstack-ui#779]

**Comment by HeyRoach** [comment]
Test on:
HeyRoach/779-base-model-async-job

**Comment by Nadya913** [comment]
**vm_deploy**
No ip value appears for both for  Post Creation dialog 
![779-ip](https://user-images.githubusercontent.com/33111683/34981124-2c368ba4-fad9-11e7-8656-a9e5e147e1b1.png)
and Access VM.

**Comment by HeyRoach** [comment]
This bug was resolved previously and this branch haven`t this changes - i will add it

**Comment by Nadya913** [comment]
**storage_disk_create**
Disk is created even error for disk creation appears. Please see the attach.
Steps:
1. Login and go to Storage
2. Press Add
3. Fill mandatories and press Create
Expected result: Disk created, no errors
Actual result: Disk created and error appears
Chrome text error: Cannot read property 'volume' of undefined
Firefox text error: e.result is undefined
![779-createdisk](https://user-images.githubusercontent.com/33111683/35085311-b2738438-fc5a-11e7-91e2-82d38274c586.png)

**Comment by rennervo** [comment]
Tested on HeyRoach/779-base-model-async-job
