### ISSUE TITLE
Get rid of BaseModel for Volume model

### ISSUE THREAD

**Issue by HeyRoach** [bwsw/cloudstack-ui#791]

**Comment by HeyRoach** [comment]
there is a problem with root disks. Sometimes there are 2 actions in actionbar that appear for root disks (detach and delete), though they should be available only for data disks. This is a model problem, fixed in #630, but it is proposed to make a refactoring in this ticket (c) @ksendart

**Comment by HeyRoach** [comment]
HeyRoach/791-base-model-volume
Test to:
storage_actionbox
storage_disk_resize
storage_disk_attach
storage_disk_detach
storage_disk_delete
storage_description_display
storage_description_change
storage_snap_display
storage_snap_delete,
storage_snap_volume_create

**Comment by Nadya913** [comment]
**storage_disk_resize**
http://cs-ui-ci.z1.netpoint-dc.com:8080/HeyRoach/791-base-model-volume/storage
The card isn't updated for new size after resizing.
Steps:
1. Login and go to Storage
2. Resize any additional volume
Expected:  card is updated for new size
Actual:  card isn't updated for new size

**Comment by Nadya913** [comment]
Tested on HeyRoach/791-base-model-volume
