### ISSUE TITLE
Open a slider for custom disk offerings straightway in disk resize dialog

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#792]
If a drive has a custom disk offering and a user clicks on "resize disk" button, there is a selector with no slider. But there should be a slider directly opened. 

Now you have to choose another offering and then come back to the first one to see a slider that allows you changing the size of a disk (without changing disk offering).

**Connected feature ID:** _storage_disk_resize_

**Comment by ksendart** [comment]
Test on: http://cs-ui-ci.z1.netpoint-dc.com:8080/ksendart/792-resize-slider
To test: 
vm_disk_resize
storage_disk_resize

**Comment by Nadya913** [comment]
Tested on http://cs-ui-ci.z1.netpoint-dc.com:8080/ksendart/792-resize-slider
