### ISSUE TITLE
SSHKey sidebar doesn`t open

### ISSUE THREAD

**Issue by HeyRoach** [bwsw/cloudstack-ui#797]
Steps to reproduce:
1) Go to SSHKeys
2) Click on SSHKeys list entity
Expected result: sidebar is open
Actual result: error appears
![image](https://user-images.githubusercontent.com/11550134/34087449-c5a3736c-e3d5-11e7-9511-316cf4b36a27.png)

**Connected feature ID:** _sshkey_description_display_

**Comment by Nadya913** [comment]
in Testing on master

**Comment by Nadya913** [comment]
Tested on master
