### ISSUE TITLE
Create Storage - zone selection clears the disk offering value 

### ISSUE THREAD

**Issue by Nadya913** [bwsw/cloudstack-ui#801]
http://cs-ui-ci.z1.netpoint-dc.com:8080/bwsw/master/storage/create
user develop
Steps:
1. Login by user
2. Go to Storage
3. Click on disk creation button
4. Select disk offering
5. Select Zone

Expected result:  disk offering value is selected
Actual result:  disk offering is empty

**Connected feature ID:** _storage_disk_create_
![2017-12-18 14-36-53](https://user-images.githubusercontent.com/33111683/34094743-198f2694-e401-11e7-8a09-bc4b098dcb10.png)

**Comment by HeyRoach** [comment]
HeyRoach/801-create-volume-selection-bug
To test: storage_disk_create
