### ISSUE TITLE
Template which is used to create VM should be either public or account-owned

### ISSUE THREAD

**Issue by bwsw** [bwsw/cloudstack-ui#807]
During VM creation only templates which are public or account-owned should be chosen.

**Connected feature ID:** _vm_creation_installsource_

**Comment by ershovaelena** [comment]
TBD in #646

**Comment by ershovaelena** [comment]
@qqcky please check that this problem does not reproduce and close the ticket

**Comment by qqcky** [comment]
Done in #646
