### ISSUE TITLE
Warning message about rebooting VM when user change service offering for stopped VM

### ISSUE THREAD

**Issue by qqcky** [bwsw/cloudstack-ui#810]
**Steps to reproduce:**

1. Go to stopped VM sidebar and click `edit` button in Service Offering section
2. Choose another service offering

**Actual result**: 'The virtual machine will be rebooted' is shown.
**Expected result**: there are no warning messages needed, stopped VM won't be rebooted.

**Connected feature ID:** _vm_SO_change_

![](https://i.imgur.com/up4kaQI.png)

**Comment by ksendart** [comment]
Solved in #712

**Comment by ershovaelena** [comment]
@ksendart please check that this problem does not reproduce and close the ticket

**Comment by ershovaelena** [comment]
consulted with PO. declined

**Comment by ksendart** [comment]
Verified in master
