### ISSUE TITLE
Configure left-side menu view in config file

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#814]
Acceptance criteria:
1. There should be a default view in config file (default - all sections as they are)
2. Allow user to configure the view in config file
3. Logout can not be removed. This element should be present even if it is not set in config
3. Configuring should be possible if reordering #36 is active (also configured in config)
4. To describe the feature in "Custom features" local document and Config Guide

**Connected feature ID:** _sidebar_configure_, _sidebar_reorder_

**Comment by HeyRoach** [comment]
HeyRoach/814-left-menu-config

**Test to:**
sidebar_configure
sidebar_reorder

**This sections was choosen in config file:**
  "cirtual machines", 
  "volumes", 
  "templates",
  "security groups", 
  "events"

**Comment by chewlite** [comment]
_**sidebar_reorder**_
Sections labels moves to left when sorting

**Comment by Nadya913** [comment]
Tested for "Custom features" local document and Config Guide updates

**Comment by rennervo** [comment]
@Nadya913 
Tested on HeyRoach/814-test-config/
As a result of testing, the following bugs were detected:
[issue 992](https://github.com/bwsw/cloudstack-ui/issues/992)
[issue 994](https://github.com/bwsw/cloudstack-ui/issues/994)
[issue 995](https://github.com/bwsw/cloudstack-ui/issues/995)
