### ISSUE TITLE
Implement Private Security Groups tab in Firewall

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#816]
**Acceptance criteria:**
1. "Private Security Groups" tab should be added to switcher
2. Filtering by accounts and search by name above the list
3. "Orphan" ("свободные") checkbox near filtering. This checkbox should appear ONLY if there are existing orphan groups ("VM: unavailable" on SG card). This might happen if VM has been deleted but a group has been not (error or incorrect behavior). 
4. SG card should contain: name, VM (might be "unavailable")
5. Action box: rules, delete (only if there is no VM - for Orphan groups), convert to shared (for now no such feature, it will be done in #821) 
5. Sidebar should represent standard info from original UI (except description)
6. Custom feature - to describe in "Custom features" local doc

**Connected feature ID:**
- _firewall_list_switch_
- _firewall_list_private_orphan_
- _firewall_card_
- _firewall_details_display_

Mockup
![816](https://user-images.githubusercontent.com/26703076/34239209-6878e3b0-e638-11e7-95df-bad98e28c953.jpg)

**Comment by HeyRoach** [comment]
HeyRoach/816-private-sg-tab
Test: firewall_list_switch, firewall_list_private_orphan, firewall_card, firewall_details_display

**Comment by Nadya913** [comment]
Tested on HeyRoach/816-private-sg-tab
**firewall_list_switch**
For list view VM info data isn't alligned and recover the actions. 
Please, see the attach.
![816-listview](https://user-images.githubusercontent.com/33111683/34376840-9e31f05e-eb20-11e7-930d-80dca809cfc3.png)

**Comment by ershovaelena** [comment]
@Nadya913 please note that #821 will be done apart

**Comment by Nadya913** [comment]
firewall_card
For russian language "Вм" is used for card. Expected "ВМ".

**Comment by Nadya913** [comment]
Previous issues fixed.
Tested on http://cs-ui-ci.z1.netpoint-dc.com:8080/HeyRoach/816-private-sg-tab
