### ISSUE TITLE
Disk offering slider is available even if installation source template is chosen

### ISSUE THREAD

**Issue by Nadya913** [bwsw/cloudstack-ui#818]
http://cs-ui-ci.z1.netpoint-dc.com:8080/bwsw/master/instances/create
develop

Steps:
1. Login by user 
2. Press create new VM
3. Select value for Installation source from iso
4. Set custom disk offering to Disk offering slider becomes visible
5. Select value for Installation source from template

Expected result: Disk offering slider is hidden
Actual result: Disk offering slider is available

Please see the attach.
![diskoffering](https://user-images.githubusercontent.com/33111683/34194058-64f9fb3e-e589-11e7-900a-bd26bafe4578.png)

Connected feature Id: vm_creation_installsource, vm_creation_diskoffering

**Comment by qqcky** [comment]
**To test:** 
- _vm_creation_diskoffering_
- _vm_creation_diskoffering_disksize_

**Regression**: _vm_deploy_

To test on `qqcky/818-show-disk-sizer-condition`

**Comment by Nadya913** [comment]
Tested on qqcky/818-show-disk-sizer-condition
