### ISSUE TITLE
Store "SSH description" in account tags if supported

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#824]
**Acceptance criteria:**
1. Store description in account tags if account tags are supported
2. Turn off this feature if account tags are not supported
3. To configure behavior in config file (true - there are account tags)
4. To describe the feature in "Custom features" local file and in Readme

**Connected feature ID:** _sshkey_description_display_, _sshkey_description_change_

**Comment by bwsw** [comment]
@ershovaelena incorrect task description.

**Comment by ershovaelena** [comment]
@bwsw description changed

**Comment by HeyRoach** [comment]
HeyRoach/884-ssh-description
Test to: 
storage_description_display
storage_description_change

**Comment by Nadya913** [comment]
Tested on HeyRoach/884-ssh-description
