### ISSUE TITLE
VM tags bug on multiple change

### ISSUE THREAD

**Issue by qqcky** [bwsw/cloudstack-ui#825]
There are **Steps to reproduce:**
1. Go to VM's details, Tags tab
2. Try to change the value of any Tag twice. 

**Expected result:** The value was changed twice
**Actual result:** The value was changed once. On second time error occurs ""Unable to find resource by uuid undefined and type UserVm".

There should be added an error catch for deleting tag too. So if it cannot be deleted, it should not start to create the updated tag.

**Connected feature ID**: 
- _vm_tag_edit_
- _vm_tag_delete_

![](https://i.imgur.com/wJzboJg.png)

**Comment by qqcky** [comment]
**To test:** 
- _vm_tag_edit_

**Regressions:**
- _vm_tag_create_
- _vm_tag_delete_

Test on `qqcky/825-change-tag-bug`

**Comment by Nadya913** [comment]
Tested on qqcky/825-change-tag-bug
