### ISSUE TITLE
Wrong sorting of elements when "group by" is applied

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#826]
Steps to reproduce (reproduced in all sections):
1. Go to Storage
2. Choose develop and user in account selector
3. Set the following order in "group by" selector: accounts, zones, types (choose all elements)

Expected result: elements are sorted in a lexicographical order. Sometimes order changes. Example:
- develop/develop, then develop/user
- additional volumes/system volumes

Actual result: elements are sorted in a wrong way.

**TO DO**
1. Make sure sorting when group by works in a proper way in all sections
2. Change security groups order in Firewall: system drives should always go first, then custom drives

**Connected feature ID:**
- _vm_list_filter, vm_list_groupby_
- _storage_list_filter, storage_list_groupby_
- _image_list_filter, image_list_groupby_
- _firewall_list_filter_
- _activitylog_filter_
- _sshkey_list_filter, sshkey_list_groupby_
- _account_list_filter, account_list_groupby_
- _firewall_list_template_display_

![default](https://user-images.githubusercontent.com/26703076/34245824-5684df26-e65e-11e7-94cc-ba6b81622ba4.PNG)

**Comment by Nadya913** [comment]
Tested on qqcky/826-group-by-sort-bug
