### ISSUE TITLE
Extra space appears when grouping VM by colors

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#827]
Steps to reproduce:
1. Go to VM list
2. Click group by colors 

Expected result: VMs are grouped
Actual result: VMs are grouped, extra space appears above the list - list moves down a little bit

**Connected feature ID:** _vm_list_groupby_

**Comment by ksendart** [comment]
Test on: http://cs-ui-ci.z1.netpoint-dc.com:8080/ksendart/827-empty-group-name
To test: vm_list_groupby

**Comment by HeyRoach** [comment]
Test on: HeyRoach/827-empty-group-name
To test: vm_list_groupby

**Comment by Nadya913** [comment]
Tested on HeyRoach/827-empty-group-name
