### ISSUE TITLE
Implement a filtering area in Volume Snapshots section

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#830]
A part of an epic #815

Acceptance criteria:
1. Add a filtering by:
- accounts (for domain administrators)
- types
      "HOURLY": "Ежечасные",
      "DAILY": "Ежедневные",
      "WEEKLY": "Еженедельные",
      "MONTHLY": "Ежемесячные",
      "MANUAL": "Вручную"
2. Add group by:
- accounts (for domain administrators)
- types
3. Add a datepicker (like in Activity log) to filter snapshots by creation date
4. Add a search by:
- name (on card)
- description 
- created (date on card)
5. Describe this feature in a local document "Admin extended features"

**Connected feature ID:** 
- _volsnapshot_list_filter_
- _volsnapshot_list_groupby_
- _volsnapshot_list_datepicker_
- _volsnapshot_list_search_

Mockup
![828 830 831](https://user-images.githubusercontent.com/26703076/34249349-047d85e4-e66c-11e7-8654-7b97ae99cd9b.jpg)

**Comment by ershovaelena** [comment]
To check If API does not return VM ID. If not - to discuss with PO

**Comment by qqcky** [comment]
**To test:** 
- volsnapshot_list_filter
- volsnapshot_list_groupby
- volsnapshot_list_datepicker
- volsnapshot_list_search

Test on [`qqcky/830-snapshot-filter-panel`](http://cs-ui-ci.z1.netpoint-dc.com:8080/qqcky/830-snapshot-filter-panel)

**Comment by Nadya913** [comment]
**volsnapshot_list_search**
Searching is by name. Expected: according 4 in ticket description
Add a search by:
name (on card)
description
created (date on card)

**Comment by Nadya913** [comment]
1. For list view seached data isn't highlighted for Created column.  
2. For symbols data also searched data isn't highlighted for Created column.
![830-sym1](https://user-images.githubusercontent.com/33111683/36085399-1d1dcf4a-0ff8-11e8-9348-28a1bec59063.png)
![830-sym2](https://user-images.githubusercontent.com/33111683/36085400-1d413516-0ff8-11e8-8d2b-3ed65d67f362.png)
Expected: all matched data is highlighted
