### ISSUE TITLE
Implement a sidebar in Volume Snapshots section

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#831]
A part of an epic #815

**Acceptance criteria:**
1. State, name and action box above cards
2. Details card (created, type)
3. Description (given during snapshot creation)
4. Volume Information
- VM that the snapshot refers to
- Volume that the snapshot refers to 
Volume info card should appear only if there is VM or a volume that this snapshot refers to. If the snapshot is dangling, do not show this section at all.
5. Add a notification box near the sidebar for pending operations.

**Connected feature ID:**
- _volsnapshot_details_display_
- _volsnapshot_description_display_
- _volsnapshot_volumeinfo_display_
- _volsnapshot_actionbox_

Mockup
![828 830 831](https://user-images.githubusercontent.com/26703076/34249360-11bed758-e66c-11e7-96ac-c8c798b49078.jpg)

**Comment by ershovaelena** [comment]
To check If API does not return VM ID. If not - to discuss with PO

**Comment by qqcky** [comment]
**To test:** 

- volsnapshot_details_display
- volsnapshot_description_display
- volsnapshot_volumeinfo_display
- volsnapshot_actionbox

Test on [`qqcky/831-snapshots-sidebar`](http://cs-ui-ci.z1.netpoint-dc.com:8080/qqcky/831-snapshots-sidebar)`

**Comment by Nadya913** [comment]
**volsnapshot_description_display**
Description is abroad when contains more than 41 symbol. 
![831-desc](https://user-images.githubusercontent.com/33111683/35852938-cdba15a0-0b5e-11e8-81e7-c68108d5eaad.png)

**Comment by qqcky** [comment]
> IE 11 - Created, Type, VM, Volume appears abroad or cut.

Should be solved as a separated task. It is IE layout error with shared component `cs-parameter-pair`. The same problems exist in Account, Volume and other sidebar cards.

@ershovaelena @Nadya913

**Comment by Nadya913** [comment]
Tested on qqcky/831-snapshots-sidebar
