### ISSUE TITLE
Implement Tags tab for Security groups sidebar

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#832]
**Acceptance criteria:**
1. Two tabs in SG sidebar (Firewall and Tags)
2. Firewall tab should have the same icon that left-side menu has 
3. Both tabs names should have tooltips
4. Tags tab is exactly the same as for VM or Image sidebar (see connected feature ID list at the end of description)

**Connected feature ID:**
- _firewall_tag_display_
- _firewall_tag_create_
- _firewall_tag_edit_
- _firewall_tag_delete_
- _firewall_tag_showsystem_
- _firewall_tag_search_

**Comment by HeyRoach** [comment]
HeyRoach/832-security-groups-tags
To test:
firewall_tag_display
firewall_tag_create
firewall_tag_edit
firewall_tag_delete
firewall_tag_showsystem
firewall_tag_search

**Comment by rennervo** [comment]
Tested on HeyRoach/832-security-groups-tags
