### ISSUE TITLE
Inaccurate event drawer view (throbber spacing, text vertical alignment)

### ISSUE THREAD

**Issue by bwsw** [bwsw/cloudstack-ui#837]
Steps to reproduce:
1. Go to VM section
2. Click on VM start
3. Open notification box

Expected result: spinner is well aligned, the first line is aligned with others 
Actual result: inaccurate throbber spacing, text vertical alignment

**Connected feature ID:** _pending_

![](https://box.bw-sw.com/f/97da558f70864431a2b5/?dl=1)

**Comment by HeyRoach** [comment]
Test on: HeyRoach/837-drawer-view
To test: pending
