### ISSUE TITLE
VMs expunge doesn't work if destroying multiple VMs at the same time

### ISSUE THREAD

**Issue by qqcky** [bwsw/cloudstack-ui#838]
**Steps to reproduce:**

1. Go to VMs page 
2. Try to destroy and expunge multiple virtual machines one by one

**Expected result:** Machines disappear from the list
**Actual result:** All machines (sometimes only one disappears) are staying in the list with state `destroying`. They disappear only after reloading the page

Research the reasons of this behavior.

**Connected feature ID:** 
- _vm_destroy_
- _vm_expunge_

![](https://media.giphy.com/media/l0HU4CNS4QHxikLBK/giphy.gif)

**Comment by ksendart** [comment]
test on: http://cs-ui-ci.z1.netpoint-dc.com:8080/ksendart/838-vm-expunge
to test: 
vm_start
vm_stop
vm_reboot
vm_reinstall
vm_destroy
vm_expunge
vm_recover

**Comment by rennervo** [comment]
Tested on http://cs-ui-ci.z1.netpoint-dc.com:8080/ksendart/838-vm-expunge
