### ISSUE TITLE
Firefox - Firewall rules can't be open on vm sidebar for view/edit

### ISSUE THREAD

**Issue by Nadya913** [bwsw/cloudstack-ui#846]
http://cs-ui-ci.z1.netpoint-dc.com:8080/bwsw/master/instances/0892b72f-7a7a-4ebe-aae4-7daffa5e16c2/network
develop
Browser: FF

Steps:
1. Login and press on any vm for opening sidebar
2. Choose network tab
3. Press on button for view/edit firewall rules

Expected result: firewall rules are opened for view/edit
Actual result:  no action 

 **Connected feature ID:** _vm_firewall_display_

**Comment by HeyRoach** [comment]
Test on:
HeyRoach/846-vm-sidebar-firewall

**To test:**
vm_firewall_display

**Comment by Nadya913** [comment]
Tested on HeyRoach/846-vm-sidebar-firewall
