### ISSUE TITLE
no "Password unknown" for VM created from ISO, template with "Password enabled" option set to NO

### ISSUE THREAD

**Issue by Nadya913** [bwsw/cloudstack-ui#847]
According https://github.com/bwsw/cloudstack-ui/issues/573 
http://cs-ui-ci.z1.netpoint-dc.com:8080/bwsw/master/instances
develop

Steps:
1. Login and press Create new VM
2. Fill mandatories and select Installation source  -  ISO or template with "Password enabled" option set to NO 
3. Press create
Expected result:  "Password unknown" is shown
Actual result: no "Password unknown" is shown 

Also it happens for Access VM dialog.

**Connected feature ID:** _vm_accessvm,  vm_postcreation_ISO, vm_postcreation_SSH, vm_postcreation_HTTP_

**Comment by ershovaelena** [comment]
consulted with PO. declined
