### ISSUE TITLE
Access VM - no IP value appears

### ISSUE THREAD

**Issue by Nadya913** [bwsw/cloudstack-ui#851]
http://cs-ui-ci.z1.netpoint-dc.com:8080/bwsw/master/instances
develop
Steps:
1. Login by user
2. For running VM press Access VM in action box

Expected result:  IP value appears as on VM card
Actual result: no IP value appears

**Connected feature ID:** _vm_accessvm_

![noip](https://user-images.githubusercontent.com/33111683/34371163-45402e52-eafd-11e7-8dff-ed87c73e4523.png)

**Comment by HeyRoach** [comment]
Test on:
HeyRoach/851-access-vm-ip

To test:
vm_accessvm

**Comment by Nadya913** [comment]
Tested on HeyRoach/851-access-vm-ip
