### ISSUE TITLE
Card header is not aligned with the content

### ISSUE THREAD

**Issue by zolotyx** [bwsw/cloudstack-ui#853]
1. As you see on the screenshot, card header is not aligned with the content. The same for VM sidebar. Please, fix the content padding
2. Change font style of "Installation source" and "Firewall rules" in VM creation 

**Connected feature ID:** 
- _storage_card_
- _vm_creation_installsource_
- _vm_creation_firewall_template_
- _vm_creation_firewall_shared_

![card header alignment](https://user-images.githubusercontent.com/2853979/34399589-4754a2fe-ebbb-11e7-9bec-75efd51011f7.png)

**Comment by HeyRoach** [comment]
Sidebar!

**Comment by HeyRoach** [comment]
HeyRoach/853-style-fixes
storage_card
vm_creation_installsource
vm_creation_firewall_template
vm_creation_firewall_shared....

**Comment by Nadya913** [comment]
**storage_card**
http://cs-ui-ci.z1.netpoint-dc.com:8080/HeyRoach/853-style-fixes/storage
Storage name isn't alligned with action box.
