### ISSUE TITLE
"Invalid resource type undefined" error appears for creation new VM from template with tags

### ISSUE THREAD

**Issue by Nadya913** [bwsw/cloudstack-ui#857]
http://cs-ui-ci.z1.netpoint-dc.com:8080/bwsw/master/instances/create
develop

Steps:
1. Login and press create new VM
2. For installation source select template with tags
3. Fill all mandatories and press Create

Expected result: VM created with copied tags from template
Actual result: "Invalid resource type undefined" error appears for copying tags

**Connected feature ID:** 
- _vm_creation_installsource_
- _vm_creation_progress_logger_

![invalidresourcetypeundefined](https://user-images.githubusercontent.com/33111683/34402839-f8f9670e-ebd6-11e7-875e-d8a8bb3d4dc2.png)

**Comment by qqcky** [comment]
It is partially fixed in #646, but it is needed to be tested, and fixed, if the error will occur on tag actions with Taggable entities.
