### ISSUE TITLE
VM Creation from template with tags leads to duplicate tags on the VM

### ISSUE THREAD

**Issue by zolotyx** [bwsw/cloudstack-ui#858]
Steps to reproduce:
1. Go to VM creation
2. Choose a template with tags as installation source
3. Fill in all fields and click Create
4. Go to Tags tab in a sidebar of created VM

Expected results: copied tags are displayed one by one
Actual result: copied tags are duplicated

**Connected feature ID:** _vm_creation_installsource, vm_tag_display_

![duplicates](https://user-images.githubusercontent.com/2853979/34406507-0e89150a-ebec-11e7-892a-7d976354efbd.png)

**Comment by HeyRoach** [comment]
Test on:
HeyRoach/858-vm-creation-duplicate-tags
Test to:
vm_tag_display

**Comment by chewlite** [comment]
Tested on: `HeyRoach/858-vm-creation-duplicate-tags`
