### ISSUE TITLE
Add additional fields to SO chooser component in VM creation

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#859]
This issue is a continuation of #502

**Acceptance criteria**
1. Characteristics should be separated in "main" (основные) - was done in #502 and additional (дополнительные)
2. A table should contain main characteristics of each service offering. Additional characteristics should open only when needed 

- Main characteristics: 
-- CPU Cores (Ядра CPU)
-- CPU (MHz) (CPU (МГц))
-- Memory (Память (МБ))
-- Network Rate (Mb/s) (скорость сети)
**- Additional characteristics: all the rest from original CS interface**
3. **A button "Show additional fields" ("Дополнительные характеристики")** should be placed above cancel and save(change)
4. If the button is clicked - additional columns should appear on the right side, user can see it by scrolling
5. Document this feature in Custom features local document

**Pay attention to units of measure!** (not KB, but MB etc)

**Connected feature ID:**
- _vm_creation_so_
- _vm_creation_so_custom_
- _vm_SO_display_
-  _vm_SO_change_

**Comment by ksendart** [comment]
test on: http://cs-ui-ci.z1.netpoint-dc.com:8080/ksendart/859-so-additional-fields
to test: 
vm_creation_so
vm_creation_so_custom
vm_SO_display

**Comment by ksendart** [comment]
ready to test on test on: http://cs-ui-ci.z1.netpoint-dc.com:8080/ksendart/859-so-additional-fields

**Comment by rennervo** [comment]
Failed.
Errors:
1. "Select" / "Change" button is available if the parameters of the selected service have not been changed when creating a VM / editing Custom SO.
**Expected result:** "Select" / "Change" button should don't available when the value of selected CSO isn't changed, but it should be available when the value of selected CSO is changed.
2. Fields of custom SO parameters allow input any characters in browsers **FF** (ver. 58.0.1 64bit), **MS Edge** (ver. 41.16299.15.0) and **MS IE** (ver. 11.192.16299.0)
**Expected result:** These fields allow input only numeric characters.
3. SO doesn't change in browser MS IE (ver. 11.192.16299.0) when editing from sidebar VM.
4. In FF (ver. 58.0.1 64bit) scroll-element is yellow-orange color but in others browser style of scroll-element is gray.

**Comment by ksendart** [comment]
@rennervo 
1. IE, MS Edge, and FF do not support input type=number correctly, that is why you do not see arrows and are able to insert characters into fields. But form provides validation, and if you insert characters, the submit button is disabled (see attached video). I suppose that this type of validation and this kind of form behavior are suitable.
2. I so sorry, but I could not reproduce the second point. I attached the video. All operations performed correctly in MS IE. 
![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/23372522/35893765-0ff9fed4-0be2-11e8-912c-56aebbda2cf4.gif)

**Comment by rennervo** [comment]
@ksendart 
Tested on ksendart/859-so-additional-fields
