### ISSUE TITLE
Manage SOs resource availability in VM creation and SO change dialog

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#860]
**Acceptance criteria:**

The following rules should be applied to VM creation and to SO change dialog (VM sidebar)
1. **Fixed Service offerings**
- Show Service offerings according to User's resources- disable those offerings that are not available for user
- Add a tooltip for disabled SOs "Not enough CPU/RAM"
2. **Custom Service offerings**
- In Custom SO dialog do not let user to change characteristics for more that are available (change numbers in inputs for maximum ones if user tries to put a bigger number)
3. Check sum of all - current offering + new offering < limit (CPU cores, RAM)

**Connected feature ID:** _vm_creation_so_, _vm_SO_change_

**Comment by bwsw** [comment]
@ershovaelena I don't think "filter" is a corect word. I suppose an user must see all, but some as unavailable as not fitting current resource limits.

**Comment by ershovaelena** [comment]
**Additional requirements:**
1. Add a tooltip for Fixed SOs "not enough CPU/RAM" in VM creation and in SO change dialog (VM sidebar)
2. For custom SOs use restrictions and do not let user to change characteristics for more that are available (change numbers in inputs for maximum ones if user tries to out a bigger number)
3. Check sum of all - current offering + new offering < limit (CPU cores, RAM)

**Comment by ershovaelena** [comment]
@qqcky please close this ticket after #932 will be closed. Check unit tests and conflicts.

**Comment by Nadya913** [comment]
**resourceusage_accountdomain**
For user account  switching between account and domain is available. Expected: available only for administrators
![860-account](https://user-images.githubusercontent.com/33111683/36190241-b3f18b40-1189-11e8-8e05-7ffce86c900f.png)

**Comment by ershovaelena** [comment]
Requirements clarification needed. To discuss with PO.
