### ISSUE TITLE
Move "keyboard layout" from VM creation to Settings

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#861]
Acceptance criteria:
1. No keyboard layout in VM creation 
2. New section "VM preferences" in Settings (above "Look and Feel"). Put "Keyborard layout" there. 
3. Default - "Standard (US) keyboard"

Also add information in Wiki -> Tags

**Connected feature ID:** _vm_creation_keyboard_, _settings_keyboard_
**REQ ID:** REQ_SET_013

**Comment by HeyRoach** [comment]
HeyRoach/861-keyboard-layout
To test:
vm_creation_keyboard
settings_keyboard

**Comment by rennervo** [comment]
Failed.
1. Value in "Keyboard layout" field doesn't translate when change language in settings; (All browser)
2. An error occurs (screenshot) and value in "Keyboard layout" doesn't save when used on Windows 10 and browser IE (ver. 11.192.16299.0). Value of keybord in GET request is "undefined" when create a new VM;
![keyboard ie](https://user-images.githubusercontent.com/26665398/35656541-8756582c-072a-11e8-8618-ce216918ace6.png)

**Comment by HeyRoach** [comment]
@rennervo The second one error will be a separated task

**Comment by rennervo** [comment]
It is necessary to show the readiness of changes of the "Keyboard layout" parameter using the value color. (as in the parameters: "First day of the week" and "Time format").

**Actual result:** New value of keyboard layout field has black color immediately after beginning changed.
**Expected result:** Gray color of value of keyboard layout field after beginning of parameter change and black color of this value after ending changed of parameter.

Screenshot of actual result:
![actualkeyboard](https://user-images.githubusercontent.com/26665398/36720752-7d96ce32-1bdb-11e8-9ba0-dd84731b9fc1.png)

Screenshot of expected result:
![expected result](https://user-images.githubusercontent.com/26665398/36721144-aa516b02-1bdc-11e8-9f86-b40ea280f258.png)

**Comment by tamazlykar** [comment]
@bwsw Should this parameter be configured in the config or not?

**Comment by bwsw** [comment]
@tamazlykar you can implement that, but not necessary.

**Comment by rennervo** [comment]
Tested on 1220

1) There is no item "Simplified Chinese keyboard" in VM terminal, therefore, it makes no sense to choose this keyboard value in the settings. It is necessary to discuss this problem with the PM or PO.
![console chinese](https://user-images.githubusercontent.com/26665398/44644189-6cae9180-a9fd-11e8-82a7-a278af23c285.png)

2) Keyboard field is empty in settings for a new user when the first login.
Steps:
1 Create a new user with role Domain Admin or User
2 Login under created user
3 Go to Settings

Actual result: Keyboard field is empty
Expected result: Keyboard field has value "Standard (US) keyboard"
![empty keyboard field for new user](https://user-images.githubusercontent.com/26665398/44644408-2c034800-a9fe-11e8-9dfb-849f1e1b5a2e.png)

3) Keyboard field value is reset when refreshing a page
Steps:
1 Log in and go to Settings
2 Select any value in keyboard field
3 Refresh page

Actual result: There is no value in the keyboard field, even after logout and login
Expected result: The keyboard field contains the selected value

4) The keyboard field value is not translated after changing the language
Steps:
1 Log in and go to Settings
2 Change the language

Actual result: The keyboard field value is not translated
Expected result: The keyboard field value is translated

**Comment by rennervo** [comment]
**Lack: 4**

**Console error with a text "Cannot read property 'lift' of null" appears when VM creating**
(This error is not repeated on master)

**Steps:**
1) Log in as user or domain admin
2) Go to VM and click to "Create" button
3) Click to "CREATE"

**Actual result:** An error occurs during the creation of the VM, the window of creating is not closed
**Expected result:** VM is created without errors

**FEATURE ID:** vm_deploy

**Screenshot:**
![2018-09-21 09-14-02](https://user-images.githubusercontent.com/26665398/45857183-cea2b280-bd81-11e8-8800-20225dde6b79.png)
