### ISSUE TITLE
Assign VM name to private security group when creating VM 

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#862]
**Acceptance criteria:** 

1. Private security groups should have an automatically created name `sg-vm-develop-35` where "vm-develop-35" is the name of its VM
2. Document this feature in "Custom features" local doc

**Connected feature ID:** _vm_creation_firewall_private_name_

**Comment by qqcky** [comment]
**To test:**
vm_creation_firewall_private_name

**Regression:**
vm_deploy

Test on: `qqcky/862-vm-creation-sg-name`

**Comment by rennervo** [comment]
Tested on qqcky/862-vm-creation-sg-name
