### ISSUE TITLE
Check limitations for affinity group creation 

### ISSUE THREAD

**Issue by qqcky** [bwsw/cloudstack-ui#864]
It is not send API requests correctly if creating affinity group's name (in VM creation) has white spaces. It is needed to check is it possible to send request without this limitation, and to fix it.

**Comment by qqcky** [comment]
**To test:** _vm_creation_affinitygroup_.

User is able to create affinity group with alphanumeric name (with any symbols, except commas). There is a limitation for length - 63 symbols.

Test on `qqcky/864-affinity-group-creation-bug`;

**Comment by chewlite** [comment]
Validation conditions for Affinity group:
- 2 symbols at least, 63 is max
- latin and cyrillic symbols
- numbers
- symbols (.?!-_) 
- spaces
- first symbol is letter

Tested: _vm_creation_affinitygroup_
