### ISSUE TITLE
Firewall rules - Sorting  Incoming- Outcoming and allignment buttons issue

### ISSUE THREAD

**Issue by Nadya913** [bwsw/cloudstack-ui#868]
http://cs-ui-ci.z1.netpoint-dc.com:8080/bwsw/master/security-group/1607c4ee-ffe6-43a1-a5bc-111efd1f1c5d/rules?viewMode=templates&query=
develop

Steps:
1. Login and go to Firewall
2. For action box press Rules
3. Group by Types and press Edit

Expected result: Sorting  Incoming- Outcoming, Button Add and Delete are vertical allignment
Actual result: Sorting  Outcoming-Incoming, Button Add and Delete aren't vertical allignment
![firewall-sort.png](https://images.zenhubusercontent.com/59faba338a75884b9085bd93/72f73c83-bc94-45d9-a0ec-cc8a94bfaff6)

**Connected feature ID**: firewall_rules_view, firewall_rules_view_groupby

**Comment by qqcky** [comment]
**To test:**
- _vm_firewall_display_
- _vm_firewall_rules_view_
- _vm_firewall_rules_edit_

Test on `qqcky/868-firewall-rules-view-bug`.

**Comment by chewlite** [comment]
Tested on `qqcky/868-firewall-rules-view-bug`

Failed:
**1) firewall_rules_edit**
_Browser: Firefox_
"Group by" option is selected / isn't selected: Add and Delete buttons aren't vertical alligned

**2) vm_firewall_rules_edit**
_Browser: Chrome / Firefox_
"Group by" option is selected / isn't selected: Add and Delete buttons aren't vertical alligned


**2) vm_firewall_rules_edit**
_Browser: Chrome / Firefox_
"Group by" option is selected / isn't selected: Add and Delete buttons aren't vertical alligned
