### ISSUE TITLE
No message "delete VM's data drives?" when destroying VM

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#870]
Steps to reproduce:
1. Go to VM list
2. Click "delete" of any VM with data drive
3. Click YES in the dialog

Expected result: a dialog appears "Delete this VM's data drives?"
Actual result: no dialog, VM is being deleted

**Connected feature ID:** _vm_destroy_datadrives_

**Comment by qqcky** [comment]
*To test:* 
- _vm_destroy_datadrives_
- _vm_destroy_
- _vm_expunge_
- _storage_disk_detach_
- _storage_disk_delete_

*Regression: *
_vm_disk_display_

Test on: `qqcky/870-vm-delete-disks-bug`

**Comment by rennervo** [comment]
Tested on qqcky/870-vm-delete-disks-bug
