### ISSUE TITLE
Propose to delete Volume snapshots when deleting VM/Volume

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#871]
Acceptance criteria:
1. When destroying a VM: add a checkbox "Delete snapshots?" ("Удалить снимки"?) to the dialog "Delete this VM's data drives?". 
This checkbox should appear **only when data drives have snapshots**
2. When deleting a Volume: add a dialog "Delete this volume's snapshots?" ("Удалить снимки данного диска?") appearing after volume deleting has been approved by user.
This dialog should appear **only when a volume has snapshots**
3. Document this feature in "Custom features" local doc

**Connected feature ID:**
- _vm_destroy_datadrives_snap_
- _storage_disk_delete_snap_

Mockup
![871](https://user-images.githubusercontent.com/26703076/34755373-31af4f9a-f5f6-11e7-92f6-5c73f023c03c.JPG)

**Comment by ksendart** [comment]
test on: http://cs-ui-ci.z1.netpoint-dc.com:8080/ksendart/871-delete-snapshots
to test: 
vm_destroy
vm_expunge
storage_disk_delete
storage_disk_delete_snap
storage_snap_display
storage_snap_delete

**Comment by Nadya913** [comment]
1. **vm_expunge**
Got error for "Failed to detach a volume" when VM was expunged. 
Steps:
1. Login and create new VM
2. For created VM on sidebar create new Volume to attach
3. Attach the Volume
4. Go to VMs and destroy VM, check Expunge

Expected result: disk is deleted
Actual result: error  "Failed to detach a volume"

2. **pending**
Count above Zero is shown. Please, see the attach. Appears in many scenarios: vm creation, vm destroying, disk deleting.
Steps:
1. Login and go to Storage
2. Create new, attach to VM
3. Make shap
4. Delete disk with shapshots
5. Expand the pending list
6. Close pending list

Expected result: no count value appears
Actual result: count value is above zero

![871- expunge](https://user-images.githubusercontent.com/33111683/35794029-957dd81c-0a86-11e8-80b8-12a47dc79144.png)
![871 - count](https://user-images.githubusercontent.com/33111683/35794032-99c03c4e-0a86-11e8-8207-0227e1ccbcdd.png)

**Comment by Nadya913** [comment]
**pending**
Snapshot created but throbber is never ending. 
Steps:
1. Login and select any vm
2. Go to Storage and make 2 snapshots one by one for one disk
3. See the pending operations

Expected result: snapshot taken in pending
Actual result: never ending throbber appears

![871 - snap](https://user-images.githubusercontent.com/33111683/36086196-64485188-0ffd-11e8-8b70-9be0b2ed387c.png)

**Comment by Nadya913** [comment]
If creation snapshot is failed, on pending Failed to delete snapshot appears. Expected: Snapshot failed.
To reproduce  -  Go to Storage and make 2 snapshots one by one for one ROOT disk

![871 - snap2](https://user-images.githubusercontent.com/33111683/36137855-a726e790-10c9-11e8-9137-0ca5200b06e0.png)
