### ISSUE TITLE
Change Group dialog - radiobuttons in one line

### ISSUE THREAD

**Issue by Nadya913** [bwsw/cloudstack-ui#872]
http://cs-ui-ci.z1.netpoint-dc.com:8080/bwsw/master/instances/331c3a91-b6b6-4b58-b739-18ba687db7e7/vm
develop
Browser: Chrome

Steps:
1. Login and change Interface Language to Russian in Settings
2. Go to VM
3. Change Group or Affinity group in sidebar

Expected: radiobuttons in different lines and alligned left
Actual: radiobuttons in one line

**Connected feature ID**: _vm_afgroup_change, vm_group_change_

![affinity.png](https://images.zenhubusercontent.com/59faba338a75884b9085bd93/2fe584d7-f994-48fc-8ccf-e8c198679000)
![instance.png](https://images.zenhubusercontent.com/59faba338a75884b9085bd93/9bfc3f2b-a937-4536-ab33-ce452f040886)

**Comment by qqcky** [comment]
**To test:**
- _vm_afgroup_change_
- _vm_group_change_
- _image_group_change_

Test on `qqcky/872-radio-buttons-view`.

**Comment by rennervo** [comment]
Bug: Group change field is not available in the Images Sidebar.
Branch: qqcky/872-radio-buttons-view
![fail ticket](https://user-images.githubusercontent.com/26665398/34975858-64345ad0-fac6-11e7-9da8-e17d8b88296c.png)

**Comment by rennervo** [comment]
Tested on qqcky/872-radio-buttons-view
