### ISSUE TITLE
Error "Invalid resource type undefined" for creating tags

### ISSUE THREAD

**Issue by Nadya913** [bwsw/cloudstack-ui#876]
Error "Invalid resource type undefined" appears for creating system and custom tags.
http://cs-ui-ci.z1.netpoint-dc.com:8080/bwsw/master/instances/e76e963b-c54c-404e-8da8-3800d7144542/tags
develop

Steps:
1. Login and press on any VM
2. Go to tags and press add button
3. Fill key and value
4. Press Create

Expected result: tag created
Actual result: Error "Invalid resource type undefined" appear
![tagError.png](https://images.zenhubusercontent.com/59faba338a75884b9085bd93/9654100f-a6d5-4fda-9b89-06fcea060997)

**Connected feature ID**: vm_tag_create

**Comment by qqcky** [comment]
*To test:* _vm_tag_create_

Test on `qqcky/876-creation-tag-bug`.

**Comment by rennervo** [comment]
The error has been fixed on the corresponding branch.
Branch: bwsw/876-creation-tag-bug
