### ISSUE TITLE
Dialog does not close after creation of SSH key with not autogenerated public key

### ISSUE THREAD

**Issue by qqcky** [bwsw/cloudstack-ui#878]
**Steps to reproduce:**

- Go to SSH keys and try to create new one
- Input your own public key

**Expected result:** SSH key was created, dialog was closed
**Actual result:** SSH key was created, but dialog is still open

![SSH Key Creation](https://images.zenhubusercontent.com/5971bcd561b4ca3b0a7537c1/bc336494-7c28-4f30-b553-bea08c01556c)

**Comment by qqcky** [comment]
**To test:**
- _sshkey_create_

Test on: `qqcky/878-ssh-key-creation-bug`.

**Comment by chewlite** [comment]
Tested on `qqcky/878-ssh-key-creation-bug.`
