### ISSUE TITLE
Show "Password: no information" when template with "password enabled: no"

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#888]
**Acceptance criteria:**

Show "Password: no information" when VM's template with "Password enabled" option set to NO
- in VM creation (post-VMcreation dialog #2)
- in Access VM dialog #573 

**Connected feature ID:** 
- _vm_postcreation_ISO_
- _vm_postcreation_SSH_
- _vm_postcreation_HTTP_
- _vm_accessvm_

**Comment by HeyRoach** [comment]
HeyRoach/888-password-vm
To test:
vm-accessvm

**Comment by chewlite** [comment]
**vm_postcreation_ISO**
There is "Password: No information" but ISO doesnt have option "Password enabled"

**vm_accessvm**
1) VM created from ISO: 
there is "Password: No information" but ISO doesnt have option "Password enabled"
2) VM created from Template with "Password enabled" option set to YES:
after page refreshing there is "Password: No information" _(repeated on master)_

**Comment by chewlite** [comment]
vm_postcreation_SSH, vm_postcreation_HTTP

**Comment by chewlite** [comment]
**_vm_postcreation_SSH, vm_postcreation_HTTP_**
VM created from Template with with "Password enabled" option set to NO

**_vm_accessvm_**
VM created from Template

**Comment by chewlite** [comment]
**_vm_accessvm_**
VM created from Template with "Password enabled" option set to NO:
after refresh "Password: undefined" appears ("Password: No information" is required)

**Comment by chewlite** [comment]
Tested on: `HeyRoach/888-password-vm`
