### ISSUE TITLE
Get rid of BaseModel for BaseTemplate model

### ISSUE THREAD

**Issue by HeyRoach** [bwsw/cloudstack-ui#893]
- BaseTemplateModel

- IsoModel

- TemplateModel

**Comment by HeyRoach** [comment]
HeyRoach/893-base-template-model

**Test to:**
image_list_switch
image_card
image_actionbox
image_delete
image_list_filter
image_list_groupby
image_list_search
image_template_create
image_iso_create

**Comment by rennervo** [comment]
Errors on HeyRoach/893-base-template-model: 

1) **ISO can not be deleted.** Text from dialog of error: "Please specify a valid template."
Actual result: ISO isn't deleted. The error there is.
Expected result: ISO is deleted.
![iso delete](https://user-images.githubusercontent.com/26665398/36959877-f5417870-2076-11e8-92a1-4d194eea270b.png)

2) **Filter "Select account" in Images list allows for role "User"** 
Actual result: Filter allows for role "User"
Expected result: Filter absents for role "User"
![selectaccuser](https://user-images.githubusercontent.com/26665398/36960700-c0fb33b8-207a-11e8-8f5e-9c86ac760c36.png)

3) **Can not read properties "split" and "filter" when transfered on Tags tab immediately after ISO creating**
After completing steps below, execution of JS code is terminated and further work in current window isn't possible without refresh of page.
**Steps:**
 - Log in and go to Images
 - Create new Template or ISO
 - Go to Tags tab of sidebar of new image


4) **Throbber absents when creating of Images**
Actual result: When creating new images there isn't throbber.
Expected result: When creating new images there is throbber.


5) **ISO images are absent in list for VM creation dialog**
Steps:
 - Log in and go to VM
 - Go to VM creation dialog
 - Go to "Installation source" in tab "ISO"
Actual result: Message "No result"
Expected result: List of available ISO
![isovm](https://user-images.githubusercontent.com/26665398/36962141-f0422e00-2080-11e8-85ec-8fedf3f6f583.png)

**Comment by HeyRoach** [comment]
1
2 +
3
4
5

**Comment by chewlite** [comment]
**1. Template sidebar: Template tab**
No "Type" in General information

**2. Template/ISO sidebar: Zones tab**
There are Status field and UPDATE button when download is completed
![2018-08-24 10-42-24](https://user-images.githubusercontent.com/32011943/44563886-82685080-a78a-11e8-83af-c7d29d8a740d.png)

**Comment by rennervo** [comment]
Tested on 948
