### ISSUE TITLE
VM Tags are not displayed correctly when the number of characters in the Key field is large

### ISSUE THREAD

**Issue by rennervo** [bwsw/cloudstack-ui#898]
Url: http://cs-ui-ci.z1.netpoint-dc.com:8080/bwsw/master/instances/98a3717f-7dcc-4b81-b423-402ebf33f3a7/tags
User: develop

Steps:
1. Login by develop
2. Go to VM
3. Click to any VM
4. Go to Tags
5. Create a new tag with 40 or more characters in the Key field

Actual result: Value of the Key field The value of the Key field is outside the display of the tags. The buttons for editing and deleting the tag are not available for clicking.

Expected result: The value of the Key field on the tag display has a display restriction for '...'. The buttons for editing and deleting the tag are available.

**Connected feature ID**: _vm_tag_display_

![Key Field Longer.png](https://images.zenhubusercontent.com/5a5c77c24b5806bc2bc2be22/cbf0fade-7192-418f-a3c8-f7b56887df79)

**Comment by qqcky** [comment]
**To test**:
- vm_tag_display
- image_tag_display

Test on `qqcky/898-tag-key-view`

**Comment by chewlite** [comment]
Tested on: `qqcky/898-tag-key-view`
