### ISSUE TITLE
Create support-info.md and show it in all error messages

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#904]
This issue covers the following requirements:
[REQ_GEN_009] A user should have an opportunity to view support informtation in all error messages 

Mockup
![904](https://user-images.githubusercontent.com/26703076/35134619-0cbc9cae-fd0a-11e7-9792-ee856c02bcb2.jpg)

**Comment by bwsw** [comment]
Please, don't use camel case for file names.

**Comment by HeyRoach** [comment]
HeyRoach/904-support-information

**To test:**
supportinfo

**Comment by HeyRoach** [comment]
Todo:

- [ ] tests

**Comment by rennervo** [comment]
Lack: 1

**There is extra space in the drop-down list of support information**
Empty space should be missing from the support information drop-down list.

**Steps:**
1) Trigger a window call error

**Actual result:** In the drop-down list with error information there is extra space on top. (see screenshot)
**Expected result:** There is no extra space in the drop-down list with information about the error.

**REQ_ID:** REQ_GEN_009
![extra space in the drop-box list of support information](https://user-images.githubusercontent.com/26665398/51459433-31857400-1d8b-11e9-852b-32e23ba870cd.png)
