### ISSUE TITLE
"Incorrect password" error occurs for empty domain or invalid username 

### ISSUE THREAD

**Issue by rennervo** [bwsw/cloudstack-ui#912]
Url: http://cs-ui-ci.z1.netpoint-dc.com:8080/bwsw/master/login

"Incorrect password" error appears for empty domain or invalid username values for login page.

Steps:
1. Go to login page;
2. Enter invalid username or empty domain;
3. Enter valid value for other fields
4. Click on "LOGIN" button.

Actual result: Error "Incorrect password" appears
Expected result: Error "Invalid username or password" appears

**Connected feature ID**: login_default, login_url, login_domain
Screenshot:
![Error of Username.png](https://images.zenhubusercontent.com/5a5c77c24b5806bc2bc2be22/71882c87-729c-4e73-97d7-2f867ca664d3)

![Error of Domain field.png](https://images.zenhubusercontent.com/5a5c77c24b5806bc2bc2be22/5add1081-4605-4565-8597-9e233c6b7b60)

**Comment by HeyRoach** [comment]
HeyRoach/912-login-error
Test to:
login_default
login_domain

**Comment by rennervo** [comment]
Tested on HeyRoach/912-login-error
