### ISSUE TITLE
Private security group is not deleted when destroying owning VM

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#913]
1. Go to VM list
2. Choose any VM with private SG, check its private SG name
2. Click on "destroy" for any VM
3. Approve VM destroying (with expunge)
4. Go to Firewall - Private SG

Expected result: private SG of destroyed VM is not in the list
Actual result: private SG of destroyed VM is in the list

**Connected feature ID:** 
- _firewall_private_vm_display_
- _vm_destroy_
- _vm_expunge_

**Comment by ksendart** [comment]
test on: http://cs-ui-ci.z1.netpoint-dc.com:8080/ksendart/913-private-sg
to test: vm_destroy, vm_expunge

**Comment by chewlite** [comment]
@ksendart

**Tested on:**  `ksendart/913-private-sg`
