### ISSUE TITLE
SG name "Default" is created when creating a VM with Shared Firewall Rules

### ISSUE THREAD

**Issue by rennervo** [bwsw/cloudstack-ui#921]
Url: http://cs-ui-ci.z1.netpoint-dc.com:8080/bwsw/master/instances/create
User: develop
If select one or multiple shared firewall rules, then sg name of new VM will be "Default".

Steps:
1. Log in, go to VM and press Add;
2. Select Firewall rules;
3. Go to "Select Shared", select one or multiple rules and confirm;
4. Press Create;

Actual rezult: SG name is "Default"
Expected rezult: SG name is names of Shared firewall rules

Screenshot:
![SG Name.png](https://images.zenhubusercontent.com/5a5c77c24b5806bc2bc2be22/8be156e8-6d41-4b1c-ab63-aa02f0e198ea)

**Comment by qqcky** [comment]
**To test:**
vm_creation_firewall_template
vm_creation_firewall_shared

**Regression:** vm_firewall_display

Test on `qqcky/921-vm-creation-shared-sg-bug`.

**Comment by chewlite** [comment]
for @qqcky 

**vm_firewall_display**
If a VM was created without changes in Firewall rules then rules are not displays in the Sidebar when clicking View

**vm_creation_firewall_template**
Changes of settings are not displayed again if: 
1) change tab "Create new" to tab "Select Shared" and back
2) open the "Firewall Rules" dialog after saving сhanges

**Comment by chewlite** [comment]
for @qqcky 

**Tested on:** `qqcky/921-vm-creation-shared-sg-bug`
