### ISSUE TITLE
Stopping VM's wrong state bullet

### ISSUE THREAD

**Issue by qqcky** [bwsw/cloudstack-ui#923]
**Step to reproduce:** Go to VM section and try to stop VM

**Expected result:** VM is stopping, state bullet is yellow
**Actual result:** VM is stopping, state bullet is green (after reloading the page, state bullet is white).

**Connected feature:** vm_card, vm_stop

![](https://media.giphy.com/media/26DMWTRmwpLssZ71e/giphy.gif)

**Comment by qqcky** [comment]
**To test:**
- vm_card
- vm_stop

Test on `qqcky/923-vm-state-bug`

**Comment by chewlite** [comment]
Tested on: `qqcky/923-vm-state-bug`
