### ISSUE TITLE
Implement snapshots list in VM snapshots

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#925]
A part of an epic #412

This issue covers the following requirements:
1. [REQ_SNAP_LIST_010] A user should be able to view the list of VM snapshots
2. [REQ_SNAP_LIST_015] A user should be able to revert VM to VM snapshot
3. [REQ_SNAP_LIST_016] A user should be able to delete VM snapshots

Mockup

![925](https://user-images.githubusercontent.com/26703076/35896647-c76ce376-0bef-11e8-8892-006605e566f1.jpg)

**Comment by tamazlykar** [comment]
To test:
[REQ_SNAP_LIST_010] A user should be able to view the list of VM snapshots
[REQ_SNAP_LIST_014] A user should be able to create a volume snapshot from a VM snapshot
[REQ_SNAP_LIST_015] A user should be able to revert VM to VM snapshot
[REQ_SNAP_LIST_016] A user should be able to delete VM snapshots

**Comment by rennervo** [comment]
Lack: 1

**1) The domain admin does not see snapshots of other accounts**

The domain admin must be able to view and interact with VM snapshots of users and other domain admins, similar to the volume's snapshot section.

Steps to reproduce:
1) Create VM snapshots for a user and two different domain admins
2) Log in as Domain admin
3) Go to "Snapshots" section on "VM" tab

Actual result: Domain admin view only itself VM snapshots
Expected result: Domain admin view all VM snapshots in the current domain

**2) Action box of VM snapshots does not open in list mode**

Steps to reproduce:
1) Create one VM snapshot
2) Go to "Snapshots" section on "VM" tab
3) Select list mode
4) Click to action box of VM snapshot

Actual result: The action box does not open.
Expected result: the action box opens.

**3) The option "Revert VM to snapshot" is available for pressing in the transition state of the VM**

The "Revert VM to snapshot" option should be available for clicking only when the VM is in the "Running" status. In any other case, including in the transition state, the option should be unavailable for pressing.

Steps to reproduce:
1) Create a VM snapshot
2) Select "Stopped" option in action box of VM
3) Go to "Snapshots" section on 'VM" tab
4) Click to action box of VM snapshots

Actual result: The option "Revert VM to snapshot" is available to pressing (if VM did not have time to go to the "Stopped" status)
Expected result: The option "Revert VM to snapshot" isn't available for pressing.

**Comment by tamazlykar** [comment]
@rennervo
3. This is a bug because of the wrong server response, decided not to fix now.

**Comment by rennervo** [comment]
Tested on 1421
