### ISSUE TITLE
User's secret key copy button is out of the layout

### ISSUE THREAD

**Issue by qqcky** [bwsw/cloudstack-ui#927]
http://cs-ui-ci.z1.netpoint-dc.com:8080/bwsw/master/accounts/35711808-7b9d-461d-a345-646585b14c64/users
user
**Steps to reproduce:**
(Only with russian interface)
  1. Login by user and go to `Accounts` section
  2. Open account's sidebar and tab `Users`
  3. Expand user

Expected result: key is shown, copying of the key is available
Actual result: key is shown, but copy button isn't. 
Error code, text in console: 
432  "The user is not allowed to request the API command or the API command does not exist"

![927-userkeycopy](https://user-images.githubusercontent.com/33111683/35494429-19153c78-04ed-11e8-86a8-1bf86f6508a1.png)

**Comment by HeyRoach** [comment]
HeyRoach/927-users-secret-key

**Test to:**
account_user_secretkey_copy

**Comment by rennervo** [comment]
Tested on HeyRoach/927-users-secret-key
