### ISSUE TITLE
Implement VM snapshots section in VM sidebar

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#928]
A part of an epic #412 
Connected to #925 

This issue covers the following requirements:
1. [REQ_VM_DTLS_039] A user should be able to view information about VM snapshots in VM details sidebar
2. [REQ_VM_DTLS_054] A user should be able to view all VM snapshots in VM details sidebar 
3. [REQ_VM_DTLS_040] A user should be able to create VM snapshots in VM details sidebar
4. [REQ_VM_DTLS_042] A user should be able to revert  VM to VM snapshot in VM details sidebar
5. [REQ_VM_DTLS_043] A user should be able to delete VM snapshots in VM details sidebar

Mockup

![928](https://user-images.githubusercontent.com/26703076/35545535-0f9c71ce-05a2-11e8-8963-b06e405cecba.jpg)

**Comment by tamazlykar** [comment]
To test:
REQ_VM_DTLS_039
REQ_VM_DTLS_054
REQ_VM_DTLS_040
REQ_VM_DTLS_042
REQ_VM_DTLS_043

**Comment by Nadya913** [comment]
1. No restrictions for name, description for length (255 symbols), error for can't create snapshot appears
2. Tooltips for long name, description appears far from labels
![tooltip](https://user-images.githubusercontent.com/33111683/49916916-9bc71100-fecf-11e8-858f-22d201d6a251.png)
3. Actions are available for snapshot in progress
Expected: actions are disabled for snapshot in progress status
4. Double : for Russian language in VM Snapshot last snapshot

**Comment by tamazlykar** [comment]
@Nadya913 #1428
