### ISSUE TITLE
Support data volume management limitations for VMs with VM snapshots

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#934]
A part of the Epic #412 

This issue covers the following requirements:
1. [REQ_VM_DTLS_044] A user cannot attach and detach data volumes to VMs that have VM snapshots
2. [REQ_STORAGE_LIST_016] A user cannot attach and detach data volumes to VMs that have VM snapshots
3. [REQ_VM_DTLS_045] A user cannot delete data volumes of VMs that have VM snapshots
4. [REQ_STORAGE_LIST_017] A user cannot delete data volumes of VMs that have VM snapshots
5. [REQ_VM_DTLS_047] A user cannot resize data disks of VMs that have VM snapshots
6. [REQ_STORAGE_LIST_018] A user cannot resize data disks of VMs that have VM snapshots

See [Apache Cloudstack official documentation](http://docs.cloudstack.apache.org/projects/cloudstack-administration/en/latest/virtual_machines.html?highlight=snapshot#virtual-machine-snapshots)

**Comment by HeyRoach** [comment]
Test:

[REQ_VM_DTLS_044]
[REQ_STORAGE_LIST_016]
[REQ_VM_DTLS_045]
[REQ_STORAGE_LIST_017]
[REQ_VM_DTLS_047]
[REQ_STORAGE_LIST_018]

**Comment by rennervo** [comment]
### 1) The dialog for deleting disk images appears when trying to remove a disk
According to the requirements of [REQ_STORAGE_LIST_017] and [REQ_VM_DTLS_045], the user cannot delete disks that are attached to a VM that has VM snapshots. Accordingly, the next steps after removing the disc should not be initiated in this case.

**Steps:**
1. Attach an additional disk to the VM without snapshots
2. Create a snapshot for additional disk
3. Create a snapshot for VM
4. Select the action to remove the additional disk and confirm

**Actual result:** In addition to the error of the impossibility of deleting a disk, the dialog for selecting deleting disk snapshots appears.
**Expected Result:** Only the error of failure to remove the disk appears.

**REQ_ID:** REQ_STORAGE_LIST_017, REQ_VM_DTLS_045

![delete and storage snapshot](https://user-images.githubusercontent.com/26665398/51733715-d1f1d600-20b4-11e9-8262-1236bfe16087.png)

### 2) Incorrect error text when changing the size of the root disk

It is necessary to replace the current text of the error when changing the size of the disk, on the text without mentioning a specific type of disk.

**Steps:**
1. Change localization to Russian
2. Create a snapshot for a VM without a snapshot.
3. Go to resize the root of the disk (sidebar VM or section "Storage")
4. Increase disk size and confirm

**Actual result:** Error text: "Изменение размера дополнительных дисков не доступно для ВМ с активными снимками" in Russian, "Data disk resize is unavailable for VMs with active snapshots" in English
**Expected result:** Text of the error: “Изменение размера диска недоступно для ВМ с активными снимками” in Russian, “Disk resize is unavailable for VMs with active snapshots” in English

**REQ_ID:** REQ_VM_DTLS_047, REQ_STORAGE_LIST_018

![root disk resize message](https://user-images.githubusercontent.com/26665398/51733723-dc13d480-20b4-11e9-8ef0-4ec04a52f0d5.png)

**Comment by rennervo** [comment]
Tested on 1521
