### ISSUE TITLE
Chrome (Mac OS) - problems with displaying ISO tab and activity log table

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#937]
Reproduced in Chrome, Mac OS

1. Go to Images: ISO tab is cut off

<img width="690" alt="2018-01-30 14 50 13" src="https://user-images.githubusercontent.com/26703076/35554919-f6caf1f6-05cf-11e8-936b-7631748dfb8e.png">

2. Go to Activity Log - table is deformed, has a huge size

<img width="1219" alt="2018-01-30 15 12 33" src="https://user-images.githubusercontent.com/26703076/35554935-0dc007f2-05d0-11e8-8f89-e27599ad1e55.png">

**Comment by HeyRoach** [comment]
1) to solve
2) it works as expected for me

**Comment by chewlite** [comment]
@tamazlykar 
This problem no longer exists
