### ISSUE TITLE
System doesn't allow creating names of Affinity groups with special characters when VM Create

### ISSUE THREAD

**Issue by rennervo** [bwsw/cloudstack-ui#939]
When create VM  can not create or select name of Affinity group with special characters, but it's possible in sidebar of deployed VM.

Steps:
1. Log in and go to VM;
2. Press Add / Click on any VM;
3. Select or create Affinity Group with special charaters in name.

Actual result: Not allows create names of Affinity group with special characters when create VM, but from sidebar of VM it's possible.
Expected result: When create VM and in VM sidebar allowed create Affinity Group name like this:
the first symbol is a letter and the others can be any characters, except commas.

Connected Feature ID: 
vm_afgroup_change, 
vm_creation_affinitygroup

Screenshots:
![AfGCreate.png](https://images.zenhubusercontent.com/5a5c77c24b5806bc2bc2be22/f0d24d33-ef12-4ec7-a6b2-d7e185382c5f)
![AffGSidebar.png](https://images.zenhubusercontent.com/5a5c77c24b5806bc2bc2be22/4a97e5c3-1b37-4e45-b4b1-96dfbc5261f8)

**Comment by HeyRoach** [comment]
HeyRoach/939-affinity-group-creation

Test to:
vm_afgroup_change,
vm_creation_affinitygroup

**Comment by tamazlykar** [comment]
@Nadya913 please test this issue. 
See HeyRoach comment

**Comment by chewlite** [comment]
@tamazlykar 

Semicolon is invalid

**Comment by tamazlykar** [comment]
@chewlite please provide a full specification that name should follow.
Because the solution provided by @HeyRoach fulfills the initial requirement.

**Comment by chewlite** [comment]
@tamazlykar 
I was guided just by the information in the description of the ticket

**Comment by tamazlykar** [comment]
@chewlite test on:
tamazlykar/939-affinity-group-name-validator
