### ISSUE TITLE
Template description is abroad for more than 40 characters

### ISSUE THREAD

**Issue by rennervo** [bwsw/cloudstack-ui#941]
Url: http://cs-ui-ci.z1.netpoint-dc.com:8080/bwsw/master/templates/
User: Develop

If description of Template is more than 40 then it goes abroad.

Steps:
1. Log in and go to Images;
2. Create Template with long description;
3. Go to sidebar of created template;

Actual result: Description goes abroad;
Expected result: Description is transferred to a new line when the end of the current line is reached.

Connected feature ID: 
image_description_display

Screenshot:
![Your eyes is clear like sky, down isn't, stopped it move.png](https://images.zenhubusercontent.com/5a5c77c24b5806bc2bc2be22/8bae91b4-26d3-4e21-b1b5-562630940a3d)

**Comment by HeyRoach** [comment]
HeyRoach/941-template-description

Test:
image_description_display

**Comment by Nadya913** [comment]
@HeyRoach 
Branch got 503 error.
http://cs-ui-ci.z1.netpoint-dc.com:8080/HeyRoach/941-template-description

**Comment by HeyRoach** [comment]
This branch is available now

**Comment by Nadya913** [comment]
Tested on 
HeyRoach/941-template-description
