### ISSUE TITLE
Keep the position of a left-side bar (collapsed/expanded)

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#944]
**Acceptance criteria:**

The position of a left-side bar (collapsed/expanded) should be remembered after 
- reloading the page
- going to another section 
- within the section
- login/logout

**Connected feature ID:** _sidenav_show_

**Comment by HeyRoach** [comment]
HeyRoach/944-sidebar-hide

Test to:
sidebar_hide

**Comment by chewlite** [comment]
for @HeyRoach 

**_sidebar_hide_**

Setting is saved when change user

**Comment by ershovaelena** [comment]
The idea is to use user tags for this feature

**Comment by tamazlykar** [comment]
Use user tags for this feature

**Comment by tamazlykar** [comment]
Regression:
sidenav_show

**Comment by chewlite** [comment]
Tested on 1194
