### ISSUE TITLE
Add "Account tags" and "User tags" tabs to Settings

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#947]
This issue covers the following requirements:
[REQ_SET_015] A user should be able to manage account tags and user tags in Settings

**Comment by ershovaelena** [comment]
When implementing this requirement, please check out if we need to create a separate task for refactoring account tags (ngrx)

**Comment by ershovaelena** [comment]
![settings-tags](https://user-images.githubusercontent.com/26703076/51167931-72d4da00-18da-11e9-88bf-9ab63cd398ff.png)
![settings-tags2](https://user-images.githubusercontent.com/26703076/51167932-736d7080-18da-11e9-9d68-6be73335838f.png)

@bwsw please take a look at mockups provided by @HeyRoach. Do you have any comments? Can we implement tags section based on these mockups ?

**Comment by HeyRoach** [comment]
Test: 
REQ_SET_015

**Comment by rennervo** [comment]
Lack: 1

### 1) Section names in settings are not translated into Russian
It is necessary that the section names in the settings change depending on the selected location.

**Steps:**
1. Go to the settings section
2. Change the language to Russian

**Actual result:** Section names "Account tags" and "User tags" in English
**Expected result:** Section titles in Russian
![sections not russian](https://user-images.githubusercontent.com/26665398/51823837-21cdd880-2313-11e9-976a-fd561e977dd5.png)

### 2) You can not create 2 or more tags without reloading the page
At the moment, the system does not create the second and subsequent tags in the "Account / User Tags" sections. It is necessary to reload the page each time to create a new tag.

**Steps:**
1. Go to the settings section
2. Open the section "Account tags" or "User tags"
3. Go to tag creation
4. Fill in the fields correctly and confirm
5. Repeat steps 3 and 4.

**Actual result:** The second tag is not created, there are no requests to the API.
**Expected result:** The second tag is created and displayed in the tag list, requests to the API are present.

### 3) You cannot remove 2 or more tags without reloading the page
At the moment, the system does not delete the second and subsequent tags in the "Account / User Tags" sections. You must reload the page each time to remove the next tag.

**Steps:**
1. Go to the settings section
2. Open the section "Account tags" or "User tags"
3. Select the delete action for any tag.
4. Confirm the action
5. Repeat steps 3 and 4.

**Actual result:** The second tag is not deleted, there are no requests to the API.
**Expected result:** The second tag is deleted and is not displayed in the tag list, requests to the API are present.
