### ISSUE TITLE
Root/Data volumes wrong sorting 

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#949]
Steps to resproduce: Go to Storage.
1. Expected result: Root drives (System volumes) go first, then Data drives (Additional Volumes)
Actual result: Alphabetical sorting (additional go first)
2. Expected result: Alphabetical sorting **within** root drives and data drives
Actual result: General alphabetical sorting
3. Expected result: When group by types is applied - system volumes go first.
Actual result: Data drives (Additional Volumes) go first, then Root drives (System volumes)

**Connected feature ID:** _storage_distinct_rootdata, storage_list_groupby_

**Comment by HeyRoach** [comment]
HeyRoach/949-sort-volume

Test to:
storage_distinct_rootdata
storage_list_groupby

**Comment by chewlite** [comment]
for @HeyRoach 

**_storage_list_groupby_**

**1)** Accounts not in the alphabetical order when 
- grouping by Accounts 
![group_by_accounts](https://user-images.githubusercontent.com/32011943/36086446-053bf828-0fff-11e8-86ef-40110198f5e0.png)
- Accounts on the top in nesting of grouping
![group_by_accounts_and_others](https://user-images.githubusercontent.com/32011943/36086450-0a44c11a-0fff-11e8-8228-448ed8e86560.png)

**2)** Additional then System volumes when Types not on the top in nesting of grouping
![group_by_smth_then_types](https://user-images.githubusercontent.com/32011943/36086456-1403b134-0fff-11e8-9671-47800a1a969a.png)

**Comment by HeyRoach** [comment]
Todo:
Discuss the second one with PM

**Comment by qqcky** [comment]
**Test on:** `qqcky/949-sort-volume`

**Test to:**
- storage_distinct_rootdata
- storage_list_groupby

**Comment by chewlite** [comment]
@qqcky 
Tested on qqcky/949-sort-volume
