### ISSUE TITLE
Assign service offerings to classes in config.json

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#950]
**Acceptance criteria:**

1. Move assigning SO to classes from account tags to config.json (related to #502, #498) 
2. Document this feature in Config guide and local doc "Custom features"
3. Remove account tag from wiki

**Connected feature ID:** 
- vm_SO_change
- vm_creation_so
- vm_creation_so_custom

**Comment by ksendart** [comment]
http://cs-ui-ci.z1.netpoint-dc.com:8080/ksendart/950-so-classes
vm_SO_display
vm_SO_filter
vm_SO_change

**Comment by Nadya913** [comment]
Tested on ksendart/950-so-classes
Tested for wiki, config guide, custom features
