### ISSUE TITLE
Disk offering style, layout, font issue for VM creation, Disk offering dialog

### ISSUE THREAD

**Issue by Nadya913** [bwsw/cloudstack-ui#958]
1. No title for Disk offering chooser dialog. Expected: "Choose Disk Offering" ("Выберите дисковое предложение")
![title](https://user-images.githubusercontent.com/33111683/35719359-bbd8725a-081b-11e8-8246-f7fc4071bf55.png)
2. Slider tooltip value is cut on left border. Expected: no cutting
3. Selected disk offering has same h4 style with 16 font size as for header. Expected: font-size 11 as for service offering (for example
![style](https://user-images.githubusercontent.com/33111683/35719598-bb4c1c46-081c-11e8-8503-f3787736fc66.png)
)
**Connected feature Id**: vm_creation_diskoffering, vm_creation_diskoffering_disksize

**Comment by HeyRoach** [comment]
HeyRoach/958-do-styles

Test to:
vm_creation_diskoffering,
vm_creation_diskoffering_disksize

Regression:
storage_diskoffering_display

**Comment by Nadya913** [comment]
**vm_creation_diskoffering**
 Title for Disk offering chooser dialog has h4 style. Expected: "Choose Disk Offering" ("Выберите дисковое предложение") h3 style as for the others titles.

**Comment by qqcky** [comment]
After #1063 will be done, this issue can be moved to verify.

**Comment by tamazlykar** [comment]
@qqcky The problem is not solved completely, the size of the header in the dialog box about which Nadya spoke was not changed.

**Comment by tamazlykar** [comment]
Should there be any explanation before the name of the selected disk, as in the other sections ("Service offering:", "OS template:")?
@Nadya913 let me know, please.

**Comment by tamazlykar** [comment]
PO said that most likely the dialogue will be redone. Therefore, we leave it as it is.

**Comment by tamazlykar** [comment]
Test on:
tamazlykar/958-vm-creation-dialog-styles

**Comment by tamazlykar** [comment]
@rennervo fixed. Test again please :)

**Comment by rennervo** [comment]
Tested on tamazlykar/958-vm-creation-dialog-styles
