### ISSUE TITLE
Separating strip isn't middle alligned for Service offering dialog

### ISSUE THREAD

**Issue by Nadya913** [bwsw/cloudstack-ui#960]
http://cs-ui-ci.z1.netpoint-dc.com:8080/bwsw/master/instances
develop
Browser Firefox

Steps:
1. Login and press on any VM
2. Press edit for Service offering change in sidebar

Expected: Separating strip is middle alligned for tabs and Searching
Actual: Separating strip isn't middle alligned for tabs and Searching

![separate](https://user-images.githubusercontent.com/33111683/35723131-c0545c94-082b-11e8-92ec-078775f5c8bb.png)

**Connected feature ID**: vm_creation_so, vm_creation_so_custom, vm_SO_change

**Comment by HeyRoach** [comment]
You mean that this dialog should looks like this:
![image](https://user-images.githubusercontent.com/11550134/35840539-913b1280-0b29-11e8-81ab-440a03f209ca.png)

**Comment by HeyRoach** [comment]
HeyRoach/960-so-styles

Test to:
vm_creation_so,
 vm_creation_so_custom,
 vm_SO_change

**Comment by ershovaelena** [comment]
Already fixed on master
