### ISSUE TITLE
Items values for ICMP type and ICMP code are cut for Shared SG and Custom firewall templates

### ISSUE THREAD

**Issue by rennervo** [bwsw/cloudstack-ui#961]
Items values for "ICMP type" and "ICMP code" fields are truncated when editing rules of Shared SG and Custom Firewall Templates.

Steps:
1. Log in and go to Firewall;
2. Click on action box of custom template firewall / shared SG and select "Rules";
3. Press Edit and select Protocol type is ICMP;
4. Press on ICMP type field, after selecting the value, press on ICMP code field.

Actual result: Names of items are cut-off
Expected result: Drop-down is larger (double size), names of items are visible.

Connected Feature ID: firewall_rules_edit

Screenshot:
![tooltips](https://user-images.githubusercontent.com/26665398/35723893-7c9f9c68-082e-11e8-8f69-45922cc9c9bf.png)

**Comment by qqcky** [comment]
**To test** _firewall_rules_edit_

Test on [`qqcky/961-selectors-tooltips`](http://cs-ui-ci.z1.netpoint-dc.com:8080/qqcky/961-selectors-tooltips)

**Comment by chewlite** [comment]
@qqcky 

Safari has it's own tooltips, therefore tooltips are duplicate - was discussed with PM and submitted for discussion with PO

**Comment by ershovaelena** [comment]
Two ways possible: to add tooltips or to make dropdown larger (e.g. double width). To discuss with PO.

**Comment by ershovaelena** [comment]
@tamazlykar Discussed with PO: to make dropdown larger (e.g. double width). Description changed

**Comment by tamazlykar** [comment]
**Test on:**
tamazlykar/961-dropdown

**Regression**
firewall_rules_edit

**Comment by chewlite** [comment]
Tested on:
tamazlykar/961-dropdown
