### ISSUE TITLE
No asterisks for mandatories in Account creation, User creation and User editing dialogs

### ISSUE THREAD

**Issue by chewlite** [bwsw/cloudstack-ui#964]
http://cs-ui-ci.z1.netpoint-dc.com:8080/bwsw/master/accounts

Steps:
1. Go to Accounts 
2. Open:
    2.1 Account creation dialog
    2.2 User creation dialog
    2.3 User editing dialog 

Actual result: There are no asterisks next to mandatories
Expected result: There are asterisks next to mandatories

![no asterisks in acc creation](https://user-images.githubusercontent.com/32011943/35777391-a0122820-09df-11e8-9344-95c0562eb731.jpg)
![aster new user](https://user-images.githubusercontent.com/32011943/35777390-9fed98e8-09df-11e8-97dc-aee48aceb19e.jpg)
![aster edit user](https://user-images.githubusercontent.com/32011943/35777389-9fc21ace-09df-11e8-95c6-2fe32b318219.jpg)

**Connected Feature ID:**
_account_create
account_user_create
account_user_edit_

**Comment by qqcky** [comment]
**To test**
- _account_create_
- _account_user_create_
- _account_user_edit_

Test on [`qqcky/964-asterisks-bug`](http://cs-ui-ci.z1.netpoint-dc.com:8080/qqcky/964-asterisks-bug)

**Comment by rennervo** [comment]
@qqcky 
Domain administrator cannot edit users of account with role "User". Required tab isn't in the user's action box on sidebar of account.
![masteruser](https://user-images.githubusercontent.com/26665398/36657867-d7867dec-1b00-11e8-9992-701349727385.png)
![branchuser](https://user-images.githubusercontent.com/26665398/36657887-ed26704e-1b00-11e8-8624-0610a860ccf2.png)

**Comment by qqcky** [comment]
@rennervo Could you check it again please?

**Comment by chewlite** [comment]
@qqcky 
This issue with editing is no longer repeated
