### ISSUE TITLE
Incorrect sorting in Accounts right after creation 

### ISSUE THREAD

**Issue by chewlite** [bwsw/cloudstack-ui#965]
http://cs-ui-ci.z1.netpoint-dc.com:8080/bwsw/master/accounts

Right after creating an account that alphabetically should take the last place in the list, it stands the penultimate one. After refresh all accounts are correctly sorted

Steps:
1. Go to Account creation
2. Fill the Username by the name which in alphabetical order should be after all existing accounts
3. Input all mandatories and click Create

Actual result: Account card stands the penultimate
Expected result: Account card stands the last

**Before refresh:**
![account before refresh](https://user-images.githubusercontent.com/32011943/35788150-054d6796-0a66-11e8-9825-05aa6ed53560.png)
**After refresh:**
![account after refresh](https://user-images.githubusercontent.com/32011943/35788154-0cc1526c-0a66-11e8-9b9c-083ecf4bd4e4.png)
**Connected Feature ID:**
_account_create_
_box_list_view_

**Comment by chewlite** [comment]
Repeated for the Storage

**Comment by tamazlykar** [comment]
@chewlite I can't reproduce the problem. Please check if it exists on the master branch.

**Comment by chewlite** [comment]
@tamazlykar 
Yes, this bug isn't reproduced now
