### ISSUE TITLE
Error appears when change settings - IE

### ISSUE THREAD

**Issue by HeyRoach** [bwsw/cloudstack-ui#978]
Browser IE (Windows 10, version 11.192.16299.0)

Steps:
1. Go to Settings
2. Change the value of option (Language or first day of week) 
3. Go to another page
4. Return to the settings again and check value of options

Expected: The new option of settings was choosen and the new value was saved (in Account tags)
Actual: The error appears and the new value of settings didn't saved

![image](https://user-images.githubusercontent.com/11550134/35900089-a9ad4aa2-0c02-11e8-86d5-5f6e130ceeb9.png)

**Connected feature ID:** settings_language_change, settings_firstdayweek_change

**Comment by HeyRoach** [comment]
Check that error represents on master when #932 will be done

**Comment by ershovaelena** [comment]
Move this issue to Verify after #1059 is closed

**Comment by tamazlykar** [comment]
The problem is not reproduced anymore. Test the master branch.

**Comment by chewlite** [comment]
@tamazlykar 
The problem is not reproduced anymore
