### ISSUE TITLE
Data in Sidebar appears empty, abroad or cut in IE

### ISSUE THREAD

**Issue by Nadya913** [bwsw/cloudstack-ui#983]
http://cs-ui-ci.z1.netpoint-dc.com:8080/bwsw/master/storage/d04ac325-5139-445b-bed6-760529bfa262/volume
develop

IE 11 - Data in Sidebar appears abroad and cut in IE. It's IE layout error with shared component cs-parameter-pair.
Sidebars: VM, Storage, Snapshots, Accounts, Firewall

![ie-sidebar](https://user-images.githubusercontent.com/33111683/35955431-f1a223e0-0cc1-11e8-900d-a6aa7ac7a690.png)
![831-ierus](https://user-images.githubusercontent.com/33111683/35955490-37277f6e-0cc2-11e8-9eac-d8fd58773f6d.png)

**Connected feature IDs:** 
vm_SO_display 
storage_diskoffering_display
volsnapshot_details_display
volsnapshot_description_display
volsnapshot_volumeinfo_display
account_limits_display
firewall_details_display

**Comment by pm-Egor-Genning** [comment]
https://github.com/bwsw/cloudstack-ui/pull/1074

**Comment by pm-Egor-Genning** [comment]
983-sidebar-values-for-parameters

**Comment by rennervo** [comment]
If values are long, they are superimposed on parameter headers in Sidebar.

Steps:
1. Log in and go to Firewall or Snapshot
2. Select firewall group with long name or description (with long volume name for snapshot)
3. Go to Sidebar of selected object

Actual result: Long value is superimposed on parameter header
Expected result: Zone of parameter header and zone of value are separated. Superimposition is impossible.

Screenshots:
![long values in firewall sidebar](https://user-images.githubusercontent.com/26665398/39860125-61b641c0-5466-11e8-82cf-f85ec2dd302d.png)
![long volume name in snapshot sidebar](https://user-images.githubusercontent.com/26665398/39860142-746a942e-5466-11e8-98d3-75223ee03853.png)

**Comment by ershovaelena** [comment]
@tamazlykar  rebuid the branch for testing. inform @chewlite when ready for testing

**Comment by chewlite** [comment]
@pm-Egor-Genning 
Tested on:
pm-Egor-Genning/983-sidebar-values-for-parameters

**Comment by tamazlykar** [comment]
@chewlite please test it again on
tamazlykar/983-sidebar-values

**Comment by chewlite** [comment]
@tamazlykar 

![2018-05-23 15-37-10](https://user-images.githubusercontent.com/32011943/40413128-456b76b4-5e9f-11e8-93bc-474d62e40c0c.png)

**Comment by chewlite** [comment]
@tamazlykar 
Can't check _storage_diskoffering_display, volsnapshot_volumeinfo_display_
because to create the volume is impossible

**Comment by tamazlykar** [comment]
@chewlite check again, now it works. It wasn't a code bug.

**Comment by rennervo** [comment]
Tested on tamazlykar/983-sidebar-values
