### ISSUE TITLE
Empty SG card in private SG 

### ISSUE THREAD

**Issue by Nadya913** [bwsw/cloudstack-ui#989]
The issue happens if VM is created with errors (card with only one option Delete) and this VM is destroyed. Private SG for this vm isn't updated. 

Steps:
1. Create VM with error - (such vm can be created with exceeded cpu limit)
2. Destroy this vm
3. Go to Private SG 

Expected result: filled correct data list/card private sg appear
Actual result: empty card for private sg
![sg](https://user-images.githubusercontent.com/33111683/36141101-2698b1be-10d6-11e8-9a66-b6b50f5a82dc.png)

**Comment by tamazlykar** [comment]
Unable to reproduce error, please provide more detailed info @Nadya913 .
After step 1 I get Error and there is no vm to delete for step 2.
In Private SG I did not found any empty card

**Comment by Nadya913** [comment]
I created wrong VM (vm-develop-1059), would you please try to reproduce with this vm?

Updated Steps:
1. Create new VM with custom wrong characteritics: 2x10015 MHz | 518.00 MB
2. Got error, refresh the page and see this vm, destroy it
3. Go to Private SG

**Comment by tamazlykar** [comment]
Thanks, I was able to reproduce the problem with your specifications.
This problem only appears if you did not wait for the removal (expulsion) of your virtual machine to complete and moved to the SG private tab.
But, I think that the problem should not be with an empty SG, but with the fact that when an error occurs during the creation process, the machine was created and it must be manually deleted.

**Comment by tamazlykar** [comment]
Update to my comment.
PO explained that creating VM with error and not delete it automatically is the default behavior for Cloudstack. So we need to fix the issue as it is explained by Nadya.

**Comment by tamazlykar** [comment]
**Test on:**
tamazlykar:989-empty-sg

**Comment by chewlite** [comment]
Tested on:
tamazlykar:989-empty-sg
