### ISSUE TITLE
Tabs Domain in VMs and Private SGs in Firewall aren't active after refresh

### ISSUE THREAD

**Issue by chewlite** [bwsw/cloudstack-ui#991]
Steps 
1. Go to Firewall then Private Security Groups tab
2. Refresh page

Expected result: Private SGs tab is active
Actual result: Firewall Templates tab is active

The similar issue happens with Domain tab in VMs
_Before refresh_
![domain_is_active](https://user-images.githubusercontent.com/32011943/36298702-f985fe90-132b-11e8-8488-ffcbdead73a6.png)
_After refresh_
![acount_is_active](https://user-images.githubusercontent.com/32011943/36298703-f9a861f6-132b-11e8-8328-4b0af81af1a4.png)

**Connected Feature ID:** 
_resourceusage_accountdomain
firewall_list_switch_

**Comment by tamazlykar** [comment]
Test on:
tamazlykar/991-tab-memory-issue

Regression:
resourceusage_accountdomain
firewall_list_switch

**Comment by chewlite** [comment]
Bugs:

**_resourceusage_accountdomain_**
1) State of switch is saved after logout 
2) State of switch is saved for other user

**_firewall_list_switch_**
1) State of switch is saved after: change section + refresh + logout
2) State of switch is saved after: change section + refresh + logout + login under other user

**Comment by chewlite** [comment]
@tamazlykar @ershovaelena 
Right, it'll be the other issue
