### ISSUE TITLE
Reset of left-side menu settings after refresh of page

### ISSUE THREAD

**Issue by rennervo** [bwsw/cloudstack-ui#992]
Order and state of visibility of items of the left-side menu are reset when refresh of page.

Pre-conditions for config.json:
"allowReorderingSidebar": true; 
In "sidebarOrder" there is several elements (Example: "sidebarOrder": ["setting", "ssh", "events", "volumes", "vms"]);

Steps:
1. Log in and go to left-side menu editing mode;
2. Make changes and exit left-side menu editing mode;
3. Refresh page.

Actual result: Left-side menu settings are reset after refreshing page;
Expected result: Left-side menu settings are saved after refreshing page;

Connected feature: sidebar_configure, sidebar_reorder

**Comment by tamazlykar** [comment]
**Test on:**
tamazlykar/995-sidenav

Regression:
 sidebar_configure, sidebar_reorder

**Comment by chewlite** [comment]
Tested on:
tamazlykar/995-sidenav
