### ISSUE TITLE
Grammatical error in Fixed/Custom SO switcher in VM creation

### ISSUE THREAD

**Issue by chewlite** [bwsw/cloudstack-ui#993]
Steps:
1. Set interface language as Russian 
2. Go to VM creation 
3. Go to SO choosing

Expected result: text on switcher "Фиксированные|Настра**И**ваемые"
Actual result: text on switcher "Фиксированные|Настра**Е**ваемые"

![default](https://user-images.githubusercontent.com/32011943/36300143-9421b59c-1332-11e8-8e47-419d08aaee5e.png)
**Connected Feature ID:**
_vm_creation_so_

**Comment by tamazlykar** [comment]
**Test on:**
tamazlykar/993-grammatical-error

**Regression:**
vm_creation_so

**Comment by rennervo** [comment]
Tested on tamazlykar/993-grammatical-error
