### ISSUE TITLE
Reset of items order of left-side menu after logout + log in

### ISSUE THREAD

**Issue by rennervo** [bwsw/cloudstack-ui#994]
Url: http://cs-ui-ci.z1.netpoint-dc.com:8080/bwsw/master/
State of elements of sidebar "enabled/disabled" is saved, but their order isn't saved when logout + log in.

Pre-conditions for config.json:
"allowReorderingSidebar": true;
In "sidebarOrder" there is several elements (Example: "sidebarOrder": ["setting", "ssh", "events", "volumes", "vms"]);

Steps:

1. Log in and go to left-side menu editing mode;
2. Change order of items and exit left-side menu editing mode;
3. Logout and log in 

Actual result: Reset of items order of left-side menu. Items order is default;
Expected result: Items order is saved after logout + log in;

Connected feature: sidebar_configure, sidebar_reorder

**Comment by tamazlykar** [comment]
Will be done in #995

**Comment by tamazlykar** [comment]
**Test on:**
tamazlykar/995-sidenav

Regression:
 sidebar_configure, sidebar_reorder

**Comment by chewlite** [comment]
Tested on:
tamazlykar/995-sidenav
