### ISSUE TITLE
Settings of left-side menu items for other users is changed when change of this menu for a current user

### ISSUE THREAD

**Issue by rennervo** [bwsw/cloudstack-ui#995]
Order and available state of left-side menu items are changed for all users of domain after setting of left-side menu for any domain user.

Pre-conditions for config.json:
"allowReorderingSidebar": true;
In "sidebarOrder" there is several elements (Example: "sidebarOrder": ["setting", "ssh", "events", "volumes", "vms"]);

Steps:

1. Log in and go to left-side menu editing mode;
2. Make changes and exit left-side menu editing mode;
3. logout and log in as another user of this or other account.

Actual result: Settings of left-side menu items is changed for all users of domain;
Expected result: Settings of left-side menu items for each domain user is independent of other users settings;

Connected feature: sidebar_configure, sidebar_reorder

**Comment by tamazlykar** [comment]
Will be fix #992 #994

**Comment by tamazlykar** [comment]
**Test on:**
tamazlykar/995-sidenav

Regression:
 sidebar_configure, sidebar_reorder

**Comment by chewlite** [comment]
Tested on:
tamazlykar/995-sidenav

**Comment by chewlite** [comment]
@tamazlykar 

1. When change menu settings for user_1 and log in under user_2 then bug is repeated, if there was no changes for user_2 before.
2. If, after first step, you change menu of user_2 and log in under user_1 the menu of user_1 will not change

**Comment by chewlite** [comment]
Tested on:
tamazlykar/995-sidenav
