### ISSUE TITLE
IPv4/IPv6 filter layout issue in Firewall rules view

### ISSUE THREAD

**Issue by chewlite** [bwsw/cloudstack-ui#996]
Steps:
1. Go to Firewall
2. Go to Rules view of some template/security group

Expected result: IPv4/IPv6 filter on the right side of two other filters
Actual result: IPv4/IPv6 filter on the left side of two other filters

![filters](https://user-images.githubusercontent.com/32011943/36366028-cd16a698-157e-11e8-87fd-4faa04b00a20.png)

**Connected Feature ID:** 
_firewall_rules_view
vm_firewall_rules_view_

**Comment by tamazlykar** [comment]
@chewlite this is not a bug, there is no specification that defines a right order of the fields. It was discussed with PO.
