### ISSUE TITLE
Ability to add a Firewall rule when incorrect IP 

### ISSUE THREAD

**Issue by chewlite** [bwsw/cloudstack-ui#997]
Steps:
1. Go to Firewall
2. Go to Rules editing
3. Fill all mandatories correctly and

**_3.1_**  in "CIDR v4/v6" input IPv4/IPv6 without subnet mask length 
Expected result: IP is invalid, add-button is disabled
Actual result: IP is valid, add-button is enabled
![valid cidr](https://user-images.githubusercontent.com/32011943/36404533-ced7091a-161d-11e8-87cb-b306f3a27b03.png)

**_3.2_**  in "CIDR v4/v6" input invalid IPv4/IPv6 (with special symbols for example)
Expected result: IP is invalid, add-button is disabled
Actual result: IP is invalid, but add-button is enabled
![invalid cidr but add is enable](https://user-images.githubusercontent.com/32011943/36372061-74223486-1596-11e8-82a6-66895844fa86.png)

**Connected Feature ID:**
_firewall_rules_edit
vm_firewall_rules_edit_

**Comment by ershovaelena** [comment]
TBD in #1019

**Comment by tamazlykar** [comment]
Test on: 
tamazlykar/997-cidr

Connected Feature ID:
firewall_rules_edit
vm_firewall_rules_edit

**Comment by chewlite** [comment]
@tamazlykar 
Tested on:
tamazlykar/997-cidr

**Comment by tamazlykar** [comment]
The new library used in #1078 broke IE.

**Comment by tamazlykar** [comment]
Please test same functionality in different browsers

Test on:
tamazlykar/997-cidr

**Comment by chewlite** [comment]
@tamazlykar 
Tested on: tamazlykar/997-cidr
